package wouldyourather

var Questions = []WouldYouRather{
	{"Have the ability to fly", "Be invisible"},
	{"Live in a world with no technology", "Live in a world with no nature"},
	{"Have a photographic memory", "Ability to forget anything you want"},
	{"Always speak your mind", "Never speak again"},
	{"Explore the deep ocean", "Explore outer space"},
	{"Be a famous celebrity for one day", "Be an average person for your entire life"},
	{"Control time", "Read minds"},
	{"Always have to tell the truth", "Always lie"},
	{"Travel to the past", "Travel to the future"},
	{"Have unlimited wealth", "Have unlimited wisdom"},
	{"Communicate with animals", "Speak all human languages"},
	{"Live without music", "Live without books"},
	{"Teleport", "Clone yourself"},
	{"Be a superhero with hidden identity", "Be a supervillain with known identity"},
	{"Live without the internet", "Live without air conditioning/heating"},
	{"Speak to the dead", "See into the future"},
	{"Have super strength", "Have super intelligence"},
	{"Only eat sweet foods", "Only eat savory foods"},
	{"Change your appearance at will", "Change the weather at will"},
	{"Be a master of all musical instruments", "Be a master of all sports"},
	{"Be able to time travel at will", "Be able to read minds"},
	{"Live in a world without pain", "Live in a world without fear"},
	{"Have the power of invisibility", "Have the power of teleportation"},
	{"Always be overdressed", "Always be underdressed"},
	{"Never have to sleep", "Never have to eat"},
	{"Have the ability to control fire", "Have the ability to control water"},
	{"Live without the ability to taste", "Live without the ability to smell"},
	{"Experience the beginning of the universe", "Experience the end of the universe"},
	{"Be able to speak with your past self", "Be able to speak with your future self"},
	{"Have the power to heal others", "Have the power to heal yourself instantly"},
	{"Be able to communicate with plants", "Be able to communicate with inanimate objects"},
	{"Have unlimited stamina", "Have unlimited creativity"},
	{"Have the ability to control the weather", "Have the ability to control luck"},
	{"Be the funniest person in the room", "Be the smartest person in the room"},
	{"Always have perfect health", "Always have perfect wealth"},
	{"Be able to speak all languages fluently", "Be a master of all musical instruments"},
	{"Have the power to stop time for 10 seconds at a time", "Have the power to rewind time by 10 seconds"},
	{"Live in a world where everyone knows your thoughts", "Live in a world where everyone hears your inner monologue"},
	{"Be able to erase one bad memory", "Be able to relive one good memory"},
	{"Have the ability to control animals' behavior", "Have the ability to control technology with your mind"},
	{"Be able to speak every language fluently", "Be a master of every musical instrument"},
	{"Have the ability to fly like a bird", "Swim underwater like a fish"},
	{"Live in a world where it's always daytime", "Live in a world where it's always nighttime"},
	{"Have a lifetime supply of your favorite food", "Have a lifetime supply of your favorite drink"},
	{"Be an expert at playing chess", "Be an expert at playing poker"},
	{"Have the power to control the weather", "Have the power to control people's emotions"},
	{"Be a professional athlete in any sport", "Be a famous actor or actress"},
	{"Always know the truth but never be believed", "Always be believed but never know the truth"},
	{"Live in a treehouse in a forest", "Live in a houseboat on a lake"},
	{"Have the ability to time travel to the past", "Have the ability to see into the future"},
	{"Be a famous historical figure", "Be a famous future visionary"},
	{"Be able to control machines with your mind", "Be able to communicate with animals"},
	{"Have the power to change one event in history", "Have the power to predict one event in the future"},
	{"Be able to instantly learn any skill", "Be able to erase any bad memory"},
	{"Live in a world without music", "Live in a world without movies and TV shows"},
	{"Have a personal chef", "Have a personal masseuse"},
	{"Be a famous artist", "Be a famous scientist"},
	{"Have the ability to freeze time", "Have the ability to rewind time"},
	{"Always have perfect hair", "Always have perfect teeth"},
	{"Travel to space and visit other planets", "Explore the depths of the oceans and discover new species"},
	{"Be able to talk to animals", "Be able to talk to plants"},
	{"Have a flying car", "Have a robot assistant"},
	{"Live in a house made entirely of chocolate", "Live in a house made entirely of glass"},
	{"Be able to change your appearance at will", "Be able to change your voice at will"},
	{"Have the ability to change your age", "Have the ability to change your gender"},
	{"Be able to control fire", "Be able to control ice"},
	{"Have the power to erase any law from existence", "Have the power to create a new law"},
	{"Be a famous professional athlete", "Be a famous musician"},
	{"Always have to wear formal attire", "Always have to wear pajamas"},
	{"Be able to communicate with people through thoughts", "Be able to communicate with people through dreams"},
	{"Be a superhero with super strength", "Be a superhero with the power of flight"},
	{"Always have perfect health", "Always have perfect relationships"},
	{"Live in a world where money doesn't exist", "Live in a world where technology doesn't exist"},
	{"Be a character in your favorite video game", "Be a character in your favorite book"},
	{"Have the power to instantly learn any language", "Have the power to instantly solve any mathematical problem"},
	{"Be a famous stand-up comedian", "Be a famous movie director"},
	{"Always have the ability to find something you lost", "Always know the answer to any question"},
	{"Be a detective solving real-life mysteries", "Be a space explorer discovering new planets"},
	{"Have the ability to control your dreams", "Have the ability to control the dreams of others"},
	{"Be able to talk to your past self", "Be able to talk to your future self"},
	{"Live in a world with talking animals", "Live in a world with sentient robots"},
	{"Be able to see in complete darkness", "Be able to see through solid objects"},
	{"Have the ability to heal any illness", "Have the ability to cure any phobia"},
	{"Be able to control the minds of others", "Be able to control the elements (fire, water, earth, air)"},
	{"Always have the perfect outfit for any occasion", "Always have the perfect comeback in any argument"},
	{"Be a professional athlete in a sport of your choice", "Be a famous actor in a genre of your choice"},
	{"Live in a world with magical creatures", "Live in a world with advanced alien civilizations"},
	{"Have the power to bring fictional characters to life", "Have the power to travel into fictional worlds"},
	{"Be able to communicate with the deceased", "Be able to communicate with extraterrestrial beings"},
	{"Have the ability to jump to any location instantly", "Have the ability to read people's thoughts"},
	{"Be a famous fashion designer", "Be a famous architect"},
	{"Always have the perfect weather", "Always have the perfect health"},
	{"Live in a world with no internet", "Live in a world with no electricity"},
	{"Be able to visit any historical event", "Be able to witness any future event"},
	{"Have the power to bring peace to the world", "Have the power to end world hunger"},
	{"Be able to manipulate probability", "Be able to control the laws of physics"},
	{"Always have the ability to find parking easily", "Always have the ability to avoid traffic"},
	{"Live in a world with dragons", "Live in a world with advanced artificial intelligence"},
	{"Be a master of every form of art", "Be a master of every form of science"},
	{"Have the ability to speak and understand animals", "Have the ability to speak and understand plants"},
	{"Be a famous chef", "Be a famous novelist"},
	{"Always know when someone is lying", "Always know when someone is attracted to you"},
	{"Live in a world with constant adventure and danger", "Live in a world with constant peace and tranquility"},
	{"Have the power to control your dreams", "Have the power to control the weather"},
	{"Be able to control and manipulate time", "Be able to control and manipulate matter"},
	{"Always have a personal assistant", "Always have a personal trainer"},
	{"Live in a world with unlimited resources", "Live in a world with unlimited knowledge"},
	{"Be able to change your appearance at will", "Be able to change your location at will"},
	{"Have the power to prevent natural disasters", "Have the power to prevent human conflicts"},
	{"Always know the answer to any riddle or puzzle", "Always win at any game of chance"},
	{"Live in a world where everyone is always honest", "Live in a world where everyone has telepathic abilities"},
	{"Be a famous singer", "Be a famous dancer"},
	{"Have the ability to instantly learn any instrument", "Have the ability to instantly learn any language"},
	{"Always have perfect memory", "Always have perfect intuition"},
	{"Live in a world with mythical creatures", "Live in a world with advanced technology"},
	{"Be able to communicate with the spirit world", "Be able to communicate with parallel universes"},
	{"Have the power to eliminate all pollution", "Have the power to cure all diseases"},
	{"Always find the good in every situation", "Always find the humor in every situation"},
	{"Live in a world with time travel technology", "Live in a world with advanced space travel technology"},
	{"Be able to control your emotions at will", "Be able to control the emotions of others"},
	{"Have the ability to change your physical age", "Have the ability to change your personality traits"},
	{"Always have the best seat in any venue", "Always have the best view from any location"},
	{"Live in a world with magic spells and potions", "Live in a world with advanced virtual reality"},
	{"Be able to manipulate dreams and nightmares", "Be able to control the flow of time"},
	{"Have the power to bring extinct species back to life", "Have the power to communicate with aliens"},
	{"Always have the ability to resolve conflicts peacefully", "Always have the ability to inspire others"},
	{"Live in a world with talking mythical creatures", "Live in a world with highly advanced AI companions"},
	{"Be able to create and manipulate holographic images", "Be able to control the weather with your thoughts"},
	{"Have the power to create unlimited clean energy", "Have the power to cure mental illnesses"},
	{"Always know when someone is thinking about you", "Always know when danger is imminent"},
	{"Live in a world where dreams come true", "Live in a world where wishes are granted"},
	{"Be able to teleport instantly to any location", "Be able to clone yourself"},
	{"Have the power to erase any painful memory", "Have the power to predict the future accurately"},
	{"Always have the perfect timing", "Always have the perfect charisma"},
	{"Live in a world with time loops and alternate realities", "Live in a world with advanced cybernetics and augmentation"},
	{"Be able to control your body temperature at will", "Be able to control your own luck"},
	{"Have the power to restore any damaged ecosystem", "Have the power to end poverty worldwide"},
	{"Always have the ability to find hidden treasures", "Always have the ability to make people laugh"},
	{"Live in a world with talking plants", "Live in a world with sentient robots as companions"},
	{"Be able to communicate with animals through gestures", "Be able to communicate with spirits and ghosts"},
	{"Have the power to instantly heal physical wounds", "Have the power to restore lost memories"},
	{"Always be the best at any physical activity", "Always be the best at any intellectual pursuit"},
	{"Live in a world with time manipulation technology", "Live in a world with advanced genetic engineering"},
	{"Be able to change your gender at will", "Be able to change your appearance at will"},
	{"Have the power to end all conflicts with a single word", "Have the power to bring about world peace"},
	{"Always know the best decision to make in any situation", "Always know the thoughts of those around you"},
	{"Live in a world with talking animals and plants", "Live in a world with highly advanced AI servants"},
	{"Be able to control the elements (earth, air, fire, water)", "Be able to control the emotions of others"},
	{"Have the power to make anyone instantly fall in love", "Have the power to eliminate all hatred from the world"},
	{"Always have the ability to instantly heal any illness", "Always have the ability to calm any emotional turmoil"},
	{"Live in a world where everyone has superpowers", "Live in a world where advanced technology is indistinguishable from magic"},
	{"Be able to control and manipulate dreams", "Be able to control and manipulate thoughts"},
	{"Have the power to change one event in history", "Have the power to predict one event in the future"},
	{"Always have the perfect sense of direction", "Always have the perfect memory recall"},
	{"Live in a world with unlimited resources and no scarcity", "Live in a world with advanced mind-reading technology"},
	{"Be able to control gravity", "Be able to control magnetism"},
	{"Have the power to instantly learn any martial art", "Have the power to instantly learn any scientific field"},
	{"Always be able to see 10 minutes into the future", "Always be able to see 100 years into the future"},
	{"Live in a world with talking animals", "Live in a world with advanced robots"},
	{"Have the ability to speak every human language", "Have the ability to communicate with animals"},
	{"Be able to change the past", "Be able to see into parallel universes"},
	{"Have the power to control and manipulate fire", "Have the power to control and manipulate ice"},
	{"Live in a world where everyone can read minds", "Live in a world where everyone can fly"},
	{"Be a famous explorer of uncharted lands", "Be a famous inventor of groundbreaking technology"},
	{"Always be able to find your way home", "Always be able to find your way to hidden treasures"},
	{"Have the power to instantly understand any complex concept", "Have the power to instantly heal any physical injury"},
	{"Live in a world with magical creatures as companions", "Live in a world with advanced AI companions"},
	{"Be able to control and manipulate dreams", "Be able to control and manipulate emotions"},
	{"Always know the answer to any question", "Always know the solution to any problem"},
	{"Have the power to bring fictional characters to life", "Have the power to bring historical figures to the present"},
	{"Live in a world with time manipulation technology", "Live in a world with advanced biotechnology"},
	{"Be a famous musician", "Be a famous actor"},
	{"Always have the ability to heal any illness", "Always have the ability to end any conflict peacefully"},
	{"Have the power to control the weather", "Have the power to control natural disasters"},
	{"Live in a world where wishes come true", "Live in a world where dreams become reality"},
	{"Be able to communicate with extraterrestrial beings", "Be able to communicate with spirits and ghosts"},
	{"Always have the ability to bring joy to others", "Always have the ability to inspire positive change"},
	{"Have the power to eliminate all pollution", "Have the power to eliminate all poverty"},
	{"Live in a world where everyone is always honest", "Live in a world where everyone is always kind"},
	{"Be a famous artist", "Be a famous scientist"},
	{"Always have the ability to avoid dangerous situations", "Always have the ability to predict future events"},
	{"Have the power to control and manipulate thoughts", "Have the power to control and manipulate matter"},
	{"Live in a world with talking plants", "Live in a world with highly advanced AI servants"},
	{"Be able to instantly learn any skill", "Be able to instantly erase any painful memory"},
	{"Always have perfect health", "Always have perfect wealth"},
	{"Have the power to prevent any disaster from occurring", "Have the power to bring about global harmony"},
	{"Live in a world with time loops and alternate realities", "Live in a world with advanced virtual reality"},
	{"Be able to change your physical appearance at will", "Be able to change your personality traits at will"},
	{"Always have the perfect timing in every situation", "Always have the perfect charisma in every situation"},
	{"Have the power to create unlimited clean energy", "Have the power to cure all mental illnesses"},
	{"Live in a world where dreams can be shared", "Live in a world where memories can be transferred"},
	{"Be able to control your emotions at will", "Be able to control the emotions of others"},
	{"Always know when someone is lying to you", "Always know when danger is approaching"},
	{"Have the power to restore any damaged ecosystem", "Have the power to restore lost historical artifacts"},
	{"Live in a world with mythical creatures as pets", "Live in a world with advanced cybernetic companions"},
	{"Be able to manipulate probability", "Be able to manipulate energy"},
	{"Always have the ability to find hidden passages", "Always have the ability to win any argument"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to make anyone instantly calm"},
	{"Live in a world where animals can communicate", "Live in a world where objects have personalities"},
	{"Be able to communicate with your past self", "Be able to communicate with your future self"},
	{"Always have the ability to find beauty in everything", "Always have the ability to find solutions to problems"},
	{"Have the power to end all conflicts with a single gesture", "Have the power to end all suffering with a single word"},
	{"Live in a world where you can visit any place in history", "Live in a world where you can visit any place in the future"},
	{"Be able to control your dreams and have lucid dreams", "Be able to control your thoughts and focus deeply"},
	{"Always have the ability to make people laugh", "Always have the ability to make people feel loved"},
	{"Have the power to instantly learn any form of art", "Have the power to instantly learn any form of science"},
	{"Live in a world with unlimited resources and abundance", "Live in a world with advanced mind-reading technology"},
	{"Be able to control gravity at will", "Be able to control magnetism at will"},
	{"Always have the ability to find the best path forward", "Always have the ability to see the bigger picture"},
	{"Have the power to instantly learn any language", "Have the power to instantly learn any musical instrument"},
	{"Live in a world where everyone has superhuman abilities", "Live in a world where technology is powered by thoughts"},
	{"Be able to change your gender instantly", "Be able to change your age instantly"},
	{"Always know when someone is thinking about you", "Always know when someone is in danger"},
	{"Have the power to erase any painful memory from your mind", "Have the power to restore lost memories"},
	{"Live in a world where everyone is always truthful", "Live in a world where everyone is always compassionate"},
	{"Be a famous explorer of outer space", "Be a famous creator of life-changing inventions"},
	{"Always have the ability to find lost items", "Always have the ability to see the potential in others"},
	{"Have the power to make any object come to life", "Have the power to heal any emotional pain"},
	{"Live in a world with time manipulation abilities", "Live in a world with advanced genetic enhancements"},
	{"Be able to control your body temperature with your mind", "Be able to control your luck with your thoughts"},
	{"Always have the ability to resolve conflicts with ease", "Always have the ability to bring about positive change"},
	{"Have the power to control and manipulate emotions", "Have the power to control and manipulate dreams"},
	{"Live in a world where you can explore the multiverse", "Live in a world where you can shape reality itself"},
	{"Be able to instantly understand any intricate concept", "Be able to instantly heal any emotional wound"},
	{"Always have the ability to find common ground between people", "Always have the ability to inspire hope"},
	{"Have the power to bring extinct species back to life", "Have the power to communicate with parallel dimensions"},
	{"Live in a world where happiness is the primary currency", "Live in a world where knowledge is the ultimate power"},
	{"Be able to manipulate the flow of time", "Be able to manipulate the fabric of reality"},
	{"Always have the ability to avoid accidents and danger", "Always have the ability to foresee future events"},
	{"Have the power to eliminate all forms of negativity", "Have the power to bring about global unity"},
	{"Live in a world with unlimited adventures and exploration", "Live in a world with limitless possibilities"},
	{"Be able to instantly learn any skill or discipline", "Be able to instantly heal any physical ailment"},
	{"Always know the right thing to say in any situation", "Always know the right action to take in any circumstance"},
	{"Have the power to control and manipulate nature", "Have the power to control and manipulate technology"},
	{"Live in a world where dreams have a profound impact on reality", "Live in a world where thoughts shape the physical world"},
	{"Be able to communicate with animals and understand their feelings", "Be able to communicate with spirits and communicate with the deceased"},
	{"Always have the ability to bring people together", "Always have the ability to create innovative solutions"},
	{"Have the power to heal any physical ailment with a touch", "Have the power to soothe any emotional pain with a word"},
	{"Live in a world with time loops and infinite possibilities", "Live in a world with limitless knowledge and wisdom"},
	{"Be able to control your own emotions at will", "Be able to influence the emotions of others"},
	{"Always know when someone is being dishonest", "Always know when danger is approaching"},
	{"Have the power to restore balance to any ecosystem", "Have the power to restore forgotten history and knowledge"},
	{"Live in a world with mythical creatures as companions", "Live in a world with advanced AI companions"},
	{"Be able to manipulate probability and shape destiny", "Be able to manipulate energy and alter the physical world"},
	{"Always have the ability to find hidden truths and mysteries", "Always have the ability to bring joy and laughter to any situation"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and inspiration in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the potential of every individual"},
	{"Always be able to speak and understand any language", "Always be able to play any musical instrument flawlessly"},
	{"Live in a world with dragons as companions", "Live in a world with advanced AI robots as companions"},
	{"Have the power to instantly heal any physical injury", "Have the power to instantly heal any emotional pain"},
	{"Be able to change your appearance at will", "Be able to change your location at will"},
	{"Always know the outcome of any decision you make", "Always know the outcome of any decision anyone else makes"},
	{"Have the power to control and manipulate fire", "Have the power to control and manipulate water"},
	{"Live in a world where you can explore the cosmos", "Live in a world where you can explore the depths of the oceans"},
	{"Be able to control your dreams and have lucid dreaming", "Be able to control your thoughts and achieve deep focus"},
	{"Always have the ability to make people laugh", "Always have the ability to make people feel loved and valued"},
	{"Have the power to eliminate all pollution from the planet", "Have the power to eliminate all poverty and inequality"},
	{"Live in a world where everyone has superhuman strength", "Live in a world where everyone has superhuman intelligence"},
	{"Be able to manipulate probability to your advantage", "Be able to manipulate energy to achieve incredible feats"},
	{"Always have the perfect sense of direction", "Always have the perfect memory recall"},
	{"Have the power to instantly learn any form of art", "Have the power to instantly learn any form of science"},
	{"Live in a world where every day is a new adventure", "Live in a world where every day is a day of tranquility"},
	{"Be able to communicate with animals through thoughts", "Be able to communicate with plants through emotions"},
	{"Always know when someone is lying to you", "Always know when someone needs your help"},
	{"Have the power to control and manipulate emotions", "Have the power to control and manipulate dreams"},
	{"Live in a world where you can explore parallel universes", "Live in a world where you can shape reality itself"},
	{"Be able to instantly understand any complex concept", "Be able to instantly heal any emotional wound"},
	{"Always have the ability to find common ground between people", "Always have the ability to inspire hope and positivity"},
	{"Have the power to bring extinct species back to life", "Have the power to communicate with extraterrestrial beings"},
	{"Live in a world where happiness and love are abundant", "Live in a world where knowledge and wisdom are abundant"},
	{"Be able to manipulate time and relive any moment", "Be able to manipulate matter and create anything"},
	{"Always have the ability to foresee future events", "Always have the ability to shape the course of history"},
	{"Have the power to restore any damaged ecosystem", "Have the power to restore forgotten historical artifacts"},
	{"Live in a world with talking animals and sentient plants", "Live in a world with highly advanced virtual companions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Have the power to make anyone instantly fall in love with you", "Have the power to erase any painful memory from your mind"},
	{"Live in a world where animals and plants can communicate with humans", "Live in a world where objects have personalities and emotions"},
	{"Be able to communicate with your past and future selves", "Be able to communicate with beings from other dimensions"},
	{"Always have the ability to find beauty and meaning in everything", "Always have the ability to find solutions and resolutions"},
	{"Have the power to end all conflicts and suffering with a single word", "Have the power to unlock the full potential of every individual"},
	{"Live in a world where dreams and thoughts shape reality", "Live in a world where actions and intentions shape reality"},
	{"Be able to control your own emotions and achieve inner peace", "Be able to influence the emotions of others and spread harmony"},
	{"Always know the right words to say to bring comfort and joy", "Always know the right actions to take to bring about positive change"},
	{"Be a Duck", "Be a Robot"},
	{"Be a Wolf", "Be a Duck"},
	{"Have a mullet", "Be bald"},
	{"Program only Rust", "Not program at all"},
	{"Wear a tuxedo t-shirt every day for a month", "Wear a tutu every day for a month"},
	{"Hit every red light for the rest of your life", "Have slow internet after the sun goes down"},
	{"Give up social media", "Eat the same dinner for the rest of your life"},
	{"Be forced to sing along to every song you hear", "Be forced to dance to every song you hear"},
	{"Live in the Matrix", "Live in Jumanji"},
	{"Buy 10 things you don't need every time you go shopping", "Always forget the one thing that you need when you go to the store"},
	{"Work an overtime shift with an annoying coworker", "Spend a whole day with your mother-in-law"},
	{"Always be 10 minutes late", "Always be 20 minutes early"},
}
