package timezonecompanion

var CCToZones = map[string][]string{
	"BL": []string{"America/St_Barthelemy"},
	"LR": []string{"Africa/Monrovia"},
	"LY": []string{"Africa/Tripoli"},
	"QA": []string{"Asia/Qatar"},
	"SJ": []string{"Arctic/Longyearbyen"},
	"CY": []string{"Asia/Nicosia", "Asia/Famagusta"},
	"ME": []string{"Europe/Podgorica"},
	"TJ": []string{"Asia/Dushanbe"},
	"UZ": []string{"Asia/Samarkand", "Asia/Tashkent"},
	"AD": []string{"Europe/Andorra"},
	"AR": []string{"America/Argentina/Buenos_Aires", "America/Argentina/Cordoba", "America/Argentina/Salta", "America/Argentina/Jujuy", "America/Argentina/Tucuman", "America/Argentina/Catamarca", "America/Argentina/La_Rioja", "America/Argentina/San_Juan", "America/Argentina/Mendoza", "America/Argentina/San_Luis", "America/Argentina/Rio_Gallegos", "America/Argentina/Ushuaia"},
	"CN": []string{"Asia/Shanghai", "Asia/Urumqi"},
	"FI": []string{"Europe/Helsinki"},
	"MT": []string{"Europe/Malta"},
	"PY": []string{"America/Asuncion"},
	"BE": []string{"Europe/Brussels"},
	"LA": []string{"Asia/Vientiane"},
	"MR": []string{"Africa/Nouakchott"},
	"TF": []string{"Indian/Kerguelen"},
	"UA": []string{"Europe/Kiev", "Europe/Uzhgorod", "Europe/Zaporozhye"},
	"DO": []string{"America/Santo_Domingo"},
	"WS": []string{"Pacific/Apia"},
	"CA": []string{"America/St_Johns", "America/Halifax", "America/Glace_Bay", "America/Moncton", "America/Goose_Bay", "America/Blanc-Sablon", "America/Toronto", "America/Nipigon", "America/Thunder_Bay", "America/Iqaluit", "America/Pangnirtung", "America/Atikokan", "America/Winnipeg", "America/Rainy_River", "America/Resolute", "America/Rankin_Inlet", "America/Regina", "America/Swift_Current", "America/Edmonton", "America/Cambridge_Bay", "America/Yellowknife", "America/Inuvik", "America/Creston", "America/Dawson_Creek", "America/Fort_Nelson", "America/Vancouver", "America/Whitehorse", "America/Dawson"},
	"IS": []string{"Atlantic/Reykjavik"},
	"KH": []string{"Asia/Phnom_Penh"},
	"LK": []string{"Asia/Colombo"},
	"SR": []string{"America/Paramaribo"},
	"SX": []string{"America/Lower_Princes"},
	"AZ": []string{"Asia/Baku"},
	"PW": []string{"Pacific/Palau"},
	"TM": []string{"Asia/Ashgabat"},
	"VE": []string{"America/Caracas"},
	"PK": []string{"Asia/Karachi"},
	"SE": []string{"Europe/Stockholm"},
	"AT": []string{"Europe/Vienna"},
	"GL": []string{"America/Godthab", "America/Danmarkshavn", "America/Scoresbysund", "America/Thule"},
	"KR": []string{"Asia/Seoul"},
	"NG": []string{"Africa/Lagos"},
	"NU": []string{"Pacific/Niue"},
	"OM": []string{"Asia/Muscat"},
	"GP": []string{"America/Guadeloupe"},
	"MD": []string{"Europe/Chisinau"},
	"VA": []string{"Europe/Vatican"},
	"UK": []string{"Europe/London"},
	"BY": []string{"Europe/Minsk"},
	"IR": []string{"Asia/Tehran"},
	"LB": []string{"Asia/Beirut"},
	"MF": []string{"America/Marigot"},
	"ST": []string{"Africa/Sao_Tome"},
	"AU": []string{"Australia/Lord_Howe", "Antarctica/Macquarie", "Australia/Hobart", "Australia/Currie", "Australia/Melbourne", "Australia/Sydney", "Australia/Broken_Hill", "Australia/Brisbane", "Australia/Lindeman", "Australia/Adelaide", "Australia/Darwin", "Australia/Perth", "Australia/Eucla"},
	"SH": []string{"Atlantic/St_Helena"},
	"CC": []string{"Indian/Cocos"},
	"MX": []string{"America/Mexico_City", "America/Cancun", "America/Merida", "America/Monterrey", "America/Matamoros", "America/Mazatlan", "America/Chihuahua", "America/Ojinaga", "America/Hermosillo", "America/Tijuana", "America/Bahia_Banderas"},
	"TR": []string{"Europe/Istanbul"},
	"KW": []string{"Asia/Kuwait"},
	"TO": []string{"Pacific/Tongatapu"},
	"VN": []string{"Asia/Ho_Chi_Minh"},
	"BM": []string{"Atlantic/Bermuda"},
	"BR": []string{"America/Noronha", "America/Belem", "America/Fortaleza", "America/Recife", "America/Araguaina", "America/Maceio", "America/Bahia", "America/Sao_Paulo", "America/Campo_Grande", "America/Cuiaba", "America/Santarem", "America/Porto_Velho", "America/Boa_Vista", "America/Manaus", "America/Eirunepe", "America/Rio_Branco"},
	"ES": []string{"Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"},
	"MA": []string{"Africa/Casablanca"},
	"LS": []string{"Africa/Maseru"},
	"MS": []string{"America/Montserrat"},
	"MW": []string{"Africa/Blantyre"},
	"MZ": []string{"Africa/Maputo"},
	"PF": []string{"Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"},
	"BI": []string{"Africa/Bujumbura"},
	"PS": []string{"Asia/Gaza", "Asia/Hebron"},
	"TT": []string{"America/Port_of_Spain"},
	"BD": []string{"Asia/Dhaka"},
	"CX": []string{"Indian/Christmas"},
	"CZ": []string{"Europe/Prague"},
	"ML": []string{"Africa/Bamako"},
	"BO": []string{"America/La_Paz"},
	"GS": []string{"Atlantic/South_Georgia"},
	"MG": []string{"Indian/Antananarivo"},
	"MQ": []string{"America/Martinique"},
	"VI": []string{"America/St_Thomas"},
	"BT": []string{"Asia/Thimphu"},
	"CF": []string{"Africa/Bangui"},
	"IN": []string{"Asia/Kolkata"},
	"KE": []string{"Africa/Nairobi"},
	"TN": []string{"Africa/Tunis"},
	"SV": []string{"America/El_Salvador"},
	"LC": []string{"America/St_Lucia"},
	"LU": []string{"Europe/Luxembourg"},
	"RU": []string{"Europe/Kaliningrad", "Europe/Moscow", "Europe/Simferopol", "Europe/Kirov", "Europe/Astrakhan", "Europe/Volgograd", "Europe/Saratov", "Europe/Ulyanovsk", "Europe/Samara", "Asia/Yekaterinburg", "Asia/Omsk", "Asia/Novosibirsk", "Asia/Barnaul", "Asia/Tomsk", "Asia/Novokuznetsk", "Asia/Krasnoyarsk", "Asia/Irkutsk", "Asia/Chita", "Asia/Yakutsk", "Asia/Khandyga", "Asia/Vladivostok", "Asia/Ust-Nera", "Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Kamchatka", "Asia/Anadyr"},
	"SZ": []string{"Africa/Mbabane"},
	"BS": []string{"America/Nassau"},
	"CG": []string{"Africa/Brazzaville"},
	"GY": []string{"America/Guyana"},
	"IO": []string{"Indian/Chagos"},
	"NP": []string{"Asia/Kathmandu"},
	"PM": []string{"America/Miquelon"},
	"KN": []string{"America/St_Kitts"},
	"SY": []string{"Asia/Damascus"},
	"KZ": []string{"Asia/Almaty", "Asia/Qyzylorda", "Asia/Qostanay", "Asia/Aqtobe", "Asia/Aqtau", "Asia/Atyrau", "Asia/Oral"},
	"EG": []string{"Africa/Cairo"},
	"SI": []string{"Europe/Ljubljana"},
	"BZ": []string{"America/Belize"},
	"MY": []string{"Asia/Kuala_Lumpur", "Asia/Kuching"},
	"SS": []string{"Africa/Juba"},
	"CW": []string{"America/Curacao"},
	"FR": []string{"Europe/Paris"},
	"NR": []string{"Pacific/Nauru"},
	"CU": []string{"America/Havana"},
	"MC": []string{"Europe/Monaco"},
	"GQ": []string{"Africa/Malabo"},
	"LT": []string{"Europe/Vilnius"},
	"VC": []string{"America/St_Vincent"},
	"EC": []string{"America/Guayaquil", "Pacific/Galapagos"},
	"MO": []string{"Asia/Macau"},
	"US": []string{"America/New_York", "America/Detroit", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Indiana/Indianapolis", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Vevay", "America/Chicago", "America/Indiana/Tell_City", "America/Indiana/Knox", "America/Menominee", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/North_Dakota/Beulah", "America/Denver", "America/Boise", "America/Phoenix", "America/Los_Angeles", "America/Anchorage", "America/Juneau", "America/Sitka", "America/Metlakatla", "America/Yakutat", "America/Nome", "America/Adak", "Pacific/Honolulu"},
	"FM": []string{"Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"},
	"GF": []string{"America/Cayenne"},
	"IL": []string{"Asia/Jerusalem"},
	"RO": []string{"Europe/Bucharest"},
	"DM": []string{"America/Dominica"},
	"KI": []string{"Pacific/Tarawa", "Pacific/Enderbury", "Pacific/Kiritimati"},
	"MV": []string{"Indian/Maldives"},
	"RW": []string{"Africa/Kigali"},
	"WF": []string{"Pacific/Wallis"},
	"NL": []string{"Europe/Amsterdam"},
	"UY": []string{"America/Montevideo"},
	"BQ": []string{"America/Kralendijk"},
	"CI": []string{"Africa/Abidjan"},
	"CK": []string{"Pacific/Rarotonga"},
	"HT": []string{"America/Port-au-Prince"},
	"ID": []string{"Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"},
	"IE": []string{"Europe/Dublin"},
	"AG": []string{"America/Antigua"},
	"AO": []string{"Africa/Luanda"},
	"GN": []string{"Africa/Conakry"},
	"GR": []string{"Europe/Athens"},
	"ZA": []string{"Africa/Johannesburg"},
	"AI": []string{"America/Anguilla"},
	"PA": []string{"America/Panama"},
	"PR": []string{"America/Puerto_Rico"},
	"TZ": []string{"Africa/Dar_es_Salaam"},
	"CO": []string{"America/Bogota"},
	"GG": []string{"Europe/Guernsey"},
	"KG": []string{"Asia/Bishkek"},
	"UM": []string{"Pacific/Midway", "Pacific/Wake"},
	"ZW": []string{"Africa/Harare"},
	"SN": []string{"Africa/Dakar"},
	"TC": []string{"America/Grand_Turk"},
	"AE": []string{"Asia/Dubai"},
	"FJ": []string{"Pacific/Fiji"},
	"GD": []string{"America/Grenada"},
	"GH": []string{"Africa/Accra"},
	"GI": []string{"Europe/Gibraltar"},
	"SL": []string{"Africa/Freetown"},
	"SC": []string{"Indian/Mahe"},
	"FK": []string{"Atlantic/Stanley"},
	"KY": []string{"America/Cayman"},
	"RS": []string{"Europe/Belgrade"},
	"GE": []string{"Asia/Tbilisi"},
	"YE": []string{"Asia/Aden"},
	"AS": []string{"Pacific/Pago_Pago"},
	"MK": []string{"Europe/Skopje"},
	"PG": []string{"Pacific/Port_Moresby", "Pacific/Bougainville"},
	"EE": []string{"Europe/Tallinn"},
	"NI": []string{"America/Managua"},
	"SA": []string{"Asia/Riyadh"},
	"BJ": []string{"Africa/Porto-Novo"},
	"LV": []string{"Europe/Riga"},
	"NE": []string{"Africa/Niamey"},
	"SD": []string{"Africa/Khartoum"},
	"YT": []string{"Indian/Mayotte"},
	"AW": []string{"America/Aruba"},
	"PH": []string{"Asia/Manila"},
	"PN": []string{"Pacific/Pitcairn"},
	"TG": []string{"Africa/Lome"},
	"CL": []string{"America/Santiago", "America/Punta_Arenas", "Pacific/Easter"},
	"GT": []string{"America/Guatemala"},
	"NA": []string{"Africa/Windhoek"},
	"SO": []string{"Africa/Mogadishu"},
	"TL": []string{"Asia/Dili"},
	"DZ": []string{"Africa/Algiers"},
	"LI": []string{"Europe/Vaduz"},
	"MH": []string{"Pacific/Majuro", "Pacific/Kwajalein"},
	"NZ": []string{"Pacific/Auckland", "Pacific/Chatham"},
	"SB": []string{"Pacific/Guadalcanal"},
	"SM": []string{"Europe/San_Marino"},
	"VG": []string{"America/Tortola"},
	"CD": []string{"Africa/Kinshasa", "Africa/Lubumbashi"},
	"BN": []string{"Asia/Brunei"},
	"AQ": []string{"Antarctica/McMurdo", "Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok"},
	"CM": []string{"Africa/Douala"},
	"JE": []string{"Europe/Jersey"},
	"JP": []string{"Asia/Tokyo"},
	"SK": []string{"Europe/Bratislava"},
	"TK": []string{"Pacific/Fakaofo"},
	"CH": []string{"Europe/Zurich"},
	"GA": []string{"Africa/Libreville"},
	"CR": []string{"America/Costa_Rica"},
	"HR": []string{"Europe/Zagreb"},
	"IM": []string{"Europe/Isle_of_Man"},
	"BG": []string{"Europe/Sofia"},
	"NF": []string{"Pacific/Norfolk"},
	"BA": []string{"Europe/Sarajevo"},
	"CV": []string{"Atlantic/Cape_Verde"},
	"JO": []string{"Asia/Amman"},
	"GU": []string{"Pacific/Guam"},
	"HU": []string{"Europe/Budapest"},
	"JM": []string{"America/Jamaica"},
	"BF": []string{"Africa/Ouagadougou"},
	"MN": []string{"Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"},
	"TV": []string{"Pacific/Funafuti"},
	"BB": []string{"America/Barbados"},
	"ER": []string{"Africa/Asmara"},
	"IT": []string{"Europe/Rome"},
	"KM": []string{"Indian/Comoro"},
	"MP": []string{"Pacific/Saipan"},
	"PT": []string{"Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"},
	"ZM": []string{"Africa/Lusaka"},
	"EH": []string{"Africa/El_Aaiun"},
	"GM": []string{"Africa/Banjul"},
	"KP": []string{"Asia/Pyongyang"},
	"NC": []string{"Pacific/Noumea"},
	"RE": []string{"Indian/Reunion"},
	"SG": []string{"Asia/Singapore"},
	"TD": []string{"Africa/Ndjamena"},
	"TW": []string{"Asia/Taipei"},
	"AF": []string{"Asia/Kabul"},
	"DE": []string{"Europe/Berlin", "Europe/Busingen"},
	"ET": []string{"Africa/Addis_Ababa"},
	"GB": []string{"Europe/London"},
	"HK": []string{"Asia/Hong_Kong"},
	"HN": []string{"America/Tegucigalpa"},
	"AM": []string{"Asia/Yerevan"},
	"BH": []string{"Asia/Bahrain"},
	"GW": []string{"Africa/Bissau"},
	"MU": []string{"Indian/Mauritius"},
	"NO": []string{"Europe/Oslo"},
	"PE": []string{"America/Lima"},
	"BW": []string{"Africa/Gaborone"},
	"DJ": []string{"Africa/Djibouti"},
	"IQ": []string{"Asia/Baghdad"},
	"MM": []string{"Asia/Yangon"},
	"DK": []string{"Europe/Copenhagen"},
	"FO": []string{"Atlantic/Faroe"},
	"PL": []string{"Europe/Warsaw"},
	"TH": []string{"Asia/Bangkok"},
	"UG": []string{"Africa/Kampala"},
	"AL": []string{"Europe/Tirane"},
	"AX": []string{"Europe/Mariehamn"},
	"VU": []string{"Pacific/Efate"},
}
