package timezonecompanion

var CCToZones = map[string][]string{
	"BL": {"America/St_Barthelemy"},
	"LR": {"Africa/Monrovia"},
	"LY": {"Africa/Tripoli"},
	"QA": {"Asia/Qatar"},
	"SJ": {"Arctic/Longyearbyen"},
	"CY": {"Asia/Nicosia", "Asia/Famagusta"},
	"ME": {"Europe/Podgorica"},
	"TJ": {"Asia/Dushanbe"},
	"UZ": {"Asia/Samarkand", "Asia/Tashkent"},
	"AD": {"Europe/Andorra"},
	"AR": {"America/Argentina/Buenos_Aires", "America/Argentina/Cordoba", "America/Argentina/Salta", "America/Argentina/Jujuy", "America/Argentina/Tucuman", "America/Argentina/Catamarca", "America/Argentina/La_Rioja", "America/Argentina/San_Juan", "America/Argentina/Mendoza", "America/Argentina/San_Luis", "America/Argentina/Rio_Gallegos", "America/Argentina/Ushuaia"},
	"CN": {"Asia/Shanghai", "Asia/Urumqi"},
	"FI": {"Europe/Helsinki"},
	"MT": {"Europe/Malta"},
	"PY": {"America/Asuncion"},
	"BE": {"Europe/Brussels"},
	"LA": {"Asia/Vientiane"},
	"MR": {"Africa/Nouakchott"},
	"TF": {"Indian/Kerguelen"},
	"UA": {"Europe/Kiev", "Europe/Uzhgorod", "Europe/Zaporozhye"},
	"DO": {"America/Santo_Domingo"},
	"WS": {"Pacific/Apia"},
	"CA": {"America/St_Johns", "America/Halifax", "America/Glace_Bay", "America/Moncton", "America/Goose_Bay", "America/Blanc-Sablon", "America/Toronto", "America/Nipigon", "America/Thunder_Bay", "America/Iqaluit", "America/Pangnirtung", "America/Atikokan", "America/Winnipeg", "America/Rainy_River", "America/Resolute", "America/Rankin_Inlet", "America/Regina", "America/Swift_Current", "America/Edmonton", "America/Cambridge_Bay", "America/Yellowknife", "America/Inuvik", "America/Creston", "America/Dawson_Creek", "America/Fort_Nelson", "America/Vancouver", "America/Whitehorse", "America/Dawson"},
	"IS": {"Atlantic/Reykjavik"},
	"KH": {"Asia/Phnom_Penh"},
	"LK": {"Asia/Colombo"},
	"SR": {"America/Paramaribo"},
	"SX": {"America/Lower_Princes"},
	"AZ": {"Asia/Baku"},
	"PW": {"Pacific/Palau"},
	"TM": {"Asia/Ashgabat"},
	"VE": {"America/Caracas"},
	"PK": {"Asia/Karachi"},
	"SE": {"Europe/Stockholm"},
	"AT": {"Europe/Vienna"},
	"GL": {"America/Godthab", "America/Danmarkshavn", "America/Scoresbysund", "America/Thule"},
	"KR": {"Asia/Seoul"},
	"NG": {"Africa/Lagos"},
	"NU": {"Pacific/Niue"},
	"OM": {"Asia/Muscat"},
	"GP": {"America/Guadeloupe"},
	"MD": {"Europe/Chisinau"},
	"VA": {"Europe/Vatican"},
	"UK": {"Europe/London"},
	"BY": {"Europe/Minsk"},
	"IR": {"Asia/Tehran"},
	"LB": {"Asia/Beirut"},
	"MF": {"America/Marigot"},
	"ST": {"Africa/Sao_Tome"},
	"AU": {"Australia/Lord_Howe", "Antarctica/Macquarie", "Australia/Hobart", "Australia/Currie", "Australia/Melbourne", "Australia/Sydney", "Australia/Broken_Hill", "Australia/Brisbane", "Australia/Lindeman", "Australia/Adelaide", "Australia/Darwin", "Australia/Perth", "Australia/Eucla"},
	"SH": {"Atlantic/St_Helena"},
	"CC": {"Indian/Cocos"},
	"MX": {"America/Mexico_City", "America/Cancun", "America/Merida", "America/Monterrey", "America/Matamoros", "America/Mazatlan", "America/Chihuahua", "America/Ojinaga", "America/Hermosillo", "America/Tijuana", "America/Bahia_Banderas"},
	"TR": {"Europe/Istanbul"},
	"KW": {"Asia/Kuwait"},
	"TO": {"Pacific/Tongatapu"},
	"VN": {"Asia/Ho_Chi_Minh"},
	"BM": {"Atlantic/Bermuda"},
	"BR": {"America/Noronha", "America/Belem", "America/Fortaleza", "America/Recife", "America/Araguaina", "America/Maceio", "America/Bahia", "America/Sao_Paulo", "America/Campo_Grande", "America/Cuiaba", "America/Santarem", "America/Porto_Velho", "America/Boa_Vista", "America/Manaus", "America/Eirunepe", "America/Rio_Branco"},
	"ES": {"Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"},
	"MA": {"Africa/Casablanca"},
	"LS": {"Africa/Maseru"},
	"MS": {"America/Montserrat"},
	"MW": {"Africa/Blantyre"},
	"MZ": {"Africa/Maputo"},
	"PF": {"Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"},
	"BI": {"Africa/Bujumbura"},
	"PS": {"Asia/Gaza", "Asia/Hebron"},
	"TT": {"America/Port_of_Spain"},
	"BD": {"Asia/Dhaka"},
	"CX": {"Indian/Christmas"},
	"CZ": {"Europe/Prague"},
	"ML": {"Africa/Bamako"},
	"BO": {"America/La_Paz"},
	"GS": {"Atlantic/South_Georgia"},
	"MG": {"Indian/Antananarivo"},
	"MQ": {"America/Martinique"},
	"VI": {"America/St_Thomas"},
	"BT": {"Asia/Thimphu"},
	"CF": {"Africa/Bangui"},
	"IN": {"Asia/Kolkata"},
	"KE": {"Africa/Nairobi"},
	"TN": {"Africa/Tunis"},
	"SV": {"America/El_Salvador"},
	"LC": {"America/St_Lucia"},
	"LU": {"Europe/Luxembourg"},
	"RU": {"Europe/Kaliningrad", "Europe/Moscow", "Europe/Simferopol", "Europe/Kirov", "Europe/Astrakhan", "Europe/Volgograd", "Europe/Saratov", "Europe/Ulyanovsk", "Europe/Samara", "Asia/Yekaterinburg", "Asia/Omsk", "Asia/Novosibirsk", "Asia/Barnaul", "Asia/Tomsk", "Asia/Novokuznetsk", "Asia/Krasnoyarsk", "Asia/Irkutsk", "Asia/Chita", "Asia/Yakutsk", "Asia/Khandyga", "Asia/Vladivostok", "Asia/Ust-Nera", "Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Kamchatka", "Asia/Anadyr"},
	"SZ": {"Africa/Mbabane"},
	"BS": {"America/Nassau"},
	"CG": {"Africa/Brazzaville"},
	"GY": {"America/Guyana"},
	"IO": {"Indian/Chagos"},
	"NP": {"Asia/Kathmandu"},
	"PM": {"America/Miquelon"},
	"KN": {"America/St_Kitts"},
	"SY": {"Asia/Damascus"},
	"KZ": {"Asia/Almaty", "Asia/Qyzylorda", "Asia/Qostanay", "Asia/Aqtobe", "Asia/Aqtau", "Asia/Atyrau", "Asia/Oral"},
	"EG": {"Africa/Cairo"},
	"SI": {"Europe/Ljubljana"},
	"BZ": {"America/Belize"},
	"MY": {"Asia/Kuala_Lumpur", "Asia/Kuching"},
	"SS": {"Africa/Juba"},
	"CW": {"America/Curacao"},
	"FR": {"Europe/Paris"},
	"NR": {"Pacific/Nauru"},
	"CU": {"America/Havana"},
	"MC": {"Europe/Monaco"},
	"GQ": {"Africa/Malabo"},
	"LT": {"Europe/Vilnius"},
	"VC": {"America/St_Vincent"},
	"EC": {"America/Guayaquil", "Pacific/Galapagos"},
	"MO": {"Asia/Macau"},
	"US": {"America/New_York", "America/Detroit", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Indiana/Indianapolis", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Vevay", "America/Chicago", "America/Indiana/Tell_City", "America/Indiana/Knox", "America/Menominee", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/North_Dakota/Beulah", "America/Denver", "America/Boise", "America/Phoenix", "America/Los_Angeles", "America/Anchorage", "America/Juneau", "America/Sitka", "America/Metlakatla", "America/Yakutat", "America/Nome", "America/Adak", "Pacific/Honolulu"},
	"FM": {"Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"},
	"GF": {"America/Cayenne"},
	"IL": {"Asia/Jerusalem"},
	"RO": {"Europe/Bucharest"},
	"DM": {"America/Dominica"},
	"KI": {"Pacific/Tarawa", "Pacific/Enderbury", "Pacific/Kiritimati"},
	"MV": {"Indian/Maldives"},
	"RW": {"Africa/Kigali"},
	"WF": {"Pacific/Wallis"},
	"NL": {"Europe/Amsterdam"},
	"UY": {"America/Montevideo"},
	"BQ": {"America/Kralendijk"},
	"CI": {"Africa/Abidjan"},
	"CK": {"Pacific/Rarotonga"},
	"HT": {"America/Port-au-Prince"},
	"ID": {"Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"},
	"IE": {"Europe/Dublin"},
	"AG": {"America/Antigua"},
	"AO": {"Africa/Luanda"},
	"GN": {"Africa/Conakry"},
	"GR": {"Europe/Athens"},
	"ZA": {"Africa/Johannesburg"},
	"AI": {"America/Anguilla"},
	"PA": {"America/Panama"},
	"PR": {"America/Puerto_Rico"},
	"TZ": {"Africa/Dar_es_Salaam"},
	"CO": {"America/Bogota"},
	"GG": {"Europe/Guernsey"},
	"KG": {"Asia/Bishkek"},
	"UM": {"Pacific/Midway", "Pacific/Wake"},
	"ZW": {"Africa/Harare"},
	"SN": {"Africa/Dakar"},
	"TC": {"America/Grand_Turk"},
	"AE": {"Asia/Dubai"},
	"FJ": {"Pacific/Fiji"},
	"GD": {"America/Grenada"},
	"GH": {"Africa/Accra"},
	"GI": {"Europe/Gibraltar"},
	"SL": {"Africa/Freetown"},
	"SC": {"Indian/Mahe"},
	"FK": {"Atlantic/Stanley"},
	"KY": {"America/Cayman"},
	"RS": {"Europe/Belgrade"},
	"GE": {"Asia/Tbilisi"},
	"YE": {"Asia/Aden"},
	"AS": {"Pacific/Pago_Pago"},
	"MK": {"Europe/Skopje"},
	"PG": {"Pacific/Port_Moresby", "Pacific/Bougainville"},
	"EE": {"Europe/Tallinn"},
	"NI": {"America/Managua"},
	"SA": {"Asia/Riyadh"},
	"BJ": {"Africa/Porto-Novo"},
	"LV": {"Europe/Riga"},
	"NE": {"Africa/Niamey"},
	"SD": {"Africa/Khartoum"},
	"YT": {"Indian/Mayotte"},
	"AW": {"America/Aruba"},
	"PH": {"Asia/Manila"},
	"PN": {"Pacific/Pitcairn"},
	"TG": {"Africa/Lome"},
	"CL": {"America/Santiago", "America/Punta_Arenas", "Pacific/Easter"},
	"GT": {"America/Guatemala"},
	"NA": {"Africa/Windhoek"},
	"SO": {"Africa/Mogadishu"},
	"TL": {"Asia/Dili"},
	"DZ": {"Africa/Algiers"},
	"LI": {"Europe/Vaduz"},
	"MH": {"Pacific/Majuro", "Pacific/Kwajalein"},
	"NZ": {"Pacific/Auckland", "Pacific/Chatham"},
	"SB": {"Pacific/Guadalcanal"},
	"SM": {"Europe/San_Marino"},
	"VG": {"America/Tortola"},
	"CD": {"Africa/Kinshasa", "Africa/Lubumbashi"},
	"BN": {"Asia/Brunei"},
	"AQ": {"Antarctica/McMurdo", "Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok"},
	"CM": {"Africa/Douala"},
	"JE": {"Europe/Jersey"},
	"JP": {"Asia/Tokyo"},
	"SK": {"Europe/Bratislava"},
	"TK": {"Pacific/Fakaofo"},
	"CH": {"Europe/Zurich"},
	"GA": {"Africa/Libreville"},
	"CR": {"America/Costa_Rica"},
	"HR": {"Europe/Zagreb"},
	"IM": {"Europe/Isle_of_Man"},
	"BG": {"Europe/Sofia"},
	"NF": {"Pacific/Norfolk"},
	"BA": {"Europe/Sarajevo"},
	"CV": {"Atlantic/Cape_Verde"},
	"JO": {"Asia/Amman"},
	"GU": {"Pacific/Guam"},
	"HU": {"Europe/Budapest"},
	"JM": {"America/Jamaica"},
	"BF": {"Africa/Ouagadougou"},
	"MN": {"Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"},
	"TV": {"Pacific/Funafuti"},
	"BB": {"America/Barbados"},
	"ER": {"Africa/Asmara"},
	"IT": {"Europe/Rome"},
	"KM": {"Indian/Comoro"},
	"MP": {"Pacific/Saipan"},
	"PT": {"Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"},
	"ZM": {"Africa/Lusaka"},
	"EH": {"Africa/El_Aaiun"},
	"GM": {"Africa/Banjul"},
	"KP": {"Asia/Pyongyang"},
	"NC": {"Pacific/Noumea"},
	"RE": {"Indian/Reunion"},
	"SG": {"Asia/Singapore"},
	"TD": {"Africa/Ndjamena"},
	"TW": {"Asia/Taipei"},
	"AF": {"Asia/Kabul"},
	"DE": {"Europe/Berlin", "Europe/Busingen"},
	"ET": {"Africa/Addis_Ababa"},
	"GB": {"Europe/London"},
	"HK": {"Asia/Hong_Kong"},
	"HN": {"America/Tegucigalpa"},
	"AM": {"Asia/Yerevan"},
	"BH": {"Asia/Bahrain"},
	"GW": {"Africa/Bissau"},
	"MU": {"Indian/Mauritius"},
	"NO": {"Europe/Oslo"},
	"PE": {"America/Lima"},
	"BW": {"Africa/Gaborone"},
	"DJ": {"Africa/Djibouti"},
	"IQ": {"Asia/Baghdad"},
	"MM": {"Asia/Yangon"},
	"DK": {"Europe/Copenhagen"},
	"FO": {"Atlantic/Faroe"},
	"PL": {"Europe/Warsaw"},
	"TH": {"Asia/Bangkok"},
	"UG": {"Africa/Kampala"},
	"AL": {"Europe/Tirane"},
	"AX": {"Europe/Mariehamn"},
	"VU": {"Pacific/Efate"},
}
