package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "ai",
		Description: "AI Pack - written by AI",
		Prompts:     []*PromptCard{},
		Responses: []ResponseCard{
			`A freakin' 'nado`,
			`A gerbil named "Her"`,
			`A hole to waste the blood of rich people`,
			`A hot air balloon that never comes down`,
			`A killer’s diet of bush, cucumbers, and feathers`,
			`A man cave filled with scalding hot garbage`,
			`A man who has porn on his hard drive and who masterbates to it`,
			`A radical rethinking of public education`,
			`A redneck arguing with a snow cone`,
			`A sexy hacker named Faith who can read minds`,
			`A treasure chest containing hamster, guinea pig, and porcupine parts`,
			`A woman who is so smart I'm like "whoa"`,
			`A woman who is so smart that she can predict the movements of 300 birds`,
			`Backwards genitals`,
			`Barnacles`,
			`Becoming less and less attractive`,
			`Being man enough to eat raw horse flesh`,
			`Being ready to have sex any time, anywhere, with almost anything`,
			`Big city food`,
			`Big dreams, big balls, and big tits`,
			`Big gay hugs`,
			`Big Jeff's tongue`,
			`Big, powerful poops`,
			`Cheap booze, dirty needles, open containers, and dead livestock`,
			`Cum-smacking my nutsack`,
			`Finding a nipple and being like “Oooh! That’s a nipple!”`,
			`Floating about in a graveyard`,
			`Fucking an elderly yoga instructor named "Scar"`,
			`Garfield penis`,
			`Gary's dad, Gary`,
			`Getting Masturbated to`,
			`Giving birth to a frozen bear on Christmas eve`,
			`Giving grandma crappy things she doesn’t like`,
			`Going apeshit for pounds and pounds of boneless skin`,
			`Ham finger`,
			`Hands down the best eggnog I have ever had`,
			`Having a happy girl poop`,
			`Having a soft spot for uneducated farm boys`,
			`Having Marxist principles but also being incredibly miserly`,
			`Hellacious ooze`,
			`Illegal dentistry`,
			`Insane empanadas`,
			`Intergalactic Congress`,
			`Jizzing a pool of black liquid into your lover's eyes`,
			`Killing, eating, drinking, and otherwise enjoying life`,
			`Kim Kardashian, but with spider legs`,
			`Laughing hysterically while my partner pours coffee into my eyes`,
			`Luigi's presence`,
			`More olives than you could possibly understand`,
			`Mr. Poop`,
			`My disgusting pot-bellied boy`,
			`Napkins`,
			`Not quite getting the gangbusters orgasm you need`,
			`Nothin', bitch`,
			`Our buddy with the bowling balls`,
			`P.F. Chang’s fusion of casual and formal cuisine`,
			`Peeing in the microwave`,
			`Reading an entire book called "how to masturbate" because you're a child`,
			`Screaming “there’s a hawk up my ass!”`,
			`Secret CIA moon prisons`,
			`Shitting on a statue of Christopher Columbus`,
			`Shitty grandpa stories`,
			`Sitting in the back of the plane, smoking a cigar and reading the Flickr privacy policy`,
			`Sitting on Earth's largest couch`,
			`Some dude who has no idea what he's doing, is terrible at sex, and is likely dead`,
			`Some dude who says he's a comedian`,
			`Some kind of mutated shrimp that can suck dick like a pro`,
			`Some sort of alien lobster handjob contest`,
			`Some sort of giant son of a bitch who lives in the internet`,
			`Some sort of unstoppable poo gun`,
			`Stairs`,
			`Straight-up fucking a computer`,
			`Sucking on a vibrator like the crazy person I am`,
			`Sugar. Yes, Sugar.`,
			`That cracker that ain't nothing but a cookie`,
			`That shitty season of Mad Men where Sterling Cooper Draper Pryce gets destroyed by Daenerys Targaryen’s dragons`,
			`That time Dad was diagnosed with terminal brain cancer and died`,
			`The amount of emotions a peanut would be capable of holding`,
			`The amount of fun Doug's having these days`,
			`The amount of pent-up hate and vitriol I can summon up at any given moment`,
			`The glue that holds the sky together`,
			`The idea of a walrus`,
			`The lesbians of Iowa`,
			`The real story behind the yogurt that came out of Tina’s vagina`,
			`The rhinoceros's deeply unnatural laughter`,
			`The unspeakable secrets of the weasels`,
			`These amazing testicles I’m about to share with you`,
			`These awesome gadgets that track my every move`,
			`These ghastly visions that haunt me nightly`,
			`These new jeans that look so cool but are actually so bad`,
			`Thinking about puppies while giving a blowjob`,
			`Thinking things through in a mature, objective way`,
			`Those "military escort services" that ferry young admirals around the wax museum`,
			`Turning on the water feature`,
			`Twenty years of untreated syphilis`,
			`Using real cheese to decorate the base of a penis`,
			`What I Doin’`,
			`When a cute little guy fucks a tough old lady`,
			`Yelling "jizz on it" as you eat an ice cream sandwich`,
		},
	}

	AddPack(pack)
}
