package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "absurdbox",
		Description: "Absurd Box",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `Ain't it nifty? Barb and Bob hit 50! So get off your ass and raise a glass to 50 years of %s.`},
			&PromptCard{Prompt: `Duuuuuuude. You have got to go to space. %s is awesome in space.`},
			&PromptCard{Prompt: `Five, four, three, two, one… %s!`},
			&PromptCard{Prompt: `For hunting in the King's forest, I hereby sentence you to death by %s.`},
			&PromptCard{Prompt: `Give me ten good men and 48 hours. I'll get you %s.`},
			&PromptCard{Prompt: `Goldfinger! / He's the man, / the man with %s.`},
			&PromptCard{Prompt: `Goodbye, %s, hello %s!`},
			&PromptCard{Prompt: `Here's a little something I learned in business school: The customer is always %s.`},
			&PromptCard{Prompt: `Hey, honey. For the bedroom, were you thinking, ""Robin's Egg Blue"" or %sPink?""`},
			&PromptCard{Prompt: `I hate this job. I hate this place. Most of all, I hate %s. I quit.`},
			&PromptCard{Prompt: `I have solved politics. My solution is %s.`},
			&PromptCard{Prompt: `I so drunk I %s.`},
			&PromptCard{Prompt: `I swear to God I'm gonna murder my husband if he doesn't shut the fuck up about %s.`},
			&PromptCard{Prompt: `In bookstores now: "From %s to %s: A memoir."`},
			&PromptCard{Prompt: `In Radiohead's new single, Thom Yorke repeats the phrase "%s" dozens of times over a skittering drum beat.`},
			&PromptCard{Prompt: `It's finally happening! I'm finally doing it! Yes! It's time for %s!`},
			&PromptCard{Prompt: `It's late at night. You're in bed with your lover, Patrick Stewart. He leans over with a twinkle in his eye and asks "How about %s?"`},
			&PromptCard{Prompt: `It's the 21st century. A woman shouldn't have to apologize for %s.`},
			&PromptCard{Prompt: `Ladies and gentlemen, I propose a two-pronged plan. The first prong will be %s, and the second prong will be %s.`},
			&PromptCard{Prompt: `Live from Universal Studios, it's America's favorite game show! "%s or %s?"`},
			&PromptCard{Prompt: `Millions of copies sold! Donald Trump's "The Art of %s."`},
			&PromptCard{Prompt: `New at TGI Fridays! It's what you've been waiting for: The %s Burger.`},
			&PromptCard{Prompt: `Oh no! Here it comes! Ohhhhh god! It's %s.`},
			&PromptCard{Prompt: `Oh you haaaaaaave to see this new documentary on Netflix. I don't want to give anything away, but let's just say it will change the way you look at %s.`},
			&PromptCard{Prompt: `Oh, the weather outside is frightful. But %s is so delightful.`},
			&PromptCard{Prompt: `One, two, three and to the four, Snoop Doggy Dogg and Dr. Dre is %s.`},
			&PromptCard{Prompt: `Personal foul: %s. 15-yard penalty. Automatic first down.`},
			&PromptCard{Prompt: `Rub a dub dub, %s in a tub!`},
			&PromptCard{Prompt: `Say it loud! I'm %s and I'm proud!`},
			&PromptCard{Prompt: `Seriously guys, there's nothing funny about %s.`},
			&PromptCard{Prompt: `Sweetheart, you and your sister escel in different ways. She's got her violin, and you've got %s.`},
			&PromptCard{Prompt: `That's bullshit! They can't fire me for %s!`},
			&PromptCard{Prompt: `The sequel is here! Get Ready for %s2: %s.`},
			&PromptCard{Prompt: `Times have changed, girlfriend. If you want to meet people in New York, you got to be down for %s.`},
			&PromptCard{Prompt: `Unfortunately, no one can be told what %s is. You have to experience it for yourself.`},
			&PromptCard{Prompt: `What has my life become? I'm jerking off to a video called "co-ed absolutely destroyed by %s."`},
			&PromptCard{Prompt: `What sounds great after four margaritas? %s`},
			&PromptCard{Prompt: `What's hot, smelly, and about to die? %s`},
			&PromptCard{Prompt: `What's secretly a Russian plot to destabilize the West? %s`},
			&PromptCard{Prompt: `What's up, YouTube? User DanTheMan wanted to see %s, so here we go.`},
			&PromptCard{Prompt: `Why did the chicken cross the road? %s`},
			&PromptCard{Prompt: `Why my mustache smell so bad? %s`},
			&PromptCard{Prompt: `Yeah that's so hot. I'm so close. Talk about %s again! OH I'M CUMMING!`},
			&PromptCard{Prompt: `You can call me David Copperfield, because I'm about to make %s disappear.`},
			&PromptCard{Prompt: `You city folk would never understand the quiet dignity of %s.`},
		},
		Responses: []ResponseCard{
			`A 12-foot scepter of bone`,
			`A basketball that screams every time it gets bounced`,
			`A bear`,
			`A big hole`,
			`A big hot fire that's burning everybody`,
			`A big, big, big, and I mean BIG big`,
			`A big, sloppy blowjob from a mean, tired cowboy`,
			`A bird that dies`,
			`A bold red lip`,
			`A button that when you press it, there's jazz`,
			`A crab rangoon`,
			`A cat with… hands`,
			`A Christmas feast of goose and jellies`,
			`A concerning amount of white people`,
			`A couple of cold ones`,
			`A family of raccoons`,
			`A four-hour depression nap`,
			`A full-on panic attack`,
			`A garbage clown who makes no one laugh and should die`,
			`A hamburger on a string that keeps getting pulled away`,
			`A hateful 30-year marriage`,
			`A little boy with big dreams and potatoes for hands`,
			`A little girl with a knife`,
			`A little sewer girl strangling a pigeon`,
			`A little taste of penis`,
			`A magician fucking up over and over again`,
			`A penis that gets too hard and explodes blood`,
			`A piping-hot casserole filled with beans and hair`,
			`A poop emergency`,
			`A powerful philosopher named Brainhead`,
			`A Pringle`,
			`A Puerto Rican minotaur from the Bronx`,
			`A racist boomerang that only comes back if you're white`,
			`A real cum-dumpster of a saxophonist`,
			`A real job with insurance and your taxes taken out and everything`,
			`A sticky tree hole full of pancake sauce`,
			`A stinky hoo-ha`,
			`A toothless woman gumming on a peach`,
			`A urinary tract infection`,
			`A vagina that beatboxes when it's horny`,
			`A whole different way of talking called Spanish`,
			`Accusing a powerful man of sexual assault`,
			`Acquiring a gun very easily`,
			`Acting white`,
			`All manners of honors`,
			`All my dead sisters`,
			`All types of girls, even ugly ones`,
			`An 800-foot-long pool noodle`,
			`An ambitious woman who wears pants`,
			`An elite squad known as the Special Victims Unit`,
			`Anything Asian`,
			`As ass like a bag of pool balls`,
			`Assembling IKEA furniture`,
			`Beef`,
			`Being hunted by giant eagles`,
			`Being inside me`,
			`Being seen reading Infinite Jest`,
			`Being shitty to everyone and late for everything`,
			`Big beefy baseball boys`,
			`Big Italian women making the spicy sauce`,
			`Bimpy, the small styrofoam ball we all jack off into`,
			`Bipolar Disorder`,
			`Blowing into the penis so that the balls inflate`,
			`Blue smoke coming out of my anus`,
			`Canada's worst mangoes`,
			`Carbs`,
			`Carlos Santana's horrible wailing guitar`,
			`Certain things, but not others`,
			`Chinese people`,
			`Chowder`,
			`Clearly asking for no cucumbers in my salad, and yet here we are`,
			`Clippy from Microsoft Office`,
			`Colluding with Russia`,
			`Corn`,
			`Country music legend Toby Keith`,
			`Crunchy snacks for big, flappy mouth`,
			`Cultural appropriation`,
			`Curly fries so good you quit ISIS`,
			`Dating a Republican`,
			`Death`,
			`Déjà vu`,
			`Déjà vu`,
			`Denying climate change`,
			`Doing ho shit`,
			`Doing it doggy, no kissing`,
			`Doing stuff bad`,
			`Drake`,
			`Driving to a Walmart parking lot and staring into the distance for eight hours`,
			`Eating pussy bad`,
			`Ejaculating a quart of hollandaise sauce`,
			`Elon Musk`,
			`Enticing a hummingbird to drink nectar out of my urethra`,
			`Fascism`,
			`Fat`,
			`Fingering each other's buttholes`,
			`Foul vegan shits`,
			`Free two-day shipping with Amazon Prime`,
			`Fresh Air with Terry Gross`,
			`Funneling money through a series of shell companies`,
			`Getting #MeToo'd`,
			`Getting banished to the Shadow Realm`,
			`Getting depressed and super fat`,
			`Getting fisted by a man with no fingers`,
			`Getting half-hard and trying to smoosh it in`,
			`Getting herpes from Bruce Willis`,
			`Getting Mommy another beer`,
			`Getting tanned, jacked, and juicy`,
			`Going "oink oink" like a nasty little pig boy`,
			`Good, clean Christian comedy`,
			`Having tuna sandwiches with my favorite honkies`,
			`Hard-hitting investigative journalism`,
			`Having a wonderful time at the zoo`,
			`Having no legs, just toes`,
			`Having thirty sons named Chad`,
			`Healthcare.gov`,
			`Hiding from border patrol`,
			`Hiking up a hillside covered in bear semen yelling "I'm the queen of the forest!"`,
			`Hoopnugget, the game where you throw a nugget into a hoop`,
			`How many bagels I can fit on my penis`,
			`How quiet the forest is`,
			`Huffing and puffing and blowing my stepdad`,
			`Hunting white men for sport`,
			`Hush money`,
			`Interrupting women`,
			`Jeremy and his stupid, annoying, dumb, hard, beautiful body`,
			`Jörmungandr the World Serpent`,
			`Joyless, wooden Soviet toys`,
			`Just a Luna bar for lunch`,
			`Kanye West but if he were an old Japanese farmer`,
			`Korean barbecue`,
			`Leading a country to war on false pretenses`,
			`Leading children around with a magical flute`,
			`Letting that pussy breathe`,
			`Letting this loser eat me out`,
			`Licking the toilet as Mistress commands`,
			`Life`,
			`Little Debbie and her mom, Full-Size Deborah`,
			`Lotion`,
			`Loving America`,
			`Magic: The Gathering`,
			`Making direct eye contact with a horse's asshole`,
			`Mark Zuckerberg`,
			`Maybe getting a little involved in selling heroin sometimes`,
			`Melania Trump`,
			`Murdering our parents`,
			`My buddy Jeff`,
			`My daughter fucking my boyfriend`,
			`My math teacher's bulge`,
			`My real dad`,
			`My secret butt`,
			`My son's dipshit friends`,
			`My son's husband's huge cock`,
			`My wife (in Borat voice)`,
			`Naked Dad`,
			`Netflix`,
			`New DNA evidence exonerating OJ Simpson`,
			`Nipples the size of CDs`,
			`None of your damn business`,
			`Nonsexual activiities, such as roller skating`,
			`Not being a part of my son's life`,
			`Oral`,
			`Outdated gender norms`,
			`Owing a lot of money to some very bad people`,
			`Panda Express`,
			`Panic and confusion`,
			`Pissin' me paants`,
			`Politics`,
			`Poppin' that pussy`,
			`Preparing my asshole for sex`,
			`Pretending golf is fun`,
			`Prison`,
			`Pulling a sick, shit-covered raccoon out of the toilet and nursing it back to health`,
			`Pulling the butt cheeks apart so the fart comes out quieter`,
			`Pushing my boob up to lick the nipple`,
			`Putting dirty dishes in the sink and hoping someone else deals with them`,
			`Quality, affordable menswear`,
			`Reparations for slavery`,
			`Representing the entire black community`,
			`Respecting woman`,
			`Rubbing my clit with a handgun`,
			`Sandwich`,
			`Schindler's List`,
			`Setting boundaries with co-workers`,
			`Sewing two hamsters together to make a Double Hamster Supreme`,
			`Shit`,
			`Shitting perfectly into a hot dog bun`,
			`Slaves`,
			`Slowly releasing a huge fart over the course of two minutes`,
			`Sluts, whores, and bitches`,
			`Small plates, or tapas if you will`,
			`Some cracker-ass motherfucker`,
			`Some light choking`,
			`Square dancing with other racists`,
			`Stapling a butterfly to a cow`,
			`Staying hydrated`,
			`Sticking my hard rat dick in my girlfiend's wet rat pussy`,
			`Substituting sweet potato fries for $2`,
			`Sucking the caviar straight out of a fish's pussy`,
			`Suddenly feeling really sad for 40 years`,
			`Swordplay`,
			`Taking a dump`,
			`Tar`,
			`The Asshole Destroyer 3000`,
			`The Audi Sign-and-Drive Sales Event`,
			`The awesome power of the Lord`,
			`The beautiful backpacks of JanSport`,
			`The boy who sucks the farts our of my sweatpants`,
			`The coming race war`,
			`The current political climate`,
			`The cutest fucking shoes I've ever seen`,
			`The end of all life on Earth`,
			`The express written consent of the National Basketball Association`,
			`The fact that time is moving backwards right now and nobody's noticing`,
			`The harsh reality that all horses are people in horse costumes`,
			`The incredible Gary, he'll suck your nipples`,
			`The kind of porn with poop`,
			`The King of Jews`,
			`The little-known fact that Polish people don't dream`,
			`The man in the basement`,
			`The man who fucks me and my wife`,
			`The Moon`,
			`The NRA`,
			`The pelican that will one day eat Scarlett Johansson's baby`,
			`The persecution of Buddhists by the American-backed government of South Vietnam`,
			`The pleasure of watching my boys wolf down my pot roast and scamper into the woods`,
			`The rock after which Dwayne Johnson was named`,
			`The South rising again`,
			`The wonderful giant spoon known as "ladle"`,
			`The world's largest baby, weighing over 700 pounds`,
			`The worm that ate my penis and is now my penis`,
			`These breasts of mine`,
			`This boring-ass white bitch from work`,
			`This kid I found`,
			`Thoughts and prayers`,
			`Three men and three hot dogs`,
			`Throwing a man by his big penis`,
			`Thrusting and grunting`,
			`Thumb, the King of the Fingers`,
			`Tiny, sour kisses from a lemon dwarf`,
			`Travolta`,
			`Trees with human skin`,
			`Turning poor people against each other so they don't pay attention to economic inequality`,
			`Twirling a cane, popping it into my anus, and giving a tip of the top hat`,
			`Uncles`,
			`Uncut daddy dick`,
			`Violating the Geneva Convention`,
			`Voldemort`,
			`Voter suppression`,
			`What looked like a chemical weapons facility but turned out to be a children's hospital`,
			`Women in positions of power`,
			`Yo stanky ass`,
			`Yogurt that moans in pleasure as you eat it`,
			`Your little booty in them underpants`,
			`Your mouth`,
			`Yummy yummy yummy yummy rat pussy`,
			`%blank`,
			`%blank`,
			`%blank`,
		},
	}

	AddPack(pack)
}
