package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "star-wars",
		Description: "Cards Against the Force. Compiled by The Galactic Republic",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s & %s. The best of both worlds.`},
			&PromptCard{Prompt: `%s and chill.`},
			&PromptCard{Prompt: `%s got me through the Battle of Saleucami! Ahh, the good stuff!`},
			&PromptCard{Prompt: `%s helped han do the kessel run in less that 12 parsecs.`},
			&PromptCard{Prompt: `%s is a girls best friend.`},
			&PromptCard{Prompt: `%s is a Jedi's best friend.`},
			&PromptCard{Prompt: `%s is a trick. Send no reply.`},
			&PromptCard{Prompt: `%s is better in space.`},
			&PromptCard{Prompt: `%s is definitly better than sex!`},
			&PromptCard{Prompt: `%s is definitly how I'd like to see Jar Jar Binks die.`},
			&PromptCard{Prompt: `%s is hiding on the Millenium Falcon.`},
			&PromptCard{Prompt: `%s is my new safe word.`},
			&PromptCard{Prompt: `%s is only legal in the Outer Rim.`},
			&PromptCard{Prompt: `%s is strong with this one.`},
			&PromptCard{Prompt: `%s is the best thing to happen in the Star Wars franchise.`},
			&PromptCard{Prompt: `%s is the most fun anyone can have Tatooine.`},
			&PromptCard{Prompt: `%s is the only chance of stopping the Empire.`},
			&PromptCard{Prompt: `%s is the path to the dark side.`},
			&PromptCard{Prompt: `%s is the reason evil exists in the galaxy!`},
			&PromptCard{Prompt: `%s is the reason why Princess Lei was so well respected.`},
			&PromptCard{Prompt: `%s is the sweetest revenge.`},
			&PromptCard{Prompt: `%s is what got me hooked on Star Wars`},
			&PromptCard{Prompt: `%s is what happens when nobody listens Luke Skywalker!`},
			&PromptCard{Prompt: `%s is what happens when Obi-Wan and Yoda work together.`},
			&PromptCard{Prompt: `%s is why Georgia Lucas Wrote Star Wars in the first place.`},
			&PromptCard{Prompt: `%s is why the new Star Wars movie is awesome!`},
			&PromptCard{Prompt: `%s is why the new Star Wars movie is sucked.`},
			&PromptCard{Prompt: `%s is worse than creating a clone army that can't aim.`},
			&PromptCard{Prompt: `%s is your weakness`},
			&PromptCard{Prompt: `%s isn't my fault! Jar Jar made me do it!`},
			&PromptCard{Prompt: `%s leads to the dark side.`},
			&PromptCard{Prompt: `%s made me sneeze blue milk out of my nose!`},
			&PromptCard{Prompt: `%s makes the dark side seem like an attractive option.`},
			&PromptCard{Prompt: `%s never fails to make the Emperor angry.`},
			&PromptCard{Prompt: `%s was all Landos Fault!`},
			&PromptCard{Prompt: `%s was being smuggled in the Millenium Falcon's secret compartment`},
			&PromptCard{Prompt: `%s was Darth Maul's guilty pleasure`},
			&PromptCard{Prompt: `%s was the real reason the sand people feared Ben Kenobi.`},
			&PromptCard{Prompt: `%s with a Wookiee is a bad idea.`},
			&PromptCard{Prompt: `%s would really help Darth Vader chill out.`},
			&PromptCard{Prompt: `%s: A Star Wars Story.`},
			&PromptCard{Prompt: `%s! Roger Roger.`},
			&PromptCard{Prompt: `%s! That is why we’re losing this war!`},
			&PromptCard{Prompt: `%s! What is it good for? Absolutely nothing!`},
			&PromptCard{Prompt: `%s. Best. Character. Ever.`},
			&PromptCard{Prompt: `%s. Force tested. Jedi approved.`},
			&PromptCard{Prompt: `%s. Good to the last drop!`},
			&PromptCard{Prompt: `%s. The other white meat.`},
			&PromptCard{Prompt: `A Jedi must focus on %s when in battle`},
			&PromptCard{Prompt: `A long time ago in a galaxy far, far away: %s.`},
			&PromptCard{Prompt: `A romantic candlelit dinner on Naboo isn’t complete without %s.`},
			&PromptCard{Prompt: `Aayla Secura’s hair feels like %s.`},
			&PromptCard{Prompt: `Adept, I need the most anal retentive %s.`},
			&PromptCard{Prompt: `Admiral Motti knows that the best way to rise in the ranks of the Empire is through %s.`},
			&PromptCard{Prompt: `After blowing up the Death Star the Rebels celebrated with %s.`},
			&PromptCard{Prompt: `Ahsoka Tano dreamt of %s with Anakin Skywalker.`},
			&PromptCard{Prompt: `Anakin - "I hate you" Obi Wan - "You were my %s Anakin, Ioved you!`},
			&PromptCard{Prompt: `Anakin and Padme's relationship was as awkward as %s.`},
			&PromptCard{Prompt: `Anakin didnt want to kill younglings, until he found out they were doing %s.`},
			&PromptCard{Prompt: `Anakin enjoys %s on his days off from Jedi training.`},
			&PromptCard{Prompt: `Anakin killed the younglings because %s.`},
			&PromptCard{Prompt: `Anakin loves Padme's interest in %s.`},
			&PromptCard{Prompt: `Anakin Skywalker loves%s when he’s not %s.`},
			&PromptCard{Prompt: `And I thought they smelled like %s on the outside.`},
			&PromptCard{Prompt: `Any attack by the rebels would result in %s.`},
			&PromptCard{Prompt: `Arye's to do list consists of %s, %s, and %s.`},
			&PromptCard{Prompt: `As well as killing the Jedi, Order 66 also forced %s on all stormtroopers.`},
			&PromptCard{Prompt: `As well as the Death Star’s weakness, Galen Erso also exposed %s.`},
			&PromptCard{Prompt: `As well as the plans to the Death Star the files also contained footage of %s.`},
			&PromptCard{Prompt: `Asajj Ventress’ favorite way to assassinate someone is by %s.`},
			&PromptCard{Prompt: `Bad idea #27: %s.`},
			&PromptCard{Prompt: `Bail Organa regretted adopting Leia. When she was young, all she wanted was %s.`},
			&PromptCard{Prompt: `Be mindful of %s Anakin. They’ll betray you.`},
			&PromptCard{Prompt: `Becoming a Jedi takes years of %s as well as %s.`},
			&PromptCard{Prompt: `Beep, beep, boop, beep, boop %s.`},
			&PromptCard{Prompt: `Before becoming the leader of the Galactic Empire, Senator Palpatine was into %s.`},
			&PromptCard{Prompt: `Before the dark times. Before the Empire. There was %s.`},
			&PromptCard{Prompt: `Being tall helps Wookiees when looking for %s.`},
			&PromptCard{Prompt: `Boba Fett panicked when he saw %s.`},
			&PromptCard{Prompt: `Boba Fett relaxes with %s.`},
			&PromptCard{Prompt: `By far the worse thing to happen in the Star Wars universe has to be %s.`},
			&PromptCard{Prompt: `C-3PO is so reliant on R2-D2, that he asks him for %s every day.`},
			&PromptCard{Prompt: `Captain Phasma’s so cool. She keeps the other stormtroopers under control by %s.`},
			&PromptCard{Prompt: `Captain Rex never wanted to fight in the Clone Wars. He would have preferred %s.`},
			&PromptCard{Prompt: `Chewbacca likes %s, only hairier.`},
			&PromptCard{Prompt: `Chewbacca will often need %s to be happy.`},
			&PromptCard{Prompt: `Clone Troopers have 99 orders but %s ain't one.`},
			&PromptCard{Prompt: `Cloud city was famous for %s.`},
			&PromptCard{Prompt: `Dagobah at night is one of the best places for %s.`},
			&PromptCard{Prompt: `Dagobah was where Yoda first learned about %s`},
			&PromptCard{Prompt: `Darth Maul enjoyed %s before battle.`},
			&PromptCard{Prompt: `Darth Maul hid on Lotho Minor along with %s.`},
			&PromptCard{Prompt: `Darth Plagueis finally found the secret to immortality: %s.`},
			&PromptCard{Prompt: `Darth Vader will never allow %s on his Star Destroyer.`},
			&PromptCard{Prompt: `Did anyone else wonder why Han was smuggling %s?`},
			&PromptCard{Prompt: `Do or do not there is no try, except when %s is/are concerned.`},
			&PromptCard{Prompt: `Do, or do not. There is no %s!`},
			&PromptCard{Prompt: `Don't forget to save %s!`},
			&PromptCard{Prompt: `Don't tell the Emperor, but Vader is secretly %s when not on duty.`},
			&PromptCard{Prompt: `Don’t try to frighten us with %s, Lord Vader.`},
			&PromptCard{Prompt: `Dormé was privy to a lot of secrets. Once she saw %s.`},
			&PromptCard{Prompt: `Each time Chewie speaks, he is actually saying, " %s".`},
			&PromptCard{Prompt: `Emperor Palpatine gets a certain amount of satisfaction from %s.`},
			&PromptCard{Prompt: `Empire law now prohibits %s on Death Stars.`},
			&PromptCard{Prompt: `Enjoying %s , I do.`},
			&PromptCard{Prompt: `Episode I: The Phantom %s`},
			&PromptCard{Prompt: `Episode II: Attack of %s`},
			&PromptCard{Prompt: `Episode III: Revenge of %s.`},
			&PromptCard{Prompt: `Episode IV: A New %s`},
			&PromptCard{Prompt: `Episode V: %s Strikes Back`},
			&PromptCard{Prompt: `Episode VI: Return of %s.`},
			&PromptCard{Prompt: `Ewoks are great when you’re %s.`},
			&PromptCard{Prompt: `Fan fiction made Leia fantasize about %s.`},
			&PromptCard{Prompt: `Fear leads to anger. Anger leads to hate. Hate leads to %s.`},
			&PromptCard{Prompt: `Finn’s first memory as a child was %s.`},
			&PromptCard{Prompt: `Following his death, Jar Jar Binks’ memorial service was only attended by %s.`},
			&PromptCard{Prompt: `For Father’s Day, Luke got Darth Vader %s.`},
			&PromptCard{Prompt: `General Grievous always looked so miserable because of %s.`},
			&PromptCard{Prompt: `General Grievous enjoys%s when nobody is looking.`},
			&PromptCard{Prompt: `General Grievous, after suffering a hit to the head, now collects %s.`},
			&PromptCard{Prompt: `Give her %s, immediately!`},
			&PromptCard{Prompt: `Goooood… let %s flow through you.`},
			&PromptCard{Prompt: `Governor Tarkin lied about %s.`},
			&PromptCard{Prompt: `Grand Admiral Thrawn likes adding %s to his art collection because it reminds him of %s.`},
			&PromptCard{Prompt: `Grand Moff Tarkin drinks to forget %s.`},
			&PromptCard{Prompt: `Greedo has a sixth sense. His eyes let him see %s.`},
			&PromptCard{Prompt: `Greedo wished he had more training with %s before trying to capture Han.`},
			&PromptCard{Prompt: `Han Solo blames %s for all his troubles.`},
			&PromptCard{Prompt: `Han Solo is wanted for %s in 12 systems!`},
			&PromptCard{Prompt: `Han Solo taught me how to smuggle %s.`},
			&PromptCard{Prompt: `Have you noticed that %s and %s are basically the same?`},
			&PromptCard{Prompt: `Have you seen the deepfake video showing %s on Pornhub?`},
			&PromptCard{Prompt: `Help me Obi Wan Kenobi! You're %s.`},
			&PromptCard{Prompt: `Herding Nerfs is easier than %s.`},
			&PromptCard{Prompt: `Honestly, I'd rather live on Alderaan than have to watch %s again!`},
			&PromptCard{Prompt: `How can %s be so wrong, yet feel so right!`},
			&PromptCard{Prompt: `I am all the %s, and I am all the %s!`},
			&PromptCard{Prompt: `I am one with %s.`},
			&PromptCard{Prompt: `I associate more with the Empire because of my life long desire for %s.`},
			&PromptCard{Prompt: `I blame %s for the breakup of my last relationship.`},
			&PromptCard{Prompt: `I can't believe Disneyland created a Star Wars attraction dedicated to %s!`},
			&PromptCard{Prompt: `I can't believe I only noticed %s when watching Star Wars for a second time.`},
			&PromptCard{Prompt: `I cannot teach him, he is %s.`},
			&PromptCard{Prompt: `I cant be the only one who can't stand %s!`},
			&PromptCard{Prompt: `I fear you underestimate %s.`},
			&PromptCard{Prompt: `I find your lack of %s disturbing.`},
			&PromptCard{Prompt: `I left the cinema after watching The Last Jedi and immediately asked for %s.`},
			&PromptCard{Prompt: `I sense %s in you, Skywalker.`},
			&PromptCard{Prompt: `I sense great fear in you, Skywalker. You have hate. You have %s.`},
			&PromptCard{Prompt: `I still don't understand why a Wampa replace his arm with %s.`},
			&PromptCard{Prompt: `I wish C-3PO was programmed to think about %s.`},
			&PromptCard{Prompt: `I wish they made a Star Wars action figure of %s.`},
			&PromptCard{Prompt: `I'd love to see a dance off between %s and %s!`},
			&PromptCard{Prompt: `I've been watching a video of %s on repeat.`},
			&PromptCard{Prompt: `I've never understood the scene that shows %s.`},
			&PromptCard{Prompt: `I’d love to live on Endor, even if it just means that I could experience %s.`},
			&PromptCard{Prompt: `I’m receiving a strange transmission. It sounds like %s.`},
			&PromptCard{Prompt: `If a stormtrooper were to try stand-up comedy, their first joke should be about %s.`},
			&PromptCard{Prompt: `If a Wampa was to shave off all its hair it would look like %s.`},
			&PromptCard{Prompt: `If I had a Padawan, I’d give them %s in the name of training.`},
			&PromptCard{Prompt: `If into the security recordings you go, only %s will you find.`},
			&PromptCard{Prompt: `If you only knew the power of %s.`},
			&PromptCard{Prompt: `If%s is going to work, we need %s.`},
			&PromptCard{Prompt: `In a former life, R2-D2 was used for %s.`},
			&PromptCard{Prompt: `In a galaxy far, far, away, %s is perfectly legal.`},
			&PromptCard{Prompt: `In an early draft of the screenplay, Darth Vader’s actual line is, “Luke, I am %s"`},
			&PromptCard{Prompt: `In light of the recent events in the Senate , we have allowed %s`},
			&PromptCard{Prompt: `In the Galactic Empire, the punishment for %s is %s.`},
			&PromptCard{Prompt: `In the next Star Wars movie we learn that the force was actually %s all along.`},
			&PromptCard{Prompt: `In the privacy of his own home, Han Solo likes %s.`},
			&PromptCard{Prompt: `In this household, George Lucas is worshiped like %s.`},
			&PromptCard{Prompt: `It can be so devastating to find %s inside an X-wing cockpit.`},
			&PromptCard{Prompt: `It makes sense that Han Solo comes from Corellia. All the people are %s.`},
			&PromptCard{Prompt: `It's not wise upset a Wookiee. It always ends with %s.`},
			&PromptCard{Prompt: `It's the ship that made the Kessel Run %s!`},
			&PromptCard{Prompt: `IT’S %s!`},
			&PromptCard{Prompt: `It’s fun when you encounter %s with Lando Calrissian.`},
			&PromptCard{Prompt: `It’s just about %s in the Star Wars universe.`},
			&PromptCard{Prompt: `Jabba got rid of the Rancor Pit and replaced it with %s pit.`},
			&PromptCard{Prompt: `Jabba the Hutt has a room dedicated to %s.`},
			&PromptCard{Prompt: `Jabba’s palace was decorated with the remains of %s.`},
			&PromptCard{Prompt: `Jango Fett’s armor was originally made from %s.`},
			&PromptCard{Prompt: `Jar Jar Binks thought everyone loved him until he encountered %s.`},
			&PromptCard{Prompt: `Jedi mind tricks are to blame for %s.`},
			&PromptCard{Prompt: `Join me, and together we can rule %s.`},
			&PromptCard{Prompt: `Join the Empire. We have %s.`},
			&PromptCard{Prompt: `Joining the Imperial fleet is awesome, because you see %s.`},
			&PromptCard{Prompt: `Kylo couldn't commit to the dark side until he let go of %s.`},
			&PromptCard{Prompt: `Kylo Ren based his entire character around %s.`},
			&PromptCard{Prompt: `Kylo Ren changed his name because he was sick of %s.`},
			&PromptCard{Prompt: `Kylo Ren is best known for %s.`},
			&PromptCard{Prompt: `Kylo Ren’s real reason for his betrayal is %s.`},
			&PromptCard{Prompt: `Longo Two Guns’ nickname as “Fastest Blaster on Tatooine” really refers to %s.`},
			&PromptCard{Prompt: `Looking back on Return of the Jedi, it reminds me of%s.`},
			&PromptCard{Prompt: `Lower your shields, I’m entering %s.`},
			&PromptCard{Prompt: `Luke could use the Force for %s.`},
			&PromptCard{Prompt: `Luke managed to get through the blockade of Hoth by distracting the Imperial troops with %s.`},
			&PromptCard{Prompt: `Luke nicknamed his Land Speeder %s.`},
			&PromptCard{Prompt: `Luke Skywalker still might have his hand if he relied on %s.`},
			&PromptCard{Prompt: `Luke, I am %s.`},
			&PromptCard{Prompt: `Luke, you can destroy the Emperor. He has foreseen %s.`},
			&PromptCard{Prompt: `Luke. Use %s!`},
			&PromptCard{Prompt: `Luminous beings are we. Not %s.`},
			&PromptCard{Prompt: `Make %s great again!`},
			&PromptCard{Prompt: `Man who says kenobi stopped saying kenobi when %s.`},
			&PromptCard{Prompt: `Maz Kanata knows all to well about the need for%s.`},
			&PromptCard{Prompt: `Midi-chlorians, while enabling contact with the Force, also help with %s.`},
			&PromptCard{Prompt: `My favorite error in the Star Wars franchise was %s.`},
			&PromptCard{Prompt: `My latest force power is %s.`},
			&PromptCard{Prompt: `My ultimate fantasy would have to involve %s and %s.`},
			&PromptCard{Prompt: `Nal Hutta is the number one location in the universe for people who desire %s.`},
			&PromptCard{Prompt: `Never underestimate the joy you get from %s.`},
			&PromptCard{Prompt: `Next time you’re feeling down, just remember that Kylo Ren is %s.`},
			&PromptCard{Prompt: `No reward is worth %s.`},
			&PromptCard{Prompt: `Obi-Wan doesn’t recognize R2-D2 because he suffering PTSD from %s.`},
			&PromptCard{Prompt: `Obi-Wan Kenobi first felt the force through %s.`},
			&PromptCard{Prompt: `Obi-Wan was thinking about %s as he left Anakin to die?`},
			&PromptCard{Prompt: `On his days off, Captain Rex likes %s.`},
			&PromptCard{Prompt: `On his first flight in an X-wing, Ello Asty felt like %s.`},
			&PromptCard{Prompt: `On the night of their wedding, Anakin and Padmé enjoyed %s.`},
			&PromptCard{Prompt: `Once Yoda considered trying %s to stop %s.`},
			&PromptCard{Prompt: `One thing's for sure, we're %s.`},
			&PromptCard{Prompt: `Order 62 is %s.`},
			&PromptCard{Prompt: `Palpatine became a Sith because of his hatred of %s.`},
			&PromptCard{Prompt: `Plo Koon blackmailed his way on to the Jedi High Council with video footage of Yoda and %s.`},
			&PromptCard{Prompt: `Pod racing is nearly as fun as %s.`},
			&PromptCard{Prompt: `Poe Dameron can’t control himself when he sees %s.`},
			&PromptCard{Prompt: `Princess Leia decided %s would help the Rebel Alliance.`},
			&PromptCard{Prompt: `Princess Leia hid the Death Star plans with %s.`},
			&PromptCard{Prompt: `Princess Leia would definitely choose %s over %s.`},
			&PromptCard{Prompt: `Princess Leia’s speech about %s was inspirational as fuck!`},
			&PromptCard{Prompt: `Qui-Gon Jinn is a master of %s.`},
			&PromptCard{Prompt: `R2-D2 has been programmed for %s.`},
			&PromptCard{Prompt: `R2-D2 saw %s on the Death Star server.`},
			&PromptCard{Prompt: `R2-D2’s data was corrupted by %s.`},
			&PromptCard{Prompt: `Remember that time Yoda was talking about %s?`},
			&PromptCard{Prompt: `Remember… %s will be with you. Always.`},
			&PromptCard{Prompt: `Return of the Jedi helped me when I was young. It taught me the importance of %s.`},
			&PromptCard{Prompt: `Rey's parents are %s and %s.`},
			&PromptCard{Prompt: `Rey’s true Father is %s.`},
			&PromptCard{Prompt: `Scientists have recently proven that the force actually comes from %s`},
			&PromptCard{Prompt: `Search your feelings and you’ll find %s.`},
			&PromptCard{Prompt: `Shiv Palpatine was so angry because he never truly understood %s.`},
			&PromptCard{Prompt: `Some of R2-D2’s high pitched beeping can only be heard by %s.`},
			&PromptCard{Prompt: `Star Wars Battlefront was such a letdown that I’d rather play with %s.`},
			&PromptCard{Prompt: `Star Wars clearly discriminates against %s.`},
			&PromptCard{Prompt: `Star Wars is the classic story of %s.`},
			&PromptCard{Prompt: `Step 1: %s Step 2: %s Step 3: Jedi Master`},
			&PromptCard{Prompt: `Step 1: %s Step 2: %s Step 3: Rule the Galaxy.`},
			&PromptCard{Prompt: `Strike me down and I shall grow %s.`},
			&PromptCard{Prompt: `Supreme Leader Snoke died because of %s.`},
			&PromptCard{Prompt: `Supreme Leader Snoke might have gotten away with it if it wasn’t for %s.`},
			&PromptCard{Prompt: `Tell me honestly. Is it weird that I masturbate to %s?`},
			&PromptCard{Prompt: `That's not %s! It's %s!`},
			&PromptCard{Prompt: `The awkward moment Luke found Vader's collection of videos about %s.`},
			&PromptCard{Prompt: `The bags under Palpatine’s eyes are actually from %s.`},
			&PromptCard{Prompt: `The Battle of Endor turned the tide of the war. Since then %s has been illegal.`},
			&PromptCard{Prompt: `The Battle of Hoth was so cold that %s was impossible.`},
			&PromptCard{Prompt: `The Battle of Hoth will be remembered for %s.`},
			&PromptCard{Prompt: `The best thing about Count Dooku is that he likes %s.`},
			&PromptCard{Prompt: `The best way to bribe a Jedi is with %s.`},
			&PromptCard{Prompt: `The best way to die in Star Wars would be by %s.`},
			&PromptCard{Prompt: `The exciting new Star Wars toy collection will include %s.`},
			&PromptCard{Prompt: `The first thing Qui-Gon Jinn learned from Count Dooku was how to use the Force for %s.`},
			&PromptCard{Prompt: `The first time I saw Star Wars, I was amazed by %s.`},
			&PromptCard{Prompt: `The fog on Mimban was so thick that you couldn’t even see %s.`},
			&PromptCard{Prompt: `The Force Awakens is simply about %s.`},
			&PromptCard{Prompt: `The force choke is responsible for %s.`},
			&PromptCard{Prompt: `The force is for %s and %s.`},
			&PromptCard{Prompt: `The force is what gives a Jedi his power. It surrounds us, penetrates us, it's %s.`},
			&PromptCard{Prompt: `The Imperial Senate decided that %s was more important than %s.`},
			&PromptCard{Prompt: `The Imperial Senate found out that Princess Leia was afraid of %s.`},
			&PromptCard{Prompt: `The Imperial weapons facility on Eadu was also used for research into %s.`},
			&PromptCard{Prompt: `The inside of Darth Vader's helmet smells like %s!`},
			&PromptCard{Prompt: `The Jedi council never believed in %s. They were wrong.`},
			&PromptCard{Prompt: `The Jedi Council recently banned %s to avoid %s.`},
			&PromptCard{Prompt: `The Last Jedi is %s.`},
			&PromptCard{Prompt: `The Millennium Falcon couldn't take off because Han hadn't finished %s.`},
			&PromptCard{Prompt: `The most powerful Jedi mind trick leads to %s.`},
			&PromptCard{Prompt: `The next Death Star shoots %s instead of lasers.`},
			&PromptCard{Prompt: `The only thing better than kissing your sister is %s.`},
			&PromptCard{Prompt: `The only thing worse than Jar Jar Binks is %s.`},
			&PromptCard{Prompt: `The only way to unite the galaxy is through %s.`},
			&PromptCard{Prompt: `The opening line on Han Solo's Tinder profile mentions %s.`},
			&PromptCard{Prompt: `The people of Jakku celebrate the new harvest with %s.`},
			&PromptCard{Prompt: `The people of Naboo celebrate with %s.`},
			&PromptCard{Prompt: `The power of a lightsaber comes from %s.`},
			&PromptCard{Prompt: `The Princess is ours! Guard her well and make sure she isn’t %s.`},
			&PromptCard{Prompt: `The prize for the first pod race held on Malastare was %s.`},
			&PromptCard{Prompt: `The radiation from hyperspace causes %s.`},
			&PromptCard{Prompt: `The Rebel Alliance recruiter promised me %s.`},
			&PromptCard{Prompt: `The Rebel Alliance was lucky %s was here!`},
			&PromptCard{Prompt: `The rebellion began with %s, and ended with %s.`},
			&PromptCard{Prompt: `The rebels latest secret weapon is %s.`},
			&PromptCard{Prompt: `The Republic will rejoice the ending of %s.`},
			&PromptCard{Prompt: `The shape of the Star Destroyer always reminds me of %s.`},
			&PromptCard{Prompt: `The Sith have started teaching %s.`},
			&PromptCard{Prompt: `The Star Wars theme park experience was so underwhelming because it includes %s.`},
			&PromptCard{Prompt: `The Star Wars tragedy that always brings tears to my eyes involves %s.`},
			&PromptCard{Prompt: `The stormtroopers keep hitting %s instead of their target.`},
			&PromptCard{Prompt: `The Trade Federation made their money from %s.`},
			&PromptCard{Prompt: `The Wookiee's are the only ones who truly appreciate %s.`},
			&PromptCard{Prompt: `There is a special room in the Jedi temple dedicated to %s.`},
			&PromptCard{Prompt: `There was a whole floor dedicated to %s on the Death Star.`},
			&PromptCard{Prompt: `There's only one thing worse than %s. It's %s!`},
			&PromptCard{Prompt: `There’s a strong chance senator Bale Organa won’t get re-elected because of %s.`},
			&PromptCard{Prompt: `There’s only 17 letters in the Wookiee alphabet. Luckily, that’s enough to spell %s.`},
			&PromptCard{Prompt: `They don't say it in the movies, but I swear Padme is allergic to %s.`},
			&PromptCard{Prompt: `This is Master Obi-Wan Kenobi, I regret to report that %s.`},
			&PromptCard{Prompt: `This is outrageous! It's unfair! How can one be on the council and not be a %s.`},
			&PromptCard{Prompt: `This weekend, thousands of stormtroopers around the galaxy will be %s.`},
			&PromptCard{Prompt: `To celebrate Disney’s acquisition of the Star Wars franchise, George Lucas invested in %s.`},
			&PromptCard{Prompt: `To make a deal with Watto requires %s.`},
			&PromptCard{Prompt: `Trusting Faro Argyus will only result in %s.`},
			&PromptCard{Prompt: `Uncle Owen and Aunt Beru have been arrested by stormtroopers for %s.`},
			&PromptCard{Prompt: `Under her cloak, Luminara Unduli was %s.`},
			&PromptCard{Prompt: `Using the force for %s always ends in %s.`},
			&PromptCard{Prompt: `Warwick Davis plays more characters in Star Wars than anyone else because he was the perfect height for %s.`},
			&PromptCard{Prompt: `Watto's breath smells like %s.`},
			&PromptCard{Prompt: `We can’t count on Han anymore. He’s too busy with %s.`},
			&PromptCard{Prompt: `We don't even know what that means! We are %s.`},
			&PromptCard{Prompt: `Wedge Antilles can fly any spaceship in the known galaxy. But he can’t use %s to save himself.`},
			&PromptCard{Prompt: `Well, it looks like Boba Fett is busy with %s yet again.`},
			&PromptCard{Prompt: `When %s occurs, “May The Force Be With You”.`},
			&PromptCard{Prompt: `When a Jedi gets a headache, the best cure is %s.`},
			&PromptCard{Prompt: `When Admiral Motti was being choked by Vader, all he could think about was %s.`},
			&PromptCard{Prompt: `When Darth Maul got cut in half %s popped out.`},
			&PromptCard{Prompt: `When Darth Vader says he likes %s, he gets it!`},
			&PromptCard{Prompt: `When I heard JJ Abrams was directing the ninth Star Wars movie, I felt like %s.`},
			&PromptCard{Prompt: `When I’m done with you, I’m going to enjoy %s and throw you in the Sarlacc pit.`},
			&PromptCard{Prompt: `When my kids are old enough ill make them watch %s.`},
			&PromptCard{Prompt: `When Obi-Wan said, “Be mindful of your thoughts, Anakin. They’ll betray you.” It’s clear Anakin was thinking about %s.`},
			&PromptCard{Prompt: `When the first transport got away, the Rebels cheered because it contained %s.`},
			&PromptCard{Prompt: `When you master the strength of the force, you will learn the importance of %s.`},
			&PromptCard{Prompt: `Whenever I hum the Star Wars theme tune I always think of %s.`},
			&PromptCard{Prompt: `While Darth Vader was fighting Luke he couldn’t stop thinking about %s.`},
			&PromptCard{Prompt: `Without %s the Rebels would never have won the Battle of Endor.`},
			&PromptCard{Prompt: `Without the Empire Strikes Back, %s wouldn't exist.`},
			&PromptCard{Prompt: `X-Wings fighters are faster when looking for %s.`},
			&PromptCard{Prompt: `Yoda is a Jedi Master who enjoys %s.`},
			&PromptCard{Prompt: `Yoda says that fear is the path to the dark side, but %s also does too.`},
			&PromptCard{Prompt: `Yoda walked in on me masturbating to %s.`},
			&PromptCard{Prompt: `Yoda's soup is made from %s.`},
			&PromptCard{Prompt: `You all like %s better than me.`},
			&PromptCard{Prompt: `You fool! I've been trained in %s by %s.`},
			&PromptCard{Prompt: `You know Jabba the Hut is sick in the head when he’s into %s.`},
			&PromptCard{Prompt: `Your sad devotion to %s has failed to conjure up the missing plans.`},
		},
		Responses: []ResponseCard{
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`900 Magna Guards stored up Wat Tambor's Ass`,
			`a 1977 Topps Star Wars error card`,
			`a 34 week abortion`,
			`a bag of Wookiee Cookies`,
			`a ball of Ewok earwax`,
			`a beautifully sculptured goatee`,
			`a black guy robbing someone at lightsaber point`,
			`a blaster pistol`,
			`a blue milk enema`,
			`a Boba Fett-ish`,
			`a bucket of bolts`,
			`a bunch of flowers to say sorry for killing your son`,
			`a Chlamydia outbreak in the Ewok population`,
			`a cloak made of synthfur`,
			`a coin purse made from Anakin's severed testicles`,
			`a confusing plot about trade that nobody really understood`,
			`a couple of hours with the carbonite machine`,
			`a cup of Hoth chocolate`,
			`a dead AT-AT`,
			`a Death Star made out of vaginas`,
			`a diet consiting solely of Trandoshani flatcakes`,
			`a double-bladed lightsaber`,
			`a fart so potent it causes the evacuation of the Death Star`,
			`a force ghost watching you masturbate`,
			`a force sensitive paraplegic`,
			`a full muff`,
			`a gang bang with Clone Troopers`,
			`a glory hole in the Mos Eisley Cantina`,
			`a golden shower from Jabba the Hutt`,
			`a home job Star Wars tattoo`,
			`a huge, pulsating Lightsaber`,
			`a Jedi concentration camp`,
			`a Jedi Master's constant trolling of their students`,
			`a kyber crystal powered vibrator`,
			`a lightsaber circumcision`,
			`a lightsaber running out of batteries mid fight`,
			`a little light incest`,
			`a long time ago in a galaxy far, far away...`,
			`a mail order bride from Tatooine`,
			`a majestic score from John Williams`,
			`a poorly made lightsaber`,
			`a Porg giving you bedroom eyes`,
			`a Porg slaughtered halal style`,
			`a posh wank`,
			`a public execution in Pau City`,
			`a punch up between K-S0 and IG-88`,
			`a racist Emperor that oversees hundreds of alien races`,
			`a ransom note`,
			`a rim job in the Outer Rim`,
			`a risky blowjob from a Sarlacc`,
			`a sad devotion to an aging religion`,
			`a Sarlacc fleshlight`,
			`a serious case of irritable bowel syndrome while trapped in the trash compactor`,
			`a seriously underrated Y-Wing pilot`,
			`a shaved Wampa`,
			`a squadron of X-Wings`,
			`a staged sex tape`,
			`a Star Wars character with Tariq's voice and Brad Pitt's body`,
			`a Star Wars Holiday Special`,
			`a Star Wars/Star Trek crossover movie`,
			`a storm trooper's poor aim`,
			`a Stormtrooper lives matter campaign`,
			`a Stormtrooper's Grindr profile`,
			`a submissive B1 battle droid`,
			`a subtle dick rub in public`,
			`a Tauntaun sleeping bag`,
			`a three point turn in the Millenium Falcon`,
			`a threesome with Uncle Owen and Aunt Beru`,
			`a token black Storm Trooper`,
			`a trashcan shaped like Kylo Ren`,
			`a trip to Kashyyk to get some wookie nookie`,
			`a Wampa's alopecia`,
			`a Wookie steak cooked medium rare`,
			`a Wookie's Bowcaster`,
			`A&E's new reality show: "Boba Fett: The Bounty Hunter"`,
			`abusing Star Wars actors online`,
			`accidentally buying Cards Against the Force for an 8 year old`,
			`accidentally filled the car with Rhydonium instead of gas`,
			`accidentally turning on a lightsaber when you're mastrubating with it`,
			`activating the tractor beam`,
			`Admiral Ackbar Sushi`,
			`Admiral Motti begging Darth Vader to choke him again`,
			`Admiral Motti choking on his own vomit`,
			`Alderaan Deniers`,
			`Alien VS Predator VS C3-PO`,
			`Amilyn Holdo's hairdresser`,
			`an accidental circumsision with a lightsaber`,
			`an E-11 blaster that only shoots urine`,
			`an episode of Maury featuring the Skywalker's`,
			`an erection that lasts for more than 4 hours`,
			`an Ewok Deathmatch`,
			`an Ewok riding an AT-ST`,
			`an imaginary childhood friend`,
			`an Imperial Senate Bukkake scene`,
			`an oestrogen fuelled fight to the death`,
			`an orgy on the Death Star`,
			`an outer rim job`,
			`an uncontrollable urge to wet yourself`,
			`an X-Wing pilot in a metal bikini`,
			`Anakin Skywalker   `,
			`Anakin Skywalker masturbating for the first time`,
			`Anakin Skywalker’s bacne`,
			`Anakin Skywalker’s evil eyes`,
			`Anakin Skywalker’s first pubes`,
			`Anakin Skywallker's missing legs`,
			`Anisoka.`,
			`annoying CGI scenes`,
			`annoying improbable theories about Rey's parents`,
			`Arc Gang`,
			`arm-wrestling Chewbacca`,
			`Asajj Ventress`,
			`AT-ATs going at it doggy style`,
			`Aunt Beru`,
			`Aunt Beru's breast milk cheese`,
			`Aunt Beru's burning corpse`,
			`bad parenting`,
			`bashing BB-8 with a sledgehammer`,
			`BB-8 slipping on sand`,
			`BB-8's sexual attachments`,
			`BB-8’s ball bearings`,
			`beating a Jedi in a bar fight`,
			`becoming a billionaire by refusing to relinquish marketing rights`,
			`becoming Saw Gerrera’s sex slave`,
			`being a wanted man in twelve systems`,
			`being abandoned on Jakku`,
			`being as blind as Maz Kanata`,
			`being dominated by Phasma`,
			`being genuinely attracted to Jabba the Hutt`,
			`Being hunted by a tribe of bloodthirsty Ewoks.`,
			`being put up for adoption`,
			`being such an asshole that even the sith didnt want you`,
			`being teasingly licked by Jar Jar`,
			`being the only human in a Mandalorian Orgy`,
			`being wanted by several bounty hunters for fucking all their Moms`,
			`Ben Kenobi`,
			`Bib Fortuna’s British teeth`,
			`blue balls`,
			`Boba Fett`,
			`Boba Fett licking Han Solo's face while he was frozen in carbonite`,
			`Boba Fett’s stunning array of weaponry`,
			`bombing the Jedi Temple.`,
			`boring missionairy sex with a Star Wars princess`,
			`Boss Nass`,
			`Boss Nass farting on your face`,
			`bragging about kissing your sister`,
			`braiding Princess Leia's pubse`,
			`C-3PO`,
			`C-3PO giving a golden shover`,
			`calling Darth Vader "Daddy" while he force chokes you`,
			`Captain Phasma`,
			`Captain Rex`,
			`carbonite breast implants`,
			`Carrie Fisher`,
			`catching genital warts from the toilet of the Millenium Falcon`,
			`celebrating Life Day on Alderaan`,
			`cheating in a pod race`,
			`cheering when an Ewok dies`,
			`Chewbacca`,
			`Chewbacca's surprisingly not unpleasant body odor`,
			`Chewbacca's surprisingly tidy pubes`,
			`Chewbacca’s secret flap`,
			`chopping Maul in half with a lightsaber.`,
			`cleaning out Yoda's 800 year old ears`,
			`Clone Troopers`,
			`Commander Cody's crotch protector`,
			`commanding an AT-AT`,
			`continually having a 'bad feeling about this'`,
			`Count Dooku`,
			`Count Dooku's dementia`,
			`Count Dooku's hipster beard`,
			`Count Dooku's Viagra`,
			`Count Dooku’s grey pubes`,
			`counterfeit Star Wars merchandise`,
			`crabby old Ben Kenobi`,
			`Cry-lo Ren`,
			`crying like the Rancor keeper`,
			`cumming inside your girl even when she says not to`,
			`cupping Ubbla Mollbro’s engorged egg sacs`,
			`cutting off a Padawan's braid`,
			`Dagobah Hookers`,
			`Darth Jar Jar`,
			`Darth Maul`,
			`Darth Maul's merkin`,
			`Darth Maul’s lip balm`,
			`Darth Tantrum`,
			`Darth Tariq`,
			`Darth Vader`,
			`Darth Vader's asthma`,
			`Darth Vader's chain smoking`,
			`Darth Vader's charred penis`,
			`Darth Vader's sex appeal`,
			`death sticks`,
			`decapitation`,
			`demanding a DNA test`,
			`demanding Shmi Skywalker's birth certificate`,
			`dipping your balls in a glass of Corellian whiskey`,
			`discovering that Finn is a power bottom from his Grindr profile`,
			`discovering who your Father is on an episode of Maury`,
			`distasteful side boob`,
			`doing the windmill with your flaccid penis`,
			`Donald trump running the Imperial senate`,
			`donkey punching Tusken Raiders`,
			`drinking the sweat from a Tauntaun's balls`,
			`driving your starship over the speed limit to compensate for your tiny penis`,
			`droid sex`,
			`dying alone`,
			`eating tuna with Bib Fortuna`,
			`ejaculating midichlorians`,
			`Emperior Palpatine telling you to "release your anger" when you're balls deeps in his wrinkled, leathery arse`,
			`Emperor Palpatine`,
			`Emperor Palpatine's colostomy bag`,
			`employing Luminara Unduli as a fluffer`,
			`endless animated TV spin offs`,
			`entombing your personal whore in carbonite`,
			`everyone finally kissing and making up`,
			`Ewok jerky`,
			`Ewok tossing`,
			`excessively force flipping during every fight scene`,
			`Exposing yourself outside of a school of Jedi Younglings`,
			`faking an orgasm`,
			`Faro Argyus`,
			`farting in your Starfighter`,
			`fat shaming a Gamorrean guard`,
			`feeding unruly servants to your pets`,
			`feeding your pet monster`,
			`fermenting cheese in Jabba’s stomach rolls`,
			`finding skid marks in Leia's metal bikini`,
			`finding the "Death Star plans" on Google`,
			`finding Yoda's porn collection stored in R2D2's memory bank`,
			`fingering the anal passage of an Ewok with constipation`,
			`Finn and some casual racism`,
			`Finn being beaten when in captivity because, well, you know…`,
			`Finn; the token black charcater`,
			`Finn's big black cock`,
			`firing Nien Numb out of a canon`,
			`firing Porgs from a BWing’s bombing compartment`,
			`first world problems`,
			`flirting with your enemies while trying to kill them`,
			`force mastrubation`,
			`freezing your balls off on Hoth`,
			`frolicking in the hay with Snoke`,
			`fucking Darth Vader's daughter`,
			`fucking Padme's still warm corpse`,
			`fucking the hole in Greedo’s half blown off head`,
			`galactic paternity tests`,
			`General Grevious`,
			`General Grevious’s long lost Marlboro advert`,
			`General Grievous and his highly marketable cough medicine`,
			`General Hux and Kylo ren are playing a game of soggy biscuits`,
			`General Hux's Nazi-esque uniform`,
			`General Hux’s ginger pubes`,
			`genetically engineered Bantha’s with acidic urine`,
			`Geonosis freezing over`,
			`George Lucas`,
			`George Lucas' new edits of the movies`,
			`getting a cleaning orgasm from a Vibromop`,
			`getting a Han job`,
			`getting a hard on when the Star Wars fanfare plays`,
			`getting an erection in a stormtrooper suit`,
			`getting anally probed by Kylo Ren`,
			`getting aroused by the total destruction of Alderaan`,
			`getting fingered by Emperor Palpatine's electric fingers`,
			`getting force choked and enjoying it`,
			`getting high with Han Solo’s latest shipment`,
			`getting kiddy fiddled by a jedi priest`,
			`getting sand in all your cracks on Tatooine`,
			`getting vaginal burns from your lightsaber`,
			`getting wasted on Corellian Ale`,
			`getting white girl wasted`,
			`giving birth to a Wookiee`,
			`giving Finn a sympathy fuck`,
			`giving into your anger`,
			`giving Wedge Antilles a massive Wedgie`,
			`Glass Mandalore`,
			`going for a job interview naked to show your uniqueness`,
			`Going on a long and complicated side plot that nobody understands`,
			`going the opposite direction to Kylo Ren`,
			`googling Star Wars characters`,
			`gouging out Wicket's Big Brown eyes`,
			`Governor Tarkin's waxed asshole`,
			`Grand Admiral Thrawn`,
			`Grand Moff Tarkin’s sweaty pits`,
			`Greedo`,
			`Greedo actually hitting something for a fucking change`,
			`Gungan genocide`,
			`Han nailing Leia on the Millennium Falcon`,
			`Han Solo`,
			`Han Solo's blaster`,
			`Han Solo's pierced nipples`,
			`Han Solo’s brown pants`,
			`handing out free samples on Endor`,
			`Harrison Ford`,
			`having a bad feeling about something`,
			`having a quick wank before the Emperor visits`,
			`having anotimcally improbable inter-species sex`,
			`having balls the size of the Death Star`,
			`having your asshole licked by Jar Jar Bink's long, wet tongue`,
			`helping pick the food out of a Rancor’s mouth`,
			`hiding the most important person in the galaxy in his evil father's home planet`,
			`high fiving an Ewok with poo on your hand`,
			`hijacking a TIE fighter on your first date`,
			`holotape of Mace Windu naked.`,
			`human rights violations`,
			`initiating an Order 69 with princess Leia`,
			`interracial action with Finn and Rey`,
			`Irritable Bowel Syndrome`,
			`J.J. Abrams`,
			`Jabba the Hutt`,
			`Jabba the Hutt’s medical records`,
			`Jabba's excess skin after going on Weight Watchers`,
			`Jabba's skin folds`,
			`Jabba's stretch marks`,
			`Jakku's failed global warming policies`,
			`James Earl Jones`,
			`James Earl Jones narrating your life`,
			`Jar Jar Bink's amazing deep throating abilities`,
			`Jar Jar Bink's urethra shattering voice`,
			`Jar Jar Binks`,
			`Jar Jar's 3-foot long tongue`,
			`Jar Jar’s dyslexia`,
			`Jedi Knights crossing swords`,
			`juggling Porgs`,
			`Jyn Erso`,
			`Jyn Erso's vaginal queefing`,
			`Ki-Adi-Mundi and the mystery of the missing younglings`,
			`Ki-Adi-Mundi’s suspiciously gentle manner`,
			`Kicking R5-D4 in the tin cans`,
			`killing your Father with a lightsaber`,
			`killing your master in his sleep`,
			`Krennic literally choking on his aspirations`,
			`Kylo drawing a fake 6- pack on himself`,
			`Kylo Ren`,
			`Kylo Ren’s angry face`,
			`Kylo Ren’s shampoo and conditioner`,
			`Kylos's uncircumcised penis`,
			`Lando`,
			`Lando coming to clean your pool`,
			`Lando's perfect manscaping`,
			`laying Leia`,
			`learning thieving techniques from Jyn Erso`,
			`leaving Chewbacca locked in your car on a hot summers day`,
			`leaving when you find out she’s pregnant`,
			`legally changing your name to Han Solo`,
			`Leia's Incestuous relationship with senator Bail Organa`,
			`listening to jizz music while making love`,
			`listening to the rain lightly pattering on the leaves in the forest of endor`,
			`Luke Skywalker`,
			`Luke Skywalker's Penis; the original lightsaber`,
			`Luke's good hand`,
			`Luke's internet search history of sister porn`,
			`Luke’s bionic hand`,
			`Luke’s severed hand`,
			`Luminara Unduli's religiously motivated headdress`,
			`Luminara Unduli’s giant fucking ears`,
			`Mace Windu`,
			`Mace Windu finding motherfucking snakes on his starfighter`,
			`making a bong from a Dantooinian sphere fruit`,
			`making chewbacca noises during intercourse`,
			`making Degobah great again`,
			`making lightsaber sounds while wielding an actual lightsaber`,
			`making the jump to lightspeed`,
			`Mark Hamill`,
			`masquerading as a moisture farmer when you're actually dealing heroin`,
			`Max Rebo's dangly blue trunk`,
			`May the 4th`,
			`may the force be with you`,
			`Maz Kanata`,
			`Maz's Glasses`,
			`measuring a tauntaun's cock with your mouth`,
			`meeting your end in a watery grave in Tipoca City`,
			`missionaries trying to convert the Sith with surprisingly positive results`,
			`Mon Mothma`,
			`Mon Mothma’s still born child`,
			`much to learn, you have`,
			`Mynocks chewing on power cables`,
			`not being able to say no`,
			`not giving a shit about the Force`,
			`not giving chewbacca a medal`,
			`not knowing who your Father is`,
			`not letting the wookie win`,
			`Obi-Wan`,
			`Obi-Wan Kenobi's superior Jedi skills`,
			`Obi-Wan's Chest wig`,
			`Obi-Wan’s descent into Alzheimer’s`,
			`Obi-Wans suicidal tenancies`,
			`only dating boys from the dark side`,
			`Oola and Bib Fortuna getting their heads tangled up`,
			`Oola’s massive tits`,
			`ordering a Twi'lek to twerk`,
			`overanalyzing all of the Clone Wars prequels`,
			`overdosing on death sticks`,
			`overestimating the power of the dark side`,
			`Padmé Amidala`,
			`Padme Amidala’s stretchy hole`,
			`Padme talking dirty in her posh Queen voice`,
			`Padmé’s frozen ovaries`,
			`Palpatine's wrinkly old ass`,
			`Palpatine’s wrinkled balls`,
			`pew pew pew`,
			`pickled porgs`,
			`picturing your sister while masturbating`,
			`playing bongos with the helmets of stormtroopers`,
			`playing robot wars with AT-ATs`,
			`Plo Koon`,
			`ploughing Rey’s ass like a professional farmer`,
			`plucking Captain Rex’s nose hair with your teeth`,
			`Poe in a gold bikini`,
			`Poe’s chiseled features`,
			`polishing Boba Fett’s helmet`,
			`polishing C-3PO's crotch`,
			`polishing C-3PO's golden rod`,
			`poorly written Star Wars fan fiction`,
			`post traumatic stress disorder`,
			`pouring Fozbeer over Leia’s boobs`,
			`pretending R2-D2 is talking when he beeps and boops`,
			`Prince William and Prince Harry’s entitled Stormtrooper cameos`,
			`Princess Leia`,
			`Princess Leia doing anal to save the Rebel Alliance`,
			`Princess Leia's boob tape`,
			`Princess Leia’s hairy buns`,
			`punching C-3PO in the face`,
			`pushing Maz Kanata’s gallbladder back in through her ass`,
			`putting Vader in a nice sauna`,
			`putting your hood up and pretending you're a Jedi`,
			`Queen Amidala`,
			`Queen Amidala's landing strip`,
			`Queen Amidala's suprisingly deep sex noises`,
			`Qui-Gon Jinn`,
			`quoting every line in a Star Wars film`,
			`R2-D2`,
			`R2-D2 saving everyone’s ass time and time again`,
			`R2-D2 trying to get through airport security`,
			`R2-D2’s vibrate function`,
			`random erections`,
			`reading a holojournal`,
			`reading Jabba the Hut's surprisingly good poetry`,
			`removing the pubic hairs from your mouth after oral sex with Chewbacca`,
			`returning to Echo Base mid-evacuation because you forgot your porn collection`,
			`Rey`,
			`Rey and Leia in a hot tub`,
			`Rey learning to use the Force to improve her hand jobs`,
			`Rey's menstrual rage`,
			`Rey’s Magnum ice cream looking speeder`,
			`Rian Johnson’s less than creative mind`,
			`ridding the galaxy of happiness`,
			`riding a 2001 Honda Civic, high on ketamine.`,
			`roger roger`,
			`Rogue One`,
			`rolling Boss Nass down a hill`,
			`rolling the chance cubes`,
			`Salacious Crumb’s sperm`,
			`saying "live long and prosper" to a Star Wars fan`,
			`saying "no" to Gardulla the Hutt`,
			`scaling Admiral Ackbar`,
			`scalping Sebulba while he serenades you`,
			`Sebulba’s sweaty meat sack`,
			`Secks Havoc`,
			`secretly wishing Luke and Leia never found out they were twins`,
			`seeing Boba Fett without his helmet on`,
			`selling out to Disney`,
			`selling out your friends to the Empire`,
			`selling Princess Leia’s dirty underwear on the Internet`,
			`sexually transmitted diseases`,
			`sharp anal beads`,
			`shaving your balls before battle, just in case you rescue some hoes`,
			`Shmi Skywalker`,
			`singing "My Humps" with the Cantina band`,
			`sitting on Yoda’s stubby green fingers`,
			`skull fucking Count Dooku's severed head`,
			`slam dunking BB-8 into a trash compactor`,
			`slapping Obi-Wan’s ass with a paddle`,
			`slipping 4 fingers in where only 2 should go`,
			`slipping face first into Bantha poo`,
			`slowly marinating Ponda Baba’s hackedoff arm`,
			`smoking a joint with Greedo`,
			`smoking blunts with Yoda`,
			`smoking crack with R2- D2`,
			`smoking Wookiee fur as a means to improve fertility`,
			`sneaking into the Ewok village with peanut butter on your balls`,
			`sneaking past stormtropers like a boss`,
			`snorting Darth Vader's ashes`,
			`snorting the ashes of Vader's body`,
			`some gentle ass play`,
			`spear-wielding teddy bears`,
			`spraying graffiti around the City of Theed`,
			`squashing Ki-AdiMundi's head back into shape`,
			`squeezing Padmé’s blackheads`,
			`Star Wars – The Musical`,
			`Star Wars Episode IV`,
			`Star Wars Episode XI featuring Mickey Mouse`,
			`Star Wars Episode XX`,
			`Star Wars erotica`,
			`Star Whores`,
			`sticking a thumb into Qui-Gon Jinn’s eye socket`,
			`stimulating nipples with force lightning`,
			`strong female characters`,
			`sucking Darth Vader’s burnt penis`,
			`sucking the little nodules on Greedo’s head`,
			`surfing the HoloNet`,
			`Sy Snootles`,
			`Sy Snootles giving you colonic irrigation with her mouth`,
			`taking a Star Wars fan's virginity on his 45th birthday`,
			`taking antidepressants to forget the recent movies`,
			`telling the odds to Han Solo`,
			`the annual orgy in the Jedi Temple`,
			`the Attack of the Clones`,
			`the awkward moment when you wonder why Luke only trained young boys`,
			`the Battle of Endor`,
			`the Battle of Geonosis`,
			`the Battle Of Hoth`,
			`the best damn pilot in the galaxy`,
			`the biggest, blackest dick in the galaxy`,
			`the blood of a million Ewoks`,
			`the Cantina song on repeat for 10 hours`,
			`the creation of Jar Jar Binks`,
			`the darkest side of the Force`,
			`the Death Star II's massive vulnerability`,
			`the Death Star plans`,
			`the delightfully pleasing sound of an ion cannon`,
			`the Disney Fan Fiction sequel trilogy`,
			`the dryness of Maz Kanata’s vagina`,
			`the Empire deciding not to strike back`,
			`the Empire’s racial cleansing`,
			`the end of Hayden Chistensen’s career`,
			`the ET aliens in the Imperial Senate`,
			`the filth between Sebulba’s toes`,
			`the Force getting a random female pregnant`,
			`the free will of the people`,
			`the Imperial Ruling Council legalizing weed`,
			`the incompetency of General Hux`,
			`the incurable uselessness of C-3PO`,
			`the irony of a smuggler smuggling himself`,
			`the lascivious secrets of the Jedi Temple`,
			`The Last Jedi`,
			`the loveless marriage of Uncle Owen and Aunt Beru`,
			`the magic of Disney`,
			`the male dominated society of the planet Ryloth`,
			`The Millennium Falcon`,
			`the Millennium Falcon’s exhaust pipe`,
			`the Mos Eisely Spaceport`,
			`the noise a Wookie makes while ejaculating`,
			`the Original Trilogy`,
			`the perfectly toasted flesh of Uncle Owen and Aunt Beru`,
			`The Phantom Menace`,
			`the population of Alderaan`,
			`the Prequel Trilogy`,
			`The Return of the Jedi`,
			`the rotting remains of a herd of dead Nerfs`,
			`the sanctity of the Great Temple`,
			`the sexual tension between Leia and Luke`,
			`the shape of Ki-AdiMundi’s mothers’ vaginal canal`,
			`the shattered left femur of Wedge Antilles`,
			`the sky-high prices of moisture these days`,
			`the smell of photon torpedoes in the morning`,
			`the tiny clitorises on Darth Maul head`,
			`the tragedy of Darth Plagueis the Wise`,
			`the twin suns of Tatooine`,
			`the upper class part of Naboo`,
			`the wreckage of a thousand TIE fighters`,
			`thinking your crush has died`,
			`three Ewoks in a trench coat`,
			`throwing Yoda around like a puppet`,
			`Tobias Beckett`,
			`trading kyber crystals for bitcoin`,
			`travelling to Mos Eisley for cheap unprotected sex`,
			`tripping out at a lightsabers colors while high on death sticks`,
			`trying to impress a girl with material items`,
			`turning Moroff into an elegant fur coat`,
			`turning the Rebel Alliance into pancakes with AT-AT's`,
			`turning to the dark side`,
			`Uncle Owen`,
			`unprotected sex with a tauntaun`,
			`urinating in the Death Star trash compactor`,
			`using "Sith On My Face" as a pickup line`,
			`using a lightsaber to cauterize Obi-Wan's hemorrhoids`,
			`using Bantha milk as lubricant`,
			`using Jabba's drool as lubricant`,
			`using Jedi mind tricks on hot girls to turn a "No" into a "Yes"`,
			`using Jedi mind tricks to smash heaps of bitches`,
			`using Oola’s head tails as reigns as you ride her deep from behind`,
			`using R2-D2 to charge your phone`,
			`using the force to undress strangers`,
			`using your lightsaber to turn your enemies into glory holes`,
			`using your own force choke for auto-erotic asphyxiation`,
			`vomiting and shitting at the same time`,
			`walking on a bridge made out of stormtroopers`,
			`Wampa flavored ice cream`,
			`Wampas`,
			`Wat Tambor's Ass`,
			`Wat Tambor’s rusty armpit`,
			`watching a rock concert with Plo Coon`,
			`watching ballet with the Rancor keeper`,
			`waterboarding Han Solo`,
			`waxing Leila before putting her into a metal bikini`,
			`wearing Princess Leia's metal bikini to your little sisters costume party`,
			`Wedge Antilles`,
			`Wicket`,
			`Wicket poking you with his spear`,
			`Wilhuff Tarkin`,
			`winning a podrace before it became cool`,
			`wiping your ass with an Ewok`,
			`yelling "its a trap!' in public`,
			`Yoda`,
			`Yoda suffering from short man syndrome`,
			`Yoda turning to the dark side`,
			`Yoda's abnormally large penis`,
			`Yoda's questionable teaching methods`,
			`Yoda's school for levitating starships`,
			`Yoda's short man syndrome`,
			`Yoda's tiny green testicles`,
			`yoga classes with Princess Amidala`,
			`Young Anakin`,
			`Youngling forced labor camps`,
			`younglings being slaughtered at the Jedi Temple.`,
			`Zam Weesel's missing arm`,
			`Zam Weesel's Sexy human form`,
		},
	}

	AddPack(pack)
}
