package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "reject",
		Description: "Reject Packs - 1, 2, and 3",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `Bitch, you look nasty. You look disgusting. You look like you're %s. Go home, bitch.`},
			&PromptCard{Prompt: `So this family circus act comes in to see a talent agent in Hoboken, and the agent askes what they do. The father of the act jumps up and starts to furiously beat off into a towel while his wife whips her hair back and forth to that famous song - originally sung by one of Will Smith's kids, "I Whip My Hair Back And Forth" - which her twin daughters are singing while they braid each other's pubes, all while the twin BROTHERS are creating a real-estate bubble by purchasing houses and flipping them for needless profit, and all THIS is happening while the grandmother is peeing into a Smuckers jar and slapping her ass. The whole thing ends with the family spitting into each other's assholes. The talent agent can't believe it. He looks at the sweaty father who has just spit into his mother's asshole and says. "WOW. This is great. Whaddya call yourselves?" And the guy looks at him and says, "We're %s."`},
			&PromptCard{Prompt: `From WBEZ Chicago, it's This American Life. Today on our program, %s. Stay with us.`},
			&PromptCard{Prompt: `My name is Inigo Montoya. You killed my father. Prepare for %s.`},
			&PromptCard{Prompt: `Sir, we found you passed out naked on the side of the road. What's the last thing you remember? %s`},
			&PromptCard{Prompt: `The elders of the Ibo tribe of Nigeria recommend %s as a cure for impotence.`},
			&PromptCard{Prompt: `The Westboro Baptist Church is now picketing soldiers' funerals with signs that read 'GOD HATES %s!'`},
			&PromptCard{Prompt: `What are two cards in your hand that you want to get rid of? %s and %s`},
			&PromptCard{Prompt: `You can't wait forever. It's time to talk to your doctor about %s.`},
			&PromptCard{Prompt: `Astronomers have discovered that the universe consists of 5 percent ordinary matter, 25 percent dark matter, and 70 percent %s.`},
			&PromptCard{Prompt: `BowWOW! is the first pet hotel in LA that offers %s for dogs.`},
			&PromptCard{Prompt: `Hey, whatever happened to Renee Zellweger? %s`},
			&PromptCard{Prompt: `Housekeeping! You want %s?`},
			&PromptCard{Prompt: `In bourgeois society, capital is independent and has individuality, while the living person is %s.`},
			&PromptCard{Prompt: `Some men aren't looking for anything logical, like money. They can't be bought, bullied, reasoned or negotiated with. Some men just want %s.`},
			&PromptCard{Prompt: `What's wrong with these gorillas? %s`},
			&PromptCard{Prompt: `Why did the chicken cross the road? %s`},
			&PromptCard{Prompt: `You say tomato, I say %s.`},
			&PromptCard{Prompt: `America is hungry. America needs %s.`},
		},
		Responses: []ResponseCard{
			`A child's love of sticks`,
			`A man two times the size of a man half his size`,
			`Abandoning all concepts and categories and seeing the world as it truly is`,
			`Abort-tron, the abortion robot`,
			`Achieving total fitness and turning into a mental cube`,
			`Being blind but having super strength but having Alzheimer's Disease by being invisible`,
			`Collapsing into singularity. Twenty minutes fo foreplay, three minutes of coitus, five minutes of rest, back to the yards for some croquet`,
			`Computers`,
			`Cum, but it's ranch`,
			`Fashion… heard of if?`,
			`Getting my mind boggled by a gang of mind bogglers`,
			`Letting these hoes know`,
			`Meatballs, meatballs, meatballs!`,
			`Passing fart and making toilet`,
			`Running afoul of the Sultan's Janissaries`,
			`Sheboygan, Wisconsin`,
			`Struggling to swallow a live bat`,
			`Taking off my glasses and becoming beautiful`,
			`The tiny man who lives inside the ATM and hands out all the money`,
			`The tiny man who only eats coffee beans and diarrheas into my thermos every morning`,
			`Using electric eels to solve the world's energy crisis`,
			`Why, a hot air balloon of course!`,
			`You there! French boy!`,
			`A dick so big and so black that not even light can escape its pull`,
			`A double murder suicide barbeque`,
			`A primordial soup and salad bar`,
			`A stack of bunnies in a trenchcoat`,
			`At least three ducks`,
			`Becoming engorged with social justice jelly and secreting a thinkpiece`,
			`Being the absolute worst`,
			`Disco Mussolini`,
			`Greg Kinnear's terrible lightning breath`,
			`Mitt Romney's eight sons Kip, Sam, Trot, Fergis, Toolshed, Grisham, Hawkeye, and Thorp`,
			`Mr. and Mrs. Tambourine Man's jingle-jangle morning sex`,
			`Mushy tushy`,
			`Ringo Starr & His All-Starr Band`,
			`Sandwich`,
			`Saving the Rainforest Cafe`,
			`Sir Thomas More's Fruitopia™`,
			`Sweating it out on the streets of a runaway American Dream`,
			`That one leftover screw`,
			`That thing politicians do with their thumbs when they talk`,
			`The spooky skeleton under my skin`,
			`The token lesbian`,
			`These dolphins`,
			`Three hairs from the silver-golden head of Galadriel`,
			`Water so cold it turned into a rock`,
			`A giant squid in a wedding gown`,
			`A heart that is two sizes too small and that therefore cannot pump an adequate amount of blood`,
			`A sexy naked interactive theater thing`,
			`Asshole pomegranates that are hard to eat`,
			`Becoming so rich that you shed your body and turn to vapor`,
			`Carribbean Jesus`,
			`Corn`,
			`Crawling into a vagina`,
			`Dividing by zero`,
			`Ejaculating a pound of tinsel`,
			`Faking a jellyfish sting so someone will pee on you`,
			`Ladles`,
			`My dick in your mouth`,
			`Playing an ocarina to summon Ultra-Congress from the sea`,
			`Super yoga`,
			`The John D. and Catherine T. MacArthur Foundation`,
			`%blank`,
		},
	}

	AddPack(pack)
}
