package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "sanity",
		Description: "Cards against our sanity: volume one",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s should never be allowed in a convention.`},
			&PromptCard{Prompt: `%s, now happening at a convention near you!`},
			&PromptCard{Prompt: `%s. Worst Decision I've ever made.`},
			&PromptCard{Prompt: `%s. An experience I‘ll never forget.`},
			&PromptCard{Prompt: `%s sucks some major dick.`},
			&PromptCard{Prompt: `After last year, the con got an ambulance on standby in case %s happened again.`},
			&PromptCard{Prompt: `Attention all guests: We regret to inform you that the game room will be closed for the rest of the convention due to %s.`},
			&PromptCard{Prompt: `At the con I decided that %s was a good idea. Go me.`},
			&PromptCard{Prompt: `Come place your bets, ladies and gentlemen! %s vs. %s. Who will win?`},
			&PromptCard{Prompt: `Follow me at: %s.tumblr.com`},
			&PromptCard{Prompt: `I got a refund when my favorite voice actor’s panel was canceled for a three-hour seminar on %s.`},
			&PromptCard{Prompt: `I won the cosplay contest because I had (a) %s.`},
			&PromptCard{Prompt: `If you see %s, say nothing and drink to forget.`},
			&PromptCard{Prompt: `My entire convention weekend was ruined by %s.`},
			&PromptCard{Prompt: `Next year’s main panel: %s, Confessions of a Life-Long Con Owner.`},
			&PromptCard{Prompt: `One day when I have kids, I’ll be able to sit them all down and tell them the story of %s.`},
			&PromptCard{Prompt: `Please go like my page “%s Cosplay”. It’s got almost 100 followers!`},
			&PromptCard{Prompt: `Scott McNeil said he wouldn't show up to another convention if %s were there.`},
			&PromptCard{Prompt: `Screw the rules! I have %s!`},
			&PromptCard{Prompt: `There are conventions themed around gaming, anime, and comic books. But you wouldn't believe what the next convention’s theme is…`},
			&PromptCard{Prompt: `What did I forget to pack for this convention?`},
			&PromptCard{Prompt: `What do you mean they ran out of %s? This after-party sucks!`},
			&PromptCard{Prompt: `What the fuck is wrong with my life?`},
			&PromptCard{Prompt: `When I witnessed someone %s this morning, I knew it wouldn’t be your average con.`},
			&PromptCard{Prompt: `You can't say you've had the full convention experience until you’ve seen %s and %s .`},
		},

		Responses: []ResponseCard{
			`A body pillow that’s been used so may times, it stands up on its own`,
			`A con stage show that the cast put their heart and soul and months of work into, only to get 2 hours to perform to an audience of around 25 people`,
			`A Cosplay Elitist`,
			`A girl that just actually really doesn’t like you`,
			`A parent chaperoning their child not quite knowing what to think about all of this`,
			`A small spin-off con that fails`,
			`A wardrobe malfunction`,
			`A Yiff Party!`,
			`Accidentally breaking a piece of your prop and calling it battle damage`,
			`Actual, real katana duels between trained professionals with deadly weapons... and you’re pretty sure you can take them both at the same time`,
			`Alcohol`,
			`An outfit that you spend hundreds of dollars and weeks of work on, only to wear it for a couple of hours`,
			`Anime crap`,
			`Assuming all girls who go to high school are over 18`,
			`Attention whores`,
			`Being Murdered`,
			`Being offended by literally nothing`,
			`Being pretty fuckin’ desperate`,
			`Being too old for this shit`,
			`Bishounen Hitler`,
			`Blowjobs`,
			`Broken Dreams`,
			`Burlesque shows. Like pole dancing — but classier`,
			`Con drama`,
			`Cosplayers`,
			`Cosplaying something obscure, and then getting mad when nobody recognizes you`,
			`Creepy photographers`,
			`Crippling depression`,
			`Crossplay`,
			`Dead Memes`,
			`Deadpool Cosplayers`,
			`Delicious Dark Side Cookies`,
			`Depressing cafe maids`,
			`Donald Trump`,
			`Dropping out of school and quitting your job to go become a professional cosplayer`,
			`Existing`,
			`Explaining your cosplay to polite but noticeably uncomfortable tourists`,
			`Floating in the Dead Sea, eating McDonald’s French fries, and being the saltiest bitch there is`,
			`Furries`,
			`Getting the con crud`,
			`Getting herpes from the Pocky Game`,
			`Getting high off of life! ( and a bit of crack cocaine)`,
			`Glorious Butts`,
			`Having an epileptic seizure at the con rave`,
			`Having to Google it`,
			`Hentai`,
			`Hookers & Blow`,
			`Indisputable scientific evidence that running like a ninja makes you faster`,
			`Introducing your parents to your body pillow girlfriend`,
			`It was me, Dio!`,
			`Just Batman`,
			`Making Cons Great Again`,
			`Nina Tucker, American Kennel Club winner for Mixed Breed`,
			`Non Consensual Glomping`,
			`Not breaking character until you are getting arrested`,
			`Not checking in your ”totally fake gun.”`,
			`Not eating anything all day, and when you feel like you are about to faint, you eat a cube of cheese`,
			`Not sealing your body paint`,
			`Overpriced food`,
			`Passing out`,
			`Picking up chicks at a con`,
			`Praying the gay away`,
			`Pretty boys`,
			`Pretty girls way out of your league`,
			`Putting minimal effort into cosplay by wearing costumes bought from Walmart`,
			`Religious protesters`,
			`Renting a convention center, hiring staff, and booking celebrities, only for the con owner to steal the budget and run away to another state`,
			`Seeing an obese rendition of your favorite character and being scarred for life`,
			`seeing someone cosplay a spoiler that came out a week ago`,
			`Selling your car for gas money`,
			`Sharing the convention center with another event`,
			`Shitty Cards Against Humanity Spin-offs`,
			`Shitty Chinese Knockoffs`,
			`Someone spiking the water coolers`,
			`Someone taking a shit in the elevator`,
			`Special Snowflakes`,
			`Steve Blum’s sultry, omnipresent voice`,
			`Stupid dumb fucking nerds`,
			`Swimming drunk in the hotel fountain because the pool was closed`,
			`Switchblades pulled out at the Smash tournament`,
			`That guy dancing around with the boombox`,
			`The ballpit didn’t have any balls and I broke my ass jumping in`,
			`That one girl who dances to J-Pop in the corner for attention`,
			`The sexiest sex to ever sex`,
			`Treating your hotel room like a clown car and shoving as many people as you can in there`,
			`Trespassing to get the prefect photoshoot location`,
			`Trying to become famous`,
			`Trying to flee that old drunk pervert staying at your hotel`,
			`Using Febreeze as deodorant`,
			`Vic Mignognanananana`,
			`Yaoi`,
			`Your Cosplay Squad`,
			`Your mom`,
			`Your old racist father`,
			`Your sweet innocent virgin soul`,
			`YouTube Let's Players`,
			`%blank`,
		},
	}

	AddPack(pack)
}
