package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "main",
		Description: "Base card deck",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s + %s = %s.`},
			&PromptCard{Prompt: `%s is a slippery slope that leads to %s.`},
			&PromptCard{Prompt: `%s would be woefully incomplete without %s.`},
			&PromptCard{Prompt: `%s: good to the last drop.`},
			&PromptCard{Prompt: `%s: kid-tested, mother-approved.`},
			&PromptCard{Prompt: `%s: Once you pop, the fun don't stop!`},
			&PromptCard{Prompt: `%s? Jim'll fix it!`},
			&PromptCard{Prompt: `%s? There's an app for that.`},
			&PromptCard{Prompt: `%s? Yeah, nah.`},
			&PromptCard{Prompt: `%s. Awesome in theory, kind of a mess in practice.`},
			&PromptCard{Prompt: `%s. Betcha can't have just one!`},
			&PromptCard{Prompt: `%s. High five, bro.`},
			&PromptCard{Prompt: `%s. It's a trap!`},
			&PromptCard{Prompt: `%s. That was so metal.`},
			&PromptCard{Prompt: `%s. That's how I want to die.`},
			&PromptCard{Prompt: `%s. That's why mums go to Iceland.`},
			&PromptCard{Prompt: `★✰✰✰✰ Do NOT go here! Found %s in my Kung Pao chicken! `},
			&PromptCard{Prompt: `50%% of all marriages end in %s.`},
			&PromptCard{Prompt: `A recent laboratory study shows that undergraduates have 50%% less sex after being exposed to %s.`},
			&PromptCard{Prompt: `A remarkable new study has shown that chimps have evolved their own primitive version of %s.`},
			&PromptCard{Prompt: `A romantic, candlelit dinner would be incomplete without %s.`},
			&PromptCard{Prompt: `A successful job interview begins with a firm handshake and ends with %s.`},
			&PromptCard{Prompt: `ABC presents: "%s: The Story of %s."`},
			&PromptCard{Prompt: `After eight years in the White House, how is Obama finally letting loose? %s`},
			&PromptCard{Prompt: `After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: %s.`},
			&PromptCard{Prompt: `After Hurricane Katrina, Sean Penn brought %s to all the people of New Orleans.`},
			&PromptCard{Prompt: `After months of practice with %s, I think I’m finally ready for %s.`},
			&PromptCard{Prompt: `After the earthquake, Sean Penn brought %s to the people of Haiti.`},
			&PromptCard{Prompt: `Air Canada guidelines now prohibit %s on airplanes.`},
			&PromptCard{Prompt: `Airport security guidelines now prohibit %s on airplanes.`},
			&PromptCard{Prompt: `Alternative medicine is now embracing the curative powers of %s.`},
			&PromptCard{Prompt: `And the Academy Award for %s goes to %s.`},
			&PromptCard{Prompt: `And the BAFTA for %s goes to %s. `},
			&PromptCard{Prompt: `And what did you bring for show and tell? %s`},
			&PromptCard{Prompt: `Anthropologists have recently discovered a primitive tribe that worships %s.`},
			&PromptCard{Prompt: `Arby's: We Have %s.`},
			&PromptCard{Prompt: `"Are you thinking what I'm thinking, B1? I think I am, B2: it's %s time!"`},
			&PromptCard{Prompt: `As my New Year's resolution, I vow to give up %s.`},
			&PromptCard{Prompt: `As the mum of five rambunctious boys, I'm no stranger to %s.`},
			&PromptCard{Prompt: `Betcha can't have just one! %s`},
			&PromptCard{Prompt: `BILLY MAYS HERE FOR %s.`},
			&PromptCard{Prompt: `Bravo's new reality show features eight washed-up celebrities living with %s.`},
			&PromptCard{Prompt: `Brought to you by Bud Light®, the Official Beer of %s.`},
			&PromptCard{Prompt: `But before I kill you, Mr. Bond, I must show you %s.`},
			&PromptCard{Prompt: `CBC presents "%s: the Story of %s."`},
			&PromptCard{Prompt: `Channel 4 presents %s, the story of %s.`},
			&PromptCard{Prompt: `Channel 5's new reality show features eight washed-up celebrities living with %s.`},
			&PromptCard{Prompt: `Channel 9 is pleased to present its new variety show, "Hey Hey It's %s."`},
			&PromptCard{Prompt: `Charades was ruined for me forever when my mom had to act out %s.`},
			&PromptCard{Prompt: `Check me out, yo! I call this dance move "%s."`},
			&PromptCard{Prompt: `Click Here for %s!!!`},
			&PromptCard{Prompt: `Coming this season, Samuel Beckett's classic existential play: Waiting for %s.`},
			&PromptCard{Prompt: `Coming to Broadway this season, %s: The Musical.`},
			&PromptCard{Prompt: `Crikey! I've never seen %s like this before! Let's get a bit closer.`},
			&PromptCard{Prompt: `CTV presents "%s: the Story of %s."`},
			&PromptCard{Prompt: `Daddy, why is mummy crying? %s`},
			&PromptCard{Prompt: `Dear Abby, I'm having some trouble with %s and would like your advice.`},
			&PromptCard{Prompt: `Dear Agony Aunt, I'm having some trouble with %s and I need your advice.`},
			&PromptCard{Prompt: `Dear Sir or Madam, We regret to inform you that the Office of %s has denied your request for %s.`},
			&PromptCard{Prompt: `Doctor, you've gone too far! The human body wasn't meant to withstand that amount of %s!`},
			&PromptCard{Prompt: `Dude, do not go in that bathroom. There's %s in there.`},
			&PromptCard{Prompt: `Due to a PR fiasco, Walmart no longer offers %s.`},
			&PromptCard{Prompt: `During his childhood, Salvador Dali produced hundreds of paintings of %s.`},
			&PromptCard{Prompt: `During his midlife crisis, my dad got really into %s.`},
			&PromptCard{Prompt: `During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of %s.`},
			&PromptCard{Prompt: `During sex, I like to think about %s.`},
			&PromptCard{Prompt: `Finally! A service that delivers %s right to your door.`},
			&PromptCard{Prompt: `For my next trick, I will pull %s out of %s.`},
			&PromptCard{Prompt: `Fun tip! When your man asks you to go down on him, try surprising him with %s instead.`},
			&PromptCard{Prompt: `Future historians will agree that %s marked the beginning of America's decline.`},
			&PromptCard{Prompt: `Having problems with %s? Try %s!`},
			&PromptCard{Prompt: `"Here is the church, Here is the steeple, Open the doors and there is %s."`},
			&PromptCard{Prompt: `Hey guys, welcome to TGIF! Would you like to start the night off right with %s?`},
			&PromptCard{Prompt: `Hey Reddit! I'm %s. Ask me anything.`},
			&PromptCard{Prompt: `How am I maintaining my relationship status? %s`},
			&PromptCard{Prompt: `How did I lose my virginity? %s`},
			&PromptCard{Prompt: `I do not know with what weapons World War III will be fought, but World War IV will be fought with %s.`},
			&PromptCard{Prompt: `I drink to forget %s.`},
			&PromptCard{Prompt: `I get by with a little help from %s.`},
			&PromptCard{Prompt: `I got 99 problems but %s ain't one.`},
			&PromptCard{Prompt: `I know when that hotline bling, that can only mean one thing: %s.`},
			&PromptCard{Prompt: `I learned the hard way that you can't cheer up a grieving friend with %s.`},
			&PromptCard{Prompt: `I never truly understood %s until I encountered %s.`},
			&PromptCard{Prompt: `I spent my whole life working toward %s, only to have it ruined by %s.`},
			&PromptCard{Prompt: `I wish I hadn't lost the instruction manual for %s.`},
			&PromptCard{Prompt: `I'm going on a cleanse this week. Nothing but kale juice and %s.`},
			&PromptCard{Prompt: `I'm Lebron James, and when I'm not slamming dunks, I love %s.`},
			&PromptCard{Prompt: `I'm no doctor, but I'm pretty sure what you're suffering from is called "%s."`},
			&PromptCard{Prompt: `I'm sorry, Professor, but I couldn't complete my homework because of %s.`},
			&PromptCard{Prompt: `I'm sorry, Sir, but I couldn't complete my homework because of %s.`},
			&PromptCard{Prompt: `I’m not like the rest of you. I’m too rich and busy for %s.`},
			&PromptCard{Prompt: `If you can't be with the one you love, love %s.`},
			&PromptCard{Prompt: `IF you like %s, YOU MIGHT BE A REDNECK.`},
			&PromptCard{Prompt: `In 1,000 years, when paper money is but a distant memory, %s will be our currency.`},
			&PromptCard{Prompt: `In a world ravaged by %s, our only solace is %s.`},
			&PromptCard{Prompt: `In Australia, %s is twice as big and twice as deadly.`},
			&PromptCard{Prompt: `In Belmarsh Prison, word is you can trade 200 cigarettes for %s.`},
			&PromptCard{Prompt: `In her latest feature-length film, Tracy Beaker struggles with %s for the first time.`},
			&PromptCard{Prompt: `In his new self-produced album, Kanye West raps over the sounds of %s.`},
			&PromptCard{Prompt: `In his new summer comedy, Rob Schneider is %s trapped in the body of %s.`},
			&PromptCard{Prompt: `In L.A. County Jail, word is you can trade 200 cigarettes for %s.`},
			&PromptCard{Prompt: `In M. Night Shyamalan's new movie, Bruce Willis discovers that %s had really been %s all along.`},
			&PromptCard{Prompt: `In Michael Jackson's final moments, he thought about %s.`},
			&PromptCard{Prompt: `In Rome, there are whisperings that the Vatican has a secret room devoted to %s.`},
			&PromptCard{Prompt: `In the new Disney Channel Original Movie, Hannah Montana struggles with %s for the first time.`},
			&PromptCard{Prompt: `In the seventh circle of Hell, sinners must endure %s for all eternity.`},
			&PromptCard{Prompt: `In Wormwood Scrubs, word is you can trade 200 cigarettes for %s.`},
			&PromptCard{Prompt: `Instead of coal, Santa now gives the bad children %s.`},
			&PromptCard{Prompt: `Introducing the amazing superhero/sidekick duo! It's %s and %s!`},
			&PromptCard{Prompt: `Introducing X-Treme Baseball! It's like baseball, but with %s!`},
			&PromptCard{Prompt: `It's a trap!`},
			&PromptCard{Prompt: `It’s a pity that kids these days are all getting involved with %s.`},
			&PromptCard{Prompt: `Just once, I'd like to hear you say "Thanks, Mom. Thanks for %s."`},
			&PromptCard{Prompt: `Just saw this upsetting video! Please retweet!! #stop%s`},
			&PromptCard{Prompt: `Kids, I don't need drugs to get high. I'm high on %s.`},
			&PromptCard{Prompt: `Life for Aboriginal people was forever changed when the white man introduced them to %s.`},
			&PromptCard{Prompt: `Life for American Indians was forever changed when the White Man introduced them to %s.`},
			&PromptCard{Prompt: `Life was difficult for cavemen before %s.`},
			&PromptCard{Prompt: `Lifetime® presents "%s: the Story of %s."`},
			&PromptCard{Prompt: `Lovin’ you is easy ’cause you’re %s.`},
			&PromptCard{Prompt: `Major League Baseball has banned %s for giving players an unfair advantage.`},
			&PromptCard{Prompt: `Make a haiku.`},
			&PromptCard{Prompt: `Mate, do not go in that toilet. There's %s in there.`},
			&PromptCard{Prompt: `Maybe she's born with it. Maybe it's %s.`},
			&PromptCard{Prompt: `Men's Wearhouse: You're gonna like %s. I guarantee it.`},
			&PromptCard{Prompt: `Military historians remember Alexander the Great for his brilliant use of %s against the Persians.`},
			&PromptCard{Prompt: `Money can’t buy me love, but it can buy me %s.`},
			&PromptCard{Prompt: `Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is %s?`},
			&PromptCard{Prompt: `MTV's new reality show features eight washed-up celebrities living with %s.`},
			&PromptCard{Prompt: `My fellow Americans: Before this decade is out, we will have %s on the moon!`},
			&PromptCard{Prompt: `My mom freaked out when she looked at my browser history and found %s.com/%s.`},
			&PromptCard{Prompt: `My plan for world domination begins with %s.`},
			&PromptCard{Prompt: `Next from J.K. Rowling: Harry Potter and the Chamber of %s.`},
			&PromptCard{Prompt: `Next on ESPN2: The World Series of %s.`},
			&PromptCard{Prompt: `Next up on Channel 4: Ramsay's %s Nightmares.`},
			&PromptCard{Prompt: `Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and %s.`},
			&PromptCard{Prompt: `Now at the Natural History Museum: an interactive exhibit on %s.`},
			&PromptCard{Prompt: `O Canada, we stand on guard for %s.`},
			&PromptCard{Prompt: `Oi! Show us %s!`},
			&PromptCard{Prompt: `Old MacDonald had %s. E-I-E-I-O.`},
			&PromptCard{Prompt: `Only two things in life are certain: death and %s.`},
			&PromptCard{Prompt: `Penalty! %s: that's 5 minutes in the box!`},
			&PromptCard{Prompt: `Qantas now prohibits %s on airplanes.`},
			&PromptCard{Prompt: `Rumor has it that Vladimir Putin's favorite dish is %s stuffed with %s.`},
			&PromptCard{Prompt: `Science will never explain %s.`},
			&PromptCard{Prompt: `Skidamarink a dink a dink, skidamarink a doo, I love %s.`},
			&PromptCard{Prompt: `Sorry everyone, I just %s.`},
			&PromptCard{Prompt: `"Step 1: %s. Step 2: %s. Step 3: Profit."`},
			&PromptCard{Prompt: `Studies show that lab rats navigate mazes 50%% faster after being exposed to %s.`},
			&PromptCard{Prompt: `TFL apologizes for the delay in train service due to %s.`},
			&PromptCard{Prompt: `That's right, I killed %s. How, you ask? %s.`},
			&PromptCard{Prompt: `The blind date was going horribly until we discovered our shared interest in %s.`},
			&PromptCard{Prompt: `The class field trip was completely ruined by %s.`},
			&PromptCard{Prompt: `The Five Stages of Grief: denial, anger, bargaining, %s, acceptance.`},
			&PromptCard{Prompt: `The healing process began when I joined a support group for victims of %s.`},
			&PromptCard{Prompt: `The new Chevy Tahoe. With the power and space to take %s everywhere you go.`},
			&PromptCard{Prompt: `The school excursion was completely ruined by %s.`},
			&PromptCard{Prompt: `The school field trip was completely ruined by %s.`},
			&PromptCard{Prompt: `The school trip was completely ruined by %s.`},
			&PromptCard{Prompt: `The secret to a lasting marriage is communication, communication, and %s.`},
			&PromptCard{Prompt: `The TFL apologizes for the delay in train service due to %s. `},
			&PromptCard{Prompt: `The theme for next year's Eurovision Song Contest is "We are %s."`},
			&PromptCard{Prompt: `The U.S. has begun airdropping %s to the children of Afghanistan.`},
			&PromptCard{Prompt: `They said we were crazy. They said we couldn't put %s inside of %s. They were wrong.`},
			&PromptCard{Prompt: `"This is the way the world ends. Not with a bang but with %s."`},
			&PromptCard{Prompt: `This is your captain speaking. Fasten your seatbelts and prepare for %s.`},
			&PromptCard{Prompt: `This season at the Sydney Opera House, Samuel Beckett's classic existential play: Waiting for %s.`},
			&PromptCard{Prompt: `Today on Jerry Springer: "Help! My son is %s!"`},
			&PromptCard{Prompt: `Tonight's top story: What you don't know about %s could kill you.`},
			&PromptCard{Prompt: `TSA guidelines now prohibit %s on airplanes.`},
			&PromptCard{Prompt: `Turns out that %s-Man was neither the hero we needed nor wanted.`},
			&PromptCard{Prompt: `Uh, hey guys, I know this was my idea, but I'm having serious doubts about %s.`},
			&PromptCard{Prompt: `UKIP: Putting %s First!`},
			&PromptCard{Prompt: `War! What is it good for?`},
			&PromptCard{Prompt: `Well if you'll excuse me, gentlemen, I have a date with %s.`},
			&PromptCard{Prompt: `What am I giving up for Lent?`},
			&PromptCard{Prompt: `What are my parents hiding from me?`},
			&PromptCard{Prompt: `What are school administrators using to curb rampant teenage pregnancy?`},
			&PromptCard{Prompt: `What broke up the original Wiggles?`},
			&PromptCard{Prompt: `What brought the orgy to a grinding halt?`},
			&PromptCard{Prompt: `What did I bring back from Amsterdam?`},
			&PromptCard{Prompt: `What did I bring back from Bali?`},
			&PromptCard{Prompt: `What did I bring back from Mexico?`},
			&PromptCard{Prompt: `What did the US airdrop to the children of Afghanistan?`},
			&PromptCard{Prompt: `What did Vin Diesel eat for dinner?`},
			&PromptCard{Prompt: `What do old people smell like?`},
			&PromptCard{Prompt: `What does Dick Cheney prefer?`},
			&PromptCard{Prompt: `What don't you want to find in your Chinese food?`},
			&PromptCard{Prompt: `What don't you want to find in your doner kebab?`},
			&PromptCard{Prompt: `What don't you want to find in your Kung Pao chicken?`},
			&PromptCard{Prompt: `What don't you want to find in your Mongolian beef?`},
			&PromptCard{Prompt: `What ended my last relationship?`},
			&PromptCard{Prompt: `What gets better with age?`},
			&PromptCard{Prompt: `What gives me uncontrollable gas?`},
			&PromptCard{Prompt: `What has been making life difficult at the nudist colony?`},
			&PromptCard{Prompt: `What helps Barack Obama unwind?`},
			&PromptCard{Prompt: `What helps Obama unwind?`},
			&PromptCard{Prompt: `What is Batman's guilty pleasure?`},
			&PromptCard{Prompt: `What is George W. Bush thinking about right now?`},
			&PromptCard{Prompt: `What kept Margaret Thatcher busy in her waning years?`},
			&PromptCard{Prompt: `What left this stain on my couch?`},
			&PromptCard{Prompt: `What made my first kiss so awkward?`},
			&PromptCard{Prompt: `What makes life worth living?`},
			&PromptCard{Prompt: `What makes me a true blue Aussie?`},
			&PromptCard{Prompt: `What never fails to liven up the party?`},
			&PromptCard{Prompt: `What will always get you laid?`},
			&PromptCard{Prompt: `What will I bring back in time to convince people that I am a powerful wizard?`},
			&PromptCard{Prompt: `What would grandma find disturbing, yet oddly charming?`},
			&PromptCard{Prompt: `What's a girl's best friend?`},
			&PromptCard{Prompt: `What's my anti-drug?`},
			&PromptCard{Prompt: `What's my secret power?`},
			&PromptCard{Prompt: `What's Teach for America using to inspire inner city students to succeed?`},
			&PromptCard{Prompt: `What's that smell?`},
			&PromptCard{Prompt: `What's that sound?`},
			&PromptCard{Prompt: `What's the Canadian government using to inspire rural students to succeed?`},
			&PromptCard{Prompt: `What's the crustiest?`},
			&PromptCard{Prompt: `What's the most emo?`},
			&PromptCard{Prompt: `What's the new fad diet?`},
			&PromptCard{Prompt: `What's the next Happy Meal® toy?`},
			&PromptCard{Prompt: `What's there a ton of in heaven?`},
			&PromptCard{Prompt: `What's there a tonne of in heaven?`},
			&PromptCard{Prompt: `When all else fails, I can always masturbate to %s.`},
			&PromptCard{Prompt: `When I am a billionare, I shall erect a 20-meter (65 foot) statue to commemorate %s.`},
			&PromptCard{Prompt: `When I am President, I will create the Department of %s.`},
			&PromptCard{Prompt: `When I pooped, what came out of my butt?`},
			&PromptCard{Prompt: `When I was tripping on acid, %s turned into %s.`},
			&PromptCard{Prompt: `When I'm in prison, I'll have %s smuggled in.`},
			&PromptCard{Prompt: `When Pharaoh remained unmoved, Moses called down a Plague of %s.`},
			&PromptCard{Prompt: `When you get right down to it, %s is just %s.`},
			&PromptCard{Prompt: `While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on %s.`},
			&PromptCard{Prompt: `White people like %s.`},
			&PromptCard{Prompt: `Who stole the cookies from the cookie jar?`},
			&PromptCard{Prompt: `Why am I sticky?`},
			&PromptCard{Prompt: `Why can't I sleep at night?`},
			&PromptCard{Prompt: `Why do I hurt all over?`},
			&PromptCard{Prompt: `With enough time and pressure, %s will turn into %s.`},
			&PromptCard{Prompt: `Your persistence is admirable, my dear Prince. But you cannot win my heart with %s alone.`},
		},
		Responses: []ResponseCard{
			`"Tweeting"`,
			`(I am doing Kegels right now)`,
			`10,000 Syrian refugees`,
			`100% Pure New Zealand`,
			`2 Girls 1 Cup`,
			`400 years of colonial atrocities`,
			`50 mg of Zoloft daily`,
			`50,000 volts straight to the nipples`,
			`72 virgins`,
			`8 oz. of sweet Mexican black-tar heroin`,
			`A bag of magic beans`,
			`A balanced breakfast`,
			`A ball of earwax, semen, and toenail clippings`,
			`A big black dick`,
			`A big hoopla about nothing`,
			`A bird that shits human turds`,
			`A bit of slap and tickle`,
			`A bitch slap`,
			`A bleached asshole`,
			`A Bop It™`,
			`A bowl of mayonnaise and human teeth`,
			`A brain tumor`,
			`A bucket of fish heads`,
			`A can of whoop-ass`,
			`A caress of the inner thigh`,
			`A cartoon camel enjoying the smooth, refreshing taste of a cigarette`,
			`A cat video so cute that your eyes roll back and your spine slides out of your anus`,
			`A Chelsea smile`,
			`A Chinese tourist who wants something very badly but cannot communicate it`,
			`A clandestine butt scratch`,
			`A cooler full of organs`,
			`A cop who is also a dog`,
			`A crucifixion`,
			`A cute, fuzzy koala, but it has chlamydia`,
			`A death ray`,
			`A decent fucking Internet connection`,
			`A defective condom`,
			`A despondent Maple Leafs fan sitting all alone`,
			`A didgeridildo`,
			`A disappointing birthday party`,
			`A drive-by shooting`,
			`A fair go`,
			`A falcon with a cap on its head`,
			`A fanny fart`,
			`A fart so powerful that it wakes the giants from their thousand-year slumber`,
			`A fat bald man from the internet`,
			`A fetus`,
			`A five-litre goon bag`,
			`A Fleshlight®`,
			`A foetus`,
			`A foul mouth`,
			`A fuck-ton of almonds`,
			`A gassy antelope`,
			`A gentle caress of the inner thigh`,
			`A ginger's freckled ballsack`,
			`A good sniff`,
			`A good, strong gorilla`,
			`A gossamer stream of jizz that catches the light as it arcs through the morning air`,
			`A grande sugar-free iced soy caramel macchiato`,
			`A Gypsy curse`,
			`A hairless little shitstain named Callou`,
			`A Halal Snack Pack`,
			`A hen night in Slough`,
			`A homoerotic volleyball montage`,
			`A horde of Vikings`,
			`A hot mess`,
			`A Japanese toaster you can fuck`,
			`A Japanese whaling operation`,
			`A LAN party`,
			`A lifetime of sadness`,
			`A literal tornado of fire`,
			`A little boy who won't shut the fuck up about dinosaurs`,
			`A live studio audience`,
			`A look-see`,
			`A low standard of living`,
			`A mad cow`,
			`A madman who lives in a police box and kidnaps women`,
			`A man in yoga pants with a ponytail and feather earrings`,
			`A man on the brink of orgasm`,
			`A mating display`,
			`A Mexican`,
			`A micropenis`,
			`A micropig wearing a tiny raincoat and booties`,
			`A middle-aged man on roller skates`,
			`A mime having a stroke`,
			`A moment of silence`,
			`A monkey smoking a cigar`,
			`A mopey zoo lion`,
			`A much younger woman`,
			`A murder most foul`,
			`A neglected Tamagotchi™`,
			`A nice cup of tea`,
			`A pangender octopus who roams the cosmos in search of love`,
			`A piñata full of scorpions`,
			`A posh wank`,
			`A PowerPoint presentation`,
			`A pyramid of severed heads`,
			`A really cool hat`,
			`A robust mongoloid`,
			`A sad fat dragon with no friends`,
			`A sad handjob`,
			`A salad for men that's made of metal`,
			`A salty surprise`,
			`A sassy black woman`,
			`A sausage festival`,
			`A saxophone solo`,
			`A sea of troubles`,
			`A shark!`,
			`A sick burnout`,
			`A sick wombat`,
			`A sickly child-king`,
			`A six-point plan to stop the boats`,
			`A slab of VB and a pack of durries`,
			`A slightly shittier parallel universe`,
			`A snapping turtle biting the tip of your penis`,
			`A sober Irishman who doesn't care for potatoes`,
			`A soggy Sao`,
			`A spastic nerd`,
			`A stingray barb through the chest`,
			`A stray pube`,
			`A subscription to Men's Fitness`,
			`A Super Soaker™ full of cat pee`,
			`A surprising amount of hair`,
			`A sweet spaceship`,
			`A thermonuclear detonation`,
			`A thousand Scottish warriors lifting their kilts in unison`,
			`A three-way with my wife and Shaquille O'Neal`,
			`A Tim Hortons franchise`,
			`A time travel paradox`,
			`A tiny horse`,
			`A tiny, gay guitar called a ukulele`,
			`A tribe of warrior women`,
			`A vagina that leads to another dimension`,
			`A vajazzled vagina`,
			`A vastly superior healthcare system`,
			`A vindaloo poo`,
			`A web of lies`,
			`A wheelchair death race`,
			`A white van man`,
			`A whole thing of butter`,
			`A windmill full of corpses`,
			`A wisecracking terrorist`,
			`A zesty breakfast burrito`,
			`Aaron Burr`,
			`Abstinence`,
			`Academy Award winner Meryl Streep`,
			`Accepting the way things are`,
			`Accidentally slipping yourself a roofie`,
			`Active listening`,
			`Actually getting shot, for real`,
			`Actually taking candy from a baby`,
			`Adderall™`,
			`Adult Friendfinder`,
			`Advice from a wise, old black man`,
			`African children`,
			`Agriculture`,
			`AIDS`,
			`Alcohol poisoning`,
			`Alcoholism`,
			`All four prongs of an echidna's penis`,
			`All my friends dying`,
			`All of this blood`,
			`All the dudes I've fucked`,
			`All-you-can-eat shrimp for $4.99`,
			`Altar boys`,
			`America`,
			`American Gladiators`,
			`Americanization`,
			`Amputees`,
			`An AK-47 assault rifle`,
			`An AK-47`,
			`An AR-15 assault rifle`,
			`An argument with Richard Dawkins`,
			`An army of skeletons`,
			`An ass disaster`,
			`An asymmetric boob job`,
			`An endless stream of diarrhea`,
			`An endless stream of diarrhoea`,
			`An entrenched class system`,
			`An erection that lasts longer than four hours`,
			`An Evening with Michael Buble`,
			`An evil man in evil clothes`,
			`An honest cop with nothing left to lose`,
			`An icepick lobotomy`,
			`An icy handjob from an Edmonton hooker`,
			`An M. Night Shyamalan plot twist`,
			`An M16 assault rifle`,
			`An octopus giving seven handjobs and smoking a cigarette`,
			`An Oedipus complex`,
			`An old guy who's almost dead`,
			`An older woman who knows her way around the penis`,
			`An oversized lollipop`,
			`An ugly face`,
			`An unstoppable wave of fire ants`,
			`An unwanted pregnancy`,
			`An uppercut`,
			`Anal beads`,
			`Announcing that I am about to cum`,
			`Another goddamn vampire movie`,
			`Another shot of morphine`,
			`Anything that comes out of Prince Philip's mouth`,
			`Apologizing`,
			`Arnold Schwarzenegger`,
			`Asians who aren't good at math`,
			`Assless chaps`,
			`Attitude`,
			`Auschwitz`,
			`Australia`,
			`Authentic Mexican cuisine`,
			`Autocannibalism`,
			`AXE Body Spray`,
			`Bad discord bots`,
			`Badger culling`,
			`Ball-by-ball commentary from Richie Benaud`,
			`Balls`,
			`Bananas in Pajamas`,
			`Bananas`,
			`Barack Obama`,
			`Basic human decency`,
			`BATMAN!`,
			`BATMAN!!!`,
			`Battlefield amputations`,
			`Becoming a blueberry`,
			`Bees?`,
			`Being a busy adult with many important things to do`,
			`Being a dick to children`,
			`Being a dinosaur`,
			`Being a hideous beast that no one could love`,
			`Being a motherfucking sorcerer`,
			`Being a woman`,
			`Being able to talk to elephants`,
			`Being awesome at sex`,
			`Being black`,
			`Being Canadian`,
			`Being fabulous`,
			`Being fat and stupid`,
			`Being hunted like a fox`,
			`Being marginalised`,
			`Being marginalized`,
			`Being on fire`,
			`Being rich`,
			`Being white`,
			`Benedict Cumberbatch`,
			`Bestiality`,
			`Bill Nye the Science Guy`,
			`Bingeing and purging`,
			`Bio-engineered assault turtles with acid breath`,
			`Bisexuality`,
			`Bitches`,
			`Black people`,
			`Bling`,
			`Blood farts`,
			`Blood, toil, tears, and sweat`,
			`Blowing my boyfriend so hard he shits`,
			`Blowing up Parliament`,
			`Boat people; half boat, half human`,
			`Bogies`,
			`Bond, James Bond`,
			`Bono`,
			`Booby-trapping the house to foil burglars`,
			`Boogers`,
			`Bosnian chicken farmers`,
			`Braiding three penises into a Curly Wurly`,
			`Breaking out into song and dance`,
			`Brexit`,
			`Britney Spears at 55`,
			`Brown people`,
			`Bubble butt bottom boys`,
			`Buckfast Tonic Wine`,
			`Bullshit`,
			`Burning down the White House`,
			`Buying the right pants to be cool`,
			`Canada: America's Hat`,
			`Canadian Netflix`,
			`Canned tuna with extra dolphin`,
			`Capturing Newt Gingrich and forcing him to dance in a monkey suit`,
			`Cards Against Humanity`,
			`Cashed-up bogans`,
			`Casually suggesting a threesome`,
			`Catapults`,
			`Centaurs`,
			`Chainsaws for hands`,
			`Charisma`,
			`Cheating in the Special Olympics`,
			`Cheeky bum sex`,
			`Chemical weapons`,
			`Child abuse`,
			`Child beauty pageants`,
			`Children on leashes`,
			`Chivalry`,
			`Christopher Walken`,
			`Chubby baby seals`,
			`Chundering into a kangaroo's pouch`,
			`Chunks of dead backpacker`,
			`Chunks of dead hitchhiker`,
			`Chunks of dead prostitute`,
			`Chutzpah`,
			`Civilian casualties`,
			`Classist undertones`,
			`Clive Palmer's soft, shitty body`,
			`Coat hanger abortions`,
			`Cock`,
			`Cockfights`,
			`College`,
			`Committing suicide`,
			`Completely unwarranted confidence`,
			`Concealing a boner`,
			`Concealing an erection`,
			`Consensual sex`,
			`Consultants`,
			`Contagious face cancer`,
			`Converting to Islam`,
			`Cookie Monster devouring the Eucharist wafers`,
			`Copping a feel`,
			`Cottaging`,
			`Count Chocula`,
			`Court-ordered rehab`,
			`Covering myself with Parmesan cheese and chili flakes because I am pizza`,
			`Crazy hot cousin sex`,
			`Creed`,
			`Crippling debt`,
			`Crucifixion`,
			`Crumbs all over the bloody carpet`,
			`Crumpets with the Queen`,
			`Crystal meth`,
			`Cuddling`,
			`Cumming deep inside my best bro`,
			`Customer service representatives`,
			`Cybernetic enhancements`,
			`Dad's funny balls`,
			`Daddies Brown Sauce`,
			`Daddies® Brown Sauce`,
			`Daddy issues`,
			`Daddy's belt`,
			`Daniel Radcliffe's delicious asshole`,
			`Danny DeVito`,
			`Dark and mysterious forces beyond our control`,
			`Darth Vader`,
			`Date rape`,
			`Dave Matthews Band`,
			`David Bowie flying in on a tiger made of lightning`,
			`David Cameron`,
			`Dead babies`,
			`Dead birds everywhere`,
			`Dead parents`,
			`Deflowering the princess`,
			`Dental dams`,
			`Denying climate change`,
			`Destroying the evidence`,
			`Dick Cheney`,
			`Dick fingers`,
			`Dick pics`,
			`Dining with cardboard cutouts of the cast of Friends`,
			`Dirty nappies`,
			`Disco fever`,
			`Diversity`,
			`Dogging`,
			`Doin' it in the butt`,
			`Doing a shit in Pudsey Bear's eyehole`,
			`Doing crimes`,
			`Doing the right thing`,
			`Domino's™ Oreo™ Dessert Pizza`,
			`Don Cherry's wardrobe`,
			`Donald Trump`,
			`Double penetration`,
			`Douchebags on their iPhones`,
			`Dr. Martin Luther King, Jr`,
			`Drinking alone`,
			`Drinking out of the toilet and eating garbage`,
			`Dropping a baby down the dunny`,
			`Dropping a chandelier on your enemies and riding the rope up`,
			`Drowning the kids in the bathtub`,
			`Druids`,
			`Drum circles`,
			`Dry heaving`,
			`Dwarf tossing`,
			`Dwayne "The Rock" Johnson`,
			`Dying alone and in pain`,
			`Dying of dysentery`,
			`Dying`,
			`Eastern European Turbo-Folk music`,
			`Eating a hard boiled egg out of my husband's asshole`,
			`Eating all of the cookies before the AIDS bake-sale`,
			`Eating an albino`,
			`Eating the last known bison`,
			`Eating too much of a lamp`,
			`Ecstasy`,
			`Ed Balls`,
			`Edible underpants`,
			`Edible underwear`,
			`Egging an MP`,
			`Elderly Japanese men`,
			`Electricity`,
			`Embryonic stem cells`,
			`Emerging from the sea and rampaging through Tokyo`,
			`Emma Watson`,
			`Emotions`,
			`England`,
			`Erectile dysfunction`,
			`Establishing dominance`,
			`Estrogen`,
			`Ethnic cleansing`,
			`Eugenics`,
			`Euphoria™ by Calvin Klein`,
			`Exactly what you'd expect`,
			`Excalibur`,
			`Exchanging pleasantries`,
			`Executing a hostage every hour`,
			`Existentialists`,
			`Existing`,
			`Expecting a burp and vomiting on the floor`,
			`Explaining how vaginas work`,
			`Explosions`,
			`Extremely tight jeans`,
			`Facebook`,
			`Fading away into nothingness`,
			`Faffing about`,
			`Faith healing`,
			`Fake tits`,
			`FALCON PUNCH!!!`,
			`Famine`,
			`Fancy Feast®`,
			`Farting and walking away`,
			`Farting into your petticoats and wafting it at Lord Gregory`,
			`Fear itself`,
			`Feeding Rosie O'Donnell`,
			`Fellowship in Christ`,
			`Fiery poops`,
			`Fiery poos`,
			`Figgy pudding`,
			`Filling my briefcase with business stuff`,
			`Filling my son with spaghetti`,
			`Filling Sean Hannity with helium and watching him float away`,
			`Finger painting`,
			`Fingering`,
			`Firing a rifle into the air while balls deep in a squealing hog`,
			`Fisting`,
			`Five litres of Special Brew`,
			`Five-Dollar Footlongs™`,
			`Flash flooding`,
			`Flavored condoms`,
			`Flesh-eating bacteria`,
			`Flightless birds`,
			`Flying robots that kill people`,
			`Flying sex snakes`,
			`Forced sterilisation`,
			`Foreskin`,
			`Forgetting the Alamo`,
			`Former President George W. Bush`,
			`Four Loko`,
			`Fox News`,
			`Fragile masculinity`,
			`Free samples`,
			`Friction`,
			`Friendly fire`,
			`Friends who eat all the snacks`,
			`Friends with benefits`,
			`Frolicking`,
			`Front butt`,
			`Fucking my sister`,
			`Fucking the weatherman on live television`,
			`Full frontal nudity`,
			`Funky fresh rhymes`,
			`Gandalf`,
			`Gandhi`,
			`Garth Brooks`,
			`Gary Coleman`,
			`Gary Glitter`,
			`Gay aliens`,
			`Gay conversion therapy`,
			`Geese`,
			`Genetically engineered super-soldiers`,
			`Genghis Khan`,
			`Genital piercings`,
			`Gentleman's Relish®`,
			`Genuine human connection`,
			`German Chancellor Angela Merkel`,
			`German dungeon porn`,
			`Germans on holiday`,
			`Getting a DUI on a Zamboni`,
			`Getting crushed by a vending machine`,
			`Getting cummed on`,
			`Getting drugs off the street and into my body`,
			`Getting drunk on mouthwash`,
			`Getting fingered`,
			`Getting married, having a few kids, buying some stuff, retiring to Florida, and dying`,
			`Getting naked and watching Nickelodeon`,
			`Getting pregnant again`,
			`Getting really high`,
			`Getting so angry that you pop a boner`,
			`Getting wed, having a few kids, taking some pictures, retiring to the south of France, and dying`,
			`Ghosts`,
			`Girls who shouldn't go wild`,
			`Girls`,
			`Giving 110%`,
			`Giving birth to the Antichrist`,
			`Gladiatorial combat`,
			`Glassing a wanker`,
			`Glenn Beck being harried by a swarm of buzzards`,
			`Glenn Beck catching his scrotum on a curtain hook`,
			`Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts`,
			`Glenn Beck`,
			`Global warming`,
			`Gloryholes`,
			`Goats eating cans`,
			`Goblins`,
			`God`,
			`GoGurt®`,
			`Going an entire day without masturbating`,
			`Going around punching people`,
			`Golden showers`,
			`Good-natured, fun-loving Aussie racism`,
			`Grandma`,
			`Grandpa's ashes`,
			`Graphic violence, adult language, and some sexual content`,
			`Grave robbing`,
			`Growing a pair`,
			`Guys who don't call`,
			`Haggis`,
			`Half a kilo of pure China White heroin`,
			`Half-assed foreplay`,
			`Harry Potter erotica`,
			`Have some more kugel`,
			`Having a Golden Gaytime`,
			`Having a penis`,
			`Having a shag in the back of a ute`,
			`Having anuses for eyes`,
			`Having big dreams but no realistic way to achieve them`,
			`Having sex for the first time`,
			`Having sex on top of a pizza`,
			`Having sex with every man in Winnipeg`,
			`Having shotguns for legs`,
			`Heartwarming orphans`,
			`Heath Ledger`,
			`Helplessly giggling at the mention of Hutus and Tutsis`,
			`Her Majesty, Queen Elizabeth II`,
			`Heritage minutes`,
			`Heroin`,
			`Heteronormativity`,
			`Hillary Clinton's emails`,
			`Hip hop jewels`,
			`Hip hop jews`,
			`Hipsters`,
			`Historically black colleges`,
			`Hobos`,
			`Holding down a child and farting all over him`,
			`Home video of Oprah sobbing into a Lean Cuisine®`,
			`Homeless people`,
			`Homo milk`,
			`Hooning`,
			`Hope`,
			`Hormone injections`,
			`Horrifying laser hair removal accidents`,
			`Horse meat`,
			`Hospice care`,
			`Hot cheese`,
			`Hot people`,
			`Hot Pockets®`,
			`How amazing it is to be on mushrooms`,
			`How awesome it is to be white`,
			`How bad my daughter fucked up her dance recital`,
			`How far I can get my own penis up my butt`,
			`How wet my pussy is`,
			`However much weed $20 can buy`,
			`Huffing spray paint`,
			`Huge biceps`,
			`Hulk Hogan`,
			`Hunting "accidents"`,
			`Hurling one's body down a hill in pursuit of a wheel of cheese`,
			`Hurricane Katrina`,
			`I'm friends with your dad on Facebook`,
			`Ice`,
			`Illegal immigrants`,
			`Impotence`,
			`Improvised explosive devices`,
			`Inappropriate yodeling`,
			`Incest`,
			`Indescribable loneliness`,
			`Inserting a Mason jar into my anus`,
			`Intelligent design`,
			`Intimacy problems`,
			`Invading Poland`,
			`Irritable Bowel Syndrome`,
			`Italians`,
			`Itchy pussy`,
			`J.D. Power and his associates`,
			`Jade Goody's cancerous remains`,
			`Jedward`,
			`Jehovah's Witnesses`,
			`Jennifer Lawrence`,
			`Jerking off into a pool of children's tears`,
			`Jesus`,
			`Jew-fros`,
			`Jewish fraternities`,
			`Jews, gypsies, and homosexuals`,
			`Jibber-jabber`,
			`Jimmy Savile`,
			`Jobs`,
			`Joe Biden`,
			`John Howard's eyebrows`,
			`John Wilkes Booth`,
			`Judge Judy`,
			`Judging everyone`,
			`Just touching David Beckham's hair`,
			`Justin Bieber`,
			`Justin Trudeau`,
			`Kamikaze pilots`,
			`Kanye West`,
			`Keanu Reeves`,
			`Keeping Christ in Christmas`,
			`Keg stands`,
			`Kibbles 'n Bits™`,
			`Kids with ass cancer`,
			`Kim Jong-il`,
			`Kim Jong-un`,
			`Kissing grandma on the forehead and turning off her life support`,
			`Knife crime`,
			`Kourtney, Kim, Khloe, Kendall, and Kylie`,
			`Lactation`,
			`Lads`,
			`Lady Gaga`,
			`Lance Armstrong's missing testicle`,
			`Land mines`,
			`Laying an egg`,
			`Leaked footage of Kate Middleton's colonoscopy`,
			`Leaving an awkward voicemail`,
			`Lena Dunham`,
			`Leprosy`,
			`Letting everyone down`,
			`Letting yourself go`,
			`Leveling up`,
			`Liberals`,
			`Licking things to claim them as your own`,
			`Listening to her problems without trying to solve them`,
			`Literally eating shit`,
			`Little boy penises`,
			`Living in a trash can`,
			`Living in Yellowknife`,
			`Lockjaw`,
			`Loki, the trickster god`,
			`Looking in the mirror, applying lipstick, and whispering "tonight, you will have sex with Tom Cruise."`,
			`Loose lips`,
			`Lumberjack fantasies`,
			`Lunchables™`,
			`LYNX® Body Spray`,
			`Mad cow disease`,
			`Madeleine McCann`,
			`Magnets`,
			`Making a friend`,
			`Making a pouty face`,
			`Making sex at her`,
			`Making the penises kiss`,
			`Making up for centuries of oppression with one day of apologising`,
			`Man meat`,
			`Mansplaining`,
			`Many bats`,
			`Marky Mark and the Funky Bunch`,
			`Martha Stewart`,
			`Massive, widespread drought`,
			`Masturbating`,
			`Masturbation`,
			`Mathletes`,
			`Maureen of Blackpool, Reader's Wife of the Year 1988`,
			`Me time`,
			`Me`,
			`MechaHitler`,
			`Memes`,
			`Men discussing their feelings in an emotionally healthy way`,
			`Men`,
			`Menstrual rage`,
			`Menstruation`,
			`Meth`,
			`Michael Jackson`,
			`Michelle Obama's arms`,
			`Mike Pence`,
			`Mild autism`,
			`Miley Cyrus at 55`,
			`Miley Cyrus`,
			`Millions of cane toads`,
			`Millwall fans`,
			`Mining accidents`,
			`Mistaking a retarded person for someone who's merely deaf`,
			`Mom`,
			`Mooing`,
			`Moral ambiguity`,
			`More elephant cock than I bargained for`,
			`Morgan Freeman's voice`,
			`Mountain Dew Code Red`,
			`Mouth herpes`,
			`Mr. Clean, right behind you`,
			`Mr. Dressup`,
			`Mr. Snuffleupagus`,
			`Mr. Squiggle, the Man from the Moon`,
			`Muhammad (Peace Be Upon Him)`,
			`Muhammad (Praise Be Unto Him)`,
			`Multiple orgasms`,
			`Multiple stab wounds`,
			`Murder`,
			`Mutually assured destruction`,
			`Muzzy`,
			`My abusive boyfriend who really isn't so bad once you get to know him`,
			`My balls on your face`,
			`My black ass`,
			`My bright pink fuckhole`,
			`My cheating son-of-a-bitch husband`,
			`My collection of high-tech sex toys`,
			`My collection of Japanese sex toys`,
			`My ex-wife`,
			`My fat daughter`,
			`My father, who died when I was seven`,
			`My first kill`,
			`My genitals`,
			`My good bra`,
			`My humps`,
			`My inner demons`,
			`My machete`,
			`My mate Dave`,
			`My neck, my back, my pussy, and my crack`,
			`My relationship status`,
			`My sex life`,
			`My soul`,
			`My Uber driver, Pavel`,
			`My ugly face and bad personality`,
			`My vagina`,
			`Naked News`,
			`Natalie Portman`,
			`Natural male enhancement`,
			`Natural selection`,
			`Nazis`,
			`NBA superstar LeBron James`,
			`Necrophilia`,
			`New Age music`,
			`Newfies`,
			`Nickelback`,
			`Nicolas Cage`,
			`Nip slips`,
			`Nippers`,
			`Nipple blades`,
			`Nocturnal emissions`,
			`Not contributing to society in any meaningful way`,
			`Not giving a shit about the Third World`,
			`Not having sex`,
			`Not reciprocating oral sex`,
			`Not vaccinating my children because I am stupid`,
			`Not wearing trousers`,
			`Nothing but sand`,
			`Nothing`,
			`Nunchuck moves`,
			`Obesity`,
			`Object permanence`,
			`Oestrogen`,
			`Old-people smell`,
			`Ominous background music`,
			`One Direction's supple, hairless bodies`,
			`One Ring to rule them all`,
			`One titty hanging out`,
			`One trillion dollars`,
			`Only dating Asian women`,
			`Oompa-Loompas`,
			`Opposable thumbs`,
			`Oprah`,
			`Our first chimpanzee President`,
			`Overcompensation`,
			`Overpowering your father`,
			`Oversized lollipops`,
			`Pabst Blue Ribbon`,
			`Pac-Man uncontrollably guzzling cum`,
			`Paedophiles`,
			`Panda sex`,
			`Paris Hilton`,
			`Parting the Red Sea`,
			`Party poopers`,
			`Passable transvestites`,
			`Passing a kidney stone`,
			`Passive-aggression`,
			`Passive-aggressive Post-it notes`,
			`Pauline Hanson`,
			`PCP`,
			`Peanut Butter Jelly Time`,
			`Pedophiles`,
			`Peeing a little bit`,
			`Penis breath`,
			`Penis envy`,
			`People who smell their own socks`,
			`Perfunctory foreplay`,
			`Permanent Orgasm-Face Disorder`,
			`Picking up girls at the abortion clinic`,
			`Pictures of boobs`,
			`Pikies`,
			`Pingers`,
			`Pixelated bukkake`,
			`Playing silly buggers`,
			`Police brutality`,
			`Polish People`,
			`Pooping back and forth. Forever`,
			`Pooping in a laptop and closing it`,
			`Pooping in the soup`,
			`Poopy diapers`,
			`Poor life choices`,
			`Poor people`,
			`Poorly-timed Holocaust jokes`,
			`Popped collars`,
			`Porn stars`,
			`Poutine`,
			`Poverty`,
			`Power`,
			`Powerful thighs`,
			`Prancing`,
			`Praying the gay away`,
			`Prescription pain killers`,
			`Preteens`,
			`Pretending to care`,
			`Profound respect and appreciation for indigenous culture`,
			`Pronouncing the names of northern Welsh towns`,
			`Prosti-tots`,
			`Pterodactyl eggs`,
			`PTSD`,
			`Puberty`,
			`Public ridicule`,
			`Pulling out`,
			`Pumping out a baby every nine months`,
			`Punching a congressman in the face`,
			`Punching an MP in the face`,
			`Puppies!`,
			`Pussy Galore`,
			`Queefing`,
			`Queen Elizabeth's immaculate anus`,
			`Queuing`,
			`Racially-biased SAT questions`,
			`Racism`,
			`Radical Islamic terrorism`,
			`Rap music`,
			`Raping and pillaging`,
			`Raptor attacks`,
			`Re-gifting`,
			`Rehab`,
			`Repression`,
			`Republicans`,
			`Reverse cowgirl`,
			`Rich people`,
			`Riding off into the sunset`,
			`Ring Pops`,
			`Ring Pops™`,
			`Rip Torn dropkicking anti-Semitic lesbians`,
			`Ripping off the Beatles`,
			`Ripping open a man’s chest and pulling out his still-beating heart`,
			`Rising from the grave`,
			`Road head`,
			`Rob Ford`,
			`Robbing a sperm bank`,
			`Robert Downey Jr`,
			`Robert Downey, Jr`,
			`RoboCop`,
			`Rohypnol`,
			`Ronald Reagan`,
			`Roofies`,
			`Rubbing Boris Johnson's belly until he falls asleep`,
			`Running naked through a mall, pissing and shitting everywhere`,
			`Running out of semen`,
			`Rupert Murdoch`,
			`Rush Limbaugh's soft, shitty body`,
			`Ruth Bader Ginsburg brutally gaveling your penis`,
			`Ryan Gosling riding in on a white horse`,
			`Same-sex ice dancing`,
			`Samuel L. Jackson`,
			`Santa Claus`,
			`Sarah Palin`,
			`Saxophone solos`,
			`Saying "I love you."`,
			`Scalping the Milkybar Kid`,
			`Scalping`,
			`Schmirler the Curler`,
			`Science`,
			`Scientology`,
			`Scousers`,
			`Screaming like a maniac`,
			`Scrotum tickling`,
			`Scrubbing under the folds`,
			`Sean Connery`,
			`Sean Penn`,
			`Seduction`,
			`Seeing Grandma naked`,
			`Seeing my father cry`,
			`Seeing what happens when you lock people in a room with hungry seagulls`,
			`Seething with quiet resentment`,
			`Self-flagellation`,
			`Self-loathing`,
			`Selling crack to children`,
			`Selling ice to children`,
			`Seppuku`,
			`Serfdom`,
			`Seven dead and three in critical condition`,
			`Sex with animals`,
			`Sex with Patrick Stewart`,
			`Sexting`,
			`Sexual humiliation`,
			`Sexual peeing`,
			`Sexual tension`,
			`Sexy pillow fights`,
			`Shaking a baby until it stops crying`,
			`Shapeshifters`,
			`Shaquille O'Neal's acting career`,
			`Sharing needles`,
			`Shiny objects`,
			`Shipping convicts to Australia`,
			`Shitting out a perfect Cumberland sausage`,
			`Shitting out a screaming face`,
			`Shorties and blunts`,
			`Showing up to an orgy for the food`,
			`Shutting the fuck up`,
			`Shutting up so I can watch the game`,
			`Sideboob`,
			`Silence`,
			`Sipping artificial popcorn butter`,
			`Sitting on my face and telling me I'm garbage`,
			`Sitting on my face`,
			`Skeletor`,
			`Skippy the Bush Kangaroo`,
			`Slapping a biscuit out of an orphan's mouth`,
			`Slapping a racist old lady`,
			`Slapping Nigel Farage over and over`,
			`Slaughtering innocent civilians`,
			`Slavs`,
			`Smallpox blankets`,
			`Smegma`,
			`Sneezing, farting, and cumming at the same time`,
			`Sniffing glue`,
			`Snotsicles`,
			`Sobbing into a Hungry-Man™ Frozen Dinner`,
			`Soft, kissy missionary sex`,
			`Soiling oneself`,
			`Solving problems with violence`,
			`Somali pirates`,
			`Some bloody peace and quiet`,
			`Some douche with an acoustic guitar`,
			`Some guy`,
			`Some kind of bird man`,
			`Some of the best rappers in the game`,
			`Some punk kid who stole my turkey sandwich`,
			`Some really fucked-up shit`,
			`Sorry, this content cannot be viewed in your region`,
			`Soup that is too hot`,
			`Spaghetti? Again?`,
			`Spaniards`,
			`Spectacular abs`,
			`Spending lots of money`,
			`Sperm whales`,
			`Spontaneous human combustion`,
			`Stalin`,
			`Staring at a painting and going "hmmmmmmm..."`,
			`Stephen Harper`,
			`Stephen Hawking talking dirty`,
			`Steve Bannon`,
			`Steve Irwin`,
			`Stifling a giggle at the mention of Hutus and Tutsis`,
			`Still being a virgin`,
			`Stockholm Syndrome`,
			`Stormtroopers`,
			`Stranger danger`,
			`Strong female characters`,
			`Stunt doubles`,
			`Substitute teachers`,
			`Sucking some dicks to not get drafted`,
			`Sudden Poop Explosion Disease`,
			`Suicidal thoughts`,
			`Summoning Harold Holt from the sea in a time of great need`,
			`Sunshine and rainbows`,
			`Surprise sex!`,
			`Swag`,
			`Sweet, sweet vengeance`,
			`Switching to Geico®`,
			`Swooping`,
			`Synergistic management solutions`,
			`Syrupy sex with a maple tree`,
			`Take-backsies`,
			`Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes`,
			`Taking a sheep-wife`,
			`Taking off your shirt`,
			`Tangled Slinkys`,
			`Tap dancing like there's no tomorrow`,
			`Tasteful sideboob`,
			`Teaching a robot to love`,
			`Team-building exercises`,
			`Tearing that ass up like wrapping paper on Christmas morning`,
			`Teenage pregnancy`,
			`Telling a shitty story that goes nowhere`,
			`Tentacle porn`,
			`Terrorists`,
			`Terry Fox's prosthetic leg`,
			`Testicular torsion`,
			`That ass`,
			`That one gay Teletubby`,
			`That thing that electrocutes your abs`,
			`The American Dream`,
			`The Amish`,
			`The arrival of the pizza`,
			`The art of seduction`,
			`The baby that ruined my pussy`,
			`The Bachelorette season finale`,
			`The Big Bang`,
			`The big fucking hole in the ozone layer`,
			`The Black Death`,
			`The Blood of Christ`,
			`The bloody Welsh`,
			`The BNP`,
			`The bombing of Nagasaki`,
			`The boners of the elderly`,
			`The Boy Scouts of America`,
			`The bush`,
			`The Care Bear Stare`,
			`The Chinese gymnastics team`,
			`The chronic`,
			`The clitoris`,
			`The cool, refreshing taste of Coca-Cola®`,
			`The cool, refreshing taste of Pepsi`,
			`The crazy, ball-slapping sex your parents are having right now`,
			`The Daily Mail`,
			`The Dalai Lama`,
			`The Dance of the Sugar Plum Fairy`,
			`The deformed`,
			`The Devil Himself`,
			`The Donald Trump Seal of Approval.™`,
			`The drama club`,
			`The economy`,
			`The EDL`,
			`The end of days`,
			`The entire cast of Downton Abbey`,
			`The entire Internet`,
			`The entire Mormon Tabernacle Choir`,
			`The female orgasm`,
			`The FLQ`,
			`The flute`,
			`The folly of man`,
			`The forbidden fruit`,
			`The Force`,
			`The French`,
			`The gays`,
			`The glass ceiling`,
			`The Great Depression`,
			`The Great Emu War`,
			`The Gulags`,
			`The Hamburglar`,
			`The hardworking Mexican`,
			`The heart of a child`,
			`The Hemsworth brothers`,
			`The hiccups`,
			`The Hillsborough Disaster`,
			`The Holy Bible`,
			`The homosexual agenda`,
			`The homosexual lifestyle`,
			`The Honey Monster`,
			`The human body`,
			`The Hustle`,
			`The inevitable heat death of the universe`,
			`The invisible hand`,
			`The Jews`,
			`The KKK`,
			`The Kool-Aid Man`,
			`The land of chocolate`,
			`The light of a billion suns`,
			`The Little Engine That Could`,
			`The magic of live theatre`,
			`The Make-A-Wish® Foundation`,
			`The milkman`,
			`The miracle of childbirth`,
			`The morbidly obese`,
			`The North`,
			`The Official Languages Act. La Loi sur les langues officielles`,
			`The only gay person in a hundred kilometers`,
			`The past`,
			`The Patriarchy`,
			`The penny whistle solo from "My Heart Will Go On."`,
			`The People's Elbow`,
			`The petty troubles of the landed gentry`,
			`The pirate's life`,
			`The placenta`,
			`The plot of a Michael Bay movie`,
			`The Pope`,
			`The profoundly handicapped`,
			`The prunes I've been saving for you in my armpits`,
			`The Rapture`,
			`The Red Hot Chili Peppers`,
			`The Red Menace`,
			`The Rev. Dr. Martin Luther King, Jr`,
			`The rhythms of Africa`,
			`The Royal Canadian Mounted Police`,
			`The Russians`,
			`The Scouts`,
			`The screams...the terrible screams`,
			`The Smell of Primark`,
			`The South`,
			`The Stig`,
			`The Strictly Come Dancing season finale`,
			`The sudden appearance of the Go Compare man`,
			`The Superdome`,
			`The taint; the grundle; the fleshy fun-bridge`,
			`The Tempur-Pedic® Swedish Sleep System™`,
			`The terrorists`,
			`The Thong Song`,
			`The Three-Fifths compromise`,
			`The token minority`,
			`The total collapse of the global financial system`,
			`The Trail of Tears`,
			`The true meaning of Christmas`,
			`The Übermensch`,
			`The Underground Railroad`,
			`The unstoppable tide of Islam`,
			`The violation of our most basic human rights`,
			`The Virginia Tech Massacre`,
			`The way James Bond treats women`,
			`The White Australia Policy`,
			`The wifi password`,
			`The wonders of the Orient`,
			`The World of Warcraft`,
			`The wrath of Vladimir Putin`,
			`Theresa May`,
			`These hoes`,
			`Third base`,
			`This answer is postmodern`,
			`This month's mass shooting`,
			`This year's mass shooting`,
			`Those times when you get sand in your vagina`,
			`Three dicks at the same time`,
			`Throwing a virgin into a volcano`,
			`Throwing grapes at a man until he loses touch with reality`,
			`Tickle Me Elmo™`,
			`Tickling Sean Hannity, even after he tells you to stop`,
			`Tiger Woods`,
			`Tiny nipples`,
			`Tom Cruise`,
			`Tongue`,
			`Toni Morrison's vagina`,
			`Tony Abbott in budgie smugglers`,
			`Too much hair gel`,
			`Tories`,
			`Total control of the media`,
			`Touching a pug right on his penis`,
			`Trench foot`,
			`Tripping balls`,
			`Tweeting`,
			`Twenty tonnes of bat shit`,
			`Twinkies®`,
			`Two midgets shitting into a bucket`,
			`Unfathomable stupidity`,
			`Uppercuts`,
			`Used panties`,
			`Vegemite™`,
			`Vehicular manslaughter`,
			`Viagra®`,
			`Vigilante justice`,
			`Vigorous jazz hands`,
			`Vikings`,
			`Vladimir Putin`,
			`Vomiting into a kangaroo's pouch`,
			`Vomiting mid-blowjob`,
			`Vomiting seafood and bleeding anally`,
			`Waiting 'til marriage`,
			`Waking up half-naked in a Denny's parking lot`,
			`Waking up half-naked in a Little Chef car park`,
			`Waking up half-naked in a Macca's car park`,
			`Waking up in Idris Elba's arms`,
			`Walking in on Dad peeing into Mom's mouth`,
			`Wanking into a pool of children's tears`,
			`Waterboarding`,
			`Weapons-grade plutonium`,
			`Wearing an octopus for a hat`,
			`Wearing underwear inside-out to avoid doing laundry`,
			`Wet dreams`,
			`What's left of the Great Barrier Reef`,
			`When you fart and a little bit comes out`,
			`Whining like a little bitch`,
			`Whipping it out`,
			`Whiskas® Catmilk`,
			`White people`,
			`White power`,
			`White privilege`,
			`White-man scalps`,
			`White theme`,
			`Whoever the Prime Minister is these days`,
			`Wifely duties`,
			`Will Smith`,
			`William Shatner`,
			`Winking at old people`,
			`Wiping her butt`,
			`Wizard music`,
			`Women in yoghurt commercials`,
			`Women of color`,
			`Women voting`,
			`Women's suffrage`,
			`Women's undies`,
			`Wondering if it's possible to get some of that salsa to go`,
			`Words`,
			`World peace`,
			`Worshipping that pussy`,
			`Xenophobia`,
			`Yeast`,
			`YOU MUST CONSTRUCT ADDITIONAL PYLONS`,
			`Your mum`,
			`Your weird brother`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
		},
	}

	AddPack(pack)
}
