package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "football",
		Description: "Cards against football pack. V1",
		Prompts: []*PromptCard{
			{Prompt: `Oooooooooooooh. Harvey Barnes, its an %s!`},
			{Prompt: `Football would not be football without: %s.`},
			{Prompt: `%s. Worst thing to ever exist.`},
			{Prompt: `%s>Ronaldo`},
			{Prompt: `%s>Messi`},
			{Prompt: `%s is overrated.`},
			{Prompt: `What a beauty from %s!`},
			{Prompt: `I love %s so much I would lend him my children.`},
			{Prompt: `Come place your bets, ladies and gentlemen! %s vs. %s. Who will win?`},
			{Prompt: `What's worse then being a Spurs fan? %s.`},
			{Prompt: `Rumors say if you say %s infront of a mirror 3x your club will win a quadruple.`},
			{Prompt: `%s won the champions league because they %s.`},
			{Prompt: `Being a %s is better than being a spurs fan.`},
			{Prompt: `%s is by far better than %s.`},
			{Prompt: `%s. Only reason why super league almost happened.`},
			{Prompt: `%s is the definition of a bus.`},
			{Prompt: `If you ever see %s kick a football, %s can drink a cup of tea.`},
			{Prompt: `%s will be the next ballon d’or winner.`},
			{Prompt: `Screw the ref! He is %s`},
			{Prompt: `If my Life would depend on a penalty I would let %s take it for me.`},
			{Prompt: `Roses are red, violets are blue, %s should retire and so should %s.`},
			{Prompt: `There can only be one man to win the UCL, UEL, Euros and World Cup in the same year: %s.`},
			{Prompt: `What the fuck is wrong with %s.`},
			{Prompt: `%s. I wish it never existed.`},
			{Prompt: `%s. Our lord and savior.`},
			{Prompt: `%s: This is why we love football.`},
			{Prompt: `WOW! %s`},
			{Prompt: `I can see the %s at the end of the %s.`},
			{Prompt: `A wise man once said: %s`},
			{Prompt: `Guardiola once said: %s`},
			{Prompt: `%s ~ %s 2021.`},
		},

		Responses: []ResponseCard{
			`Ronaldo`,
			`Mbappe`,
			`Messi`,
			`Lewandowski`,
			`Cruyff`,
			`Pelé`,
			`Zidane`,
			`Scoring a banger`,
			`What a beauty!`,
			`referee`,
			`VAR`,
			`offside`,
			`Real Madrid`,
			`Barca`,
			`Atleti`,
			`Liverpool`,
			`Manchester United`,
			`Manchester City`,
			`Spurs`,
			`Arsenal`,
			`Chelsea`,
			`Ajax`,
			`PSG`,
			`Bayern`,
			`Dortmund`,
			`AC Milan`,
			`Inter Milan`,
			`If history repeats itself, I should think we can expect the same thing again.`,
			`Farmers league`,
			`Aguerooooooooo`,
			`Who on earth is that?`,
			`Fraud`,
			`That amateur player that thinks he is CR7 but runs a total of 100 meters per game`,
			`Jurgen Klopp`,
			`Pep Guardiola`,
			`Tuchel`,
			`A sandwich full of artificial grass`,
			`The least corrupt organization out there; the FIFA`,
			`Liendl`,
			`Vanaken`,
			`Alvarez`,
			`The ball goes down the keeper’s throat where it hits him on the knees to say the least.`,
			`I’d say he’s the best in Europe, if you put me on the fence.`,
			`Football’s football: if that weren’t the case it wouldn’t be the game that it is.`,
			`You either win or you lose. There’s no in between.`,
			`Soccer`,
			`He hits it into the corner of the net as straight as a nut.`,
			`He’s got a knock on his shin there, just above the knee.`,
			`Here we go!`,
			`Everything in our favour was against us.`,
			`What a header!`,
			`Erling Braut Håland`,
			`Hakim Ziyech`,
			`a dick`,
			`twat`,
			`Diego Maradona`,
			`Eusebio`,
			`Beckenbauer`,
			`Rijkaard`,
			`van Dijk`,
			`tu puta madre`,
			`Neymar`,
			`Henderson`,
			`Kane`,
			`Pogba`,
			`Essien`,
			`Kante`,
			`Deez nuts`,
			`fraud`,
			`idiot`,
			`Awful`,
			`Somtimes good, sometimes bad`,
			`That's what she said`,
			`Bald`,
			`corrupted the UEFA`,
			`money grabbing whores`,
			`Fans`,
			`I prefer not to speak`,
			`My mum does not like football`,
			`Simp`,
			`Tell me another story`,
			`Bolingoli`,
			`Kante`,
			`Kante`,
			`Kante`,
			`Kante`,
			`Kante`,
			`Kante`,
			`Kante`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`The  super league doesn't exist`,
			`Here we go`,
			`Future`,
			`Game`,
			`La liga`,
			`Prem`,
			`Seria a`,
			`Budesliga`,
			`Lewagoalski`,
			`Offside`,
			`Jesus`,
			`Jose mounrtihno`,
			`Bolingoli’s Third Leg`,
			`Your mom`,
			`Americans being plastic`,
			`Winning trophies`,
			`made comebacks`,
			`Scoring goals`,
			`Conceding a lot of goals`,
			`Winning the ucl`,
			`Winning the World Cup`,
			`Winning the treble`,
			`Bitches`,
			`Football is played on grass not paper`,
		},
	}

	AddPack(pack)
}
