volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:
  proxy-tier:
    external:
      name: proxy-tier

services:
  app:
    #image: PUT_YOUR_OWN_IMAGE_HERE
    build:
      context: ../
      dockerfile: yagpdb_docker/Dockerfile
    restart: unless-stopped
    command:
      # - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=true"
      - "-https=false"
    depends_on:
      - redis
      - db
    networks:
      - default
      - proxy-tier
    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard
    env_file:
      - app.env

  redis:
    image: docker.io/redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  db:
    image: docker.io/postgres:11
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.env
