version: '3'

volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:
  proxy-tier:
    external:
      name: proxy-tier

services:
  app:
    # We don't provide an official image, but there is a community-made image you can try:
    #  - teyker/yagpdb (https://hub.docker.com/r/teyker/yagpdb)
    #
    # Note that we do not take responsibility for anything that happens as a result of using
    # the image above.
    image: PUT_YOUR_OWN_IMAGE_HERE
    restart: unless-stopped
    command:
      # - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=true"
      - "-https=false"
    depends_on:
      - redis
      - db
    networks:
      - default
      - proxy-tier
    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard
    env_file:
      - app.env

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  db:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.env
