package catfact

// Cat facts collected from vaious sources since the api i used shut down

var Catfacts = []string{
 `Cats sweat through their paws. During hot weather, you might notice their little paw prints on hard surfaces.`,
 `A domestic cat can run at speeds of around 30 miles per hour over short distances.`,
 `Cats can jump up to six times their body length in one leap.`,
 `Just like human fingerprints, each cat's nose print is unique.`,
 `Cats have excellent night vision, allowing them to see with only one-sixth the amount of light that humans need.`,
 `Cats' whiskers aren't just for show—they help them sense their surroundings and navigate tight spaces. Whiskers are roughly as wide as their body!`,
 `Their paws are designed to tread silently, making them efficient hunters.`,
 `Cats sleep for about 12-16 hours a day. In fact, they spend approximately two-thirds of their life sleeping.`,
 `The oldest known cat lived to be 38 years old. Creme Puff from Texas lived from 1967 to 2005!`,
 `Cats often make chirping or chattering noises when they're watching birds or other prey. It's believed to be an expression of frustration or excitement.`,
 `Cats spend a good amount of time grooming themselves, and they might also groom their favorite humans or fellow felines.`,
 `Cats have scent glands on their cheeks, paws, and the base of their tail. When they rub against you or objects, they're marking their territory.`,
 `Cats have a third eyelid, called the haw, which helps protect and moisten their eyes.`,
 `The world's first cat café opened in Taiwan in 1998. They quickly became popular, with many now around the globe.`,
 `Cats were domesticated around 9,000 years ago. The ancient Egyptians worshipped them and kept them as pets.`,
 `Just like humans, cats can be right or left-pawed. Studies show that male cats tend to be left-pawed, while female cats are more often right-pawed.`,
 `Kittens are born with blue eyes, but their eye color usually changes as they grow older.`,
 `The oldest known cat fossil, found in Cyprus, is estimated to be about 9,500 years old.`,
 `Contrary to popular belief, many cats are lactose intolerant, so milk can cause digestive issues for them.`,
 `When cats groom each other, it's called allogrooming. It helps strengthen social bonds and reduce conflict within a group.`,
 `Cats have a wide field of vision, approximately 200 degrees, compared to humans' 180-degree field of vision.`,
 `In ancient Egypt, cats were revered and considered sacred. They were often depicted in art and even mummified to accompany their owners into the afterlife.`,
 `Domestic cats share 95.6% of their genetic makeup with tigers, which is why some of their behaviors, like chuffing or stalking, resemble those of their wild cousins.`,
 `Cats have been known to save their owners' lives by alerting them to dangers such as fires or carbon monoxide leaks.`,
 `Most cats have five toes on their front paws and four on their back paws, but some cats, known as polydactyl cats, have extra toes.`,
 `The Siberian cat is one of the largest domestic cat breeds, with males weighing up to 25 pounds.`,
 `Kittens grow rapidly in their first six months, which is equivalent to a human growing up to a 10-year-old child.`,
 `Cats have about 230-250 bones in their bodies, compared to humans' 206. The exact number can vary because of the length of the cat's tail and the presence of extra toes.`,
 `Cats were once used on ships to control the rodent population. They were considered good luck charms by sailors.`,
 `While most domestic cats aren't fond of getting wet, some breeds, like the Bengal and the Turkish Van, actually enjoy playing in water.`,
 `Most cats are not entirely black or entirely white; they often have a mix of colors in their coat.`,
 `The longest recorded jump by a cat was over seven feet!`,
 `Cats have a unique way of communicating with their human companions, such as meowing, purring, and using body language.`,
 `In ancient Egypt, harming a cat was considered a grave offense, often punishable by death.`,
 `International Cat Day is celebrated on August 8th each year, honoring our beloved feline companions.`,
 `Cats love to climb to high places, as it gives them a good vantage point to survey their surroundings.`,
 `A cat's tail can give insights into its mood. A raised tail often indicates a friendly and confident cat, while a puffed-up tail may signal fear or aggression.`,
 `Cats are known for their grooming habits. They use their tongues to clean their fur, which helps remove loose hair and dirt, spread natural oils, and keep their coat in top condition.`,
 `Even domestic cats retain many hunting instincts from their wild ancestors. They often practice their hunting skills by pouncing on toys or stalking imaginary prey.`,
 `Cats' eyes are highly expressive and can convey a range of emotions. Slow blinking at a cat is a sign of affection and trust, often referred to as "cat kisses."`,
 `Cats can have a wide range of vocalizations, from meows and purrs to chirps and growls. Each cat has its own unique "voice," and they may use different sounds to communicate with humans and other cats.`,
 `Cats have fewer taste buds than humans, but they have an enhanced sense of smell that helps them identify food. They are also more sensitive to bitter tastes.`,
 `Some cats can sleep up to 20 hours a day, especially if they're older or less active.`,
 `The vibrations from a cat's purr can help reduce stress and promote relaxation in humans.`,
 `Cats' tongues are covered in tiny, hook-like structures called papillae, which help them groom their fur and scrape meat from bones.`,
 `In Norse mythology, the goddess Freyja's chariot was said to be pulled by two large cats, symbolizing power and protection.`,
 `Cats can hear frequencies up to 65 kHz, well beyond the range of human hearing (20 kHz).`,
 `Cats often seek out cozy, warm places to sleep, such as a sunny spot, a soft blanket, or even a cardboard box.`,
 `Mother cats communicate with their kittens through gentle purring and touching to reassure and guide them.`,
 `Cats maintain a playful, kitten-like behavior throughout their lives, making them delightful companions.`,
 `Certain cat breeds, like the Siamese, can experience coat color changes based on temperature. Cooler areas of their body may develop darker fur.`,
 `In medieval Europe, cats were often associated with witchcraft and superstition, leading to many being killed. This decrease in the cat population contributed to an increase in the rat population and the spread of the Black Plague.`,
 `The first known pet cat was found in a 9,500-year-old grave on the Mediterranean island of Cyprus.`,
 `In ancient Egypt, cats were often adorned with gold jewelry and treated like royalty.`,
 `Some cats prefer drinking running water and may be fascinated by faucets and water fountains.`,
 `The Maneki-neko, or "beckoning cat," is a common Japanese figurine believed to bring good luck and fortune. It originated in the Edo period (1603-1868).`,
 `During the Middle Ages, cats were sometimes associated with witches and superstition. This led to the unfortunate persecution of cats in some areas. In the Renaissance period, cats regained their status as beloved pets and protectors of households against pests.`,
 `The Hermitage Museum in Saint Petersburg, Russia, has a long tradition of keeping cats to protect its art collections from rodents. This practice dates back to the 18th century.`,
 `Cats have been pets in the White House, including President Abraham Lincoln's cats, Tabby and Dixie, and President Bill Clinton's cat, Socks.`,
 `During World War I and World War II, cats were kept on naval ships for pest control and to provide companionship to sailors.`,
 `In the 1960s, a cat named Félicette was sent into space by the French space agency, making her the first and only cat to travel to space.`,
 `Cats have inspired many artists throughout history, including Leonardo da Vinci, who is known to have sketched cats in his notebooks.`,
 `Cats were kept in medieval monasteries to protect valuable manuscripts from mice and rats. They became essential members of the monastic community.`,
 `In the 18th century, composer Domenico Scarlatti wrote a piece of music inspired by his cat, Pulcinella, who supposedly walked across the keyboard.`,
 `The Prophet Muhammad is said to have had a favorite cat named Muezza. According to legend, he cut off a sleeve of his robe rather than disturb the sleeping cat.`,
 `During the Russian Revolution, cats were a symbol of the bourgeoisie. Many were killed, leading to a rise in the rat population in cities like Saint Petersburg.`,
 `In Turkey, the city of Istanbul is famous for its street cats, which are considered an essential part of the city's cultural heritage.`,
 `A famous Japanese ukiyo-e artist from the Edo period, Kuniyoshi frequently incorporated cats into his woodblock prints, reflecting their importance in Japanese culture.`,
 `Cats may gently bump their heads against you, a behavior known as "bunting." This is their way of marking you with their scent and showing affection.`,
 `The Renaissance genius, Leonardo da Vinci, was known to have a fascination with cats, as seen in his numerous sketches and studies of their anatomy and movements.`,
 `If your cat follows you around the house, it's because they enjoy your company and want to be near you.`,
 `Some cats show their love by bringing "gifts," such as toys or even small prey. It's their way of sharing their accomplishments with you.`,
 `Cats knead with their paws, often on soft surfaces or their favorite humans. This behavior, reminiscent of their kittenhood, is a sign of comfort and love.`,
 `Cats often choose to sleep or rest near their favorite humans. Curling up with you is a sign that they feel safe and loved.`,
 `Engaging in playtime with you is a way for cats to bond and express their love. Interactive toys and games can strengthen the bond between you and your feline friend.`,
 `Cats often lie on their owner's belongings, such as clothes or bags, because they are comforted by their owner's scent.`,
 `Some cats develop unique vocalizations for their owners, using specific meows or chirps to communicate affection and desire for attention.`,
 `When a cat stretches out beside you or exposes their belly, it’s a sign that they feel safe and trust you completely.`,
 `Cats may bring you their favorite toys or engage in playful behavior to invite you to join them in play, which is a form of bonding.`,
 `Cats often sit on their owner's laptop or book, not just because it's warm but also to get your attention and be close to you.`,
 `If a cat chooses to sit on your lap, it's a clear sign that they feel comfortable and safe with you.`,
 `When a cat seeks comfort from you when they're scared or anxious, it's a sign of deep trust and affection.`,
 `Cats have a special sensitivity to electromagnetic fields, which may help explain their ability to detect natural disasters like earthquakes before they happen.`,
 `Cats have a higher body temperature than humans, averaging between 100.5°F to 102.5°F (38°C to 39.2°C). They regulate their temperature through behaviors like seeking warm spots and panting.`,
 `Purring is produced by the rapid movement of muscles within a cat's larynx. The frequency of a cat's purr (between 25 to 150 Hz) is thought to promote healing and reduce pain.`,
 `Cats may gently touch their noses to your face or hand, a behavior similar to how they greet other cats.`,
 `While cats are not completely colorblind, they see fewer colors than humans. They can perceive shades of blue and green but have difficulty distinguishing between reds and pinks.`,
 `Cats can experience whisker stress if their whiskers constantly touch objects, such as deep food bowls. Providing shallow dishes can help reduce this stress.`,
 `Approximately 50-70% of cats are affected by catnip. The response is due to a compound called nepetalactone, which binds to receptors in a cat's nasal tissue and triggers a temporary, pleasurable reaction.`,
 `Cats sleep in short cycles of about 15-30 minutes, with brief periods of deep sleep followed by lighter sleep. This allows them to remain alert to their surroundings.`,
 `Female cats can become pregnant as early as five months old. They can have multiple litters per year, each consisting of 1-9 kittens.`,
 `Cats use their tails to communicate a wide range of emotions. A flicking tail can indicate irritation, while a gently swaying tail shows contentment.`,
 `Cats have incredibly fast reflexes, with a reaction time of approximately 20 to 70 milliseconds. This helps them catch prey and evade danger.`,
 `In 1963, a cat named Félicette became the first and only cat to travel to space. As part of the French space program, Félicette was launched on a suborbital flight to study the effects of space travel on a cat's body. She was chosen for her calm demeanor and underwent special training to prepare for the mission.`,
 `NASA achieved a breakthrough in deep space communication by transmitting a high-definition video of a cat named Taters from 19 million miles away. This experiment, part of the Deep Space Optical Communications (DSOC) project, showcased the potential of laser communication for future space missions.`,
 `Cats were highly revered in ancient Egypt, often associated with the goddess Bastet, who represented home, fertility, and protection. Egyptians believed cats had protective qualities and kept them in households to ward off evil spirits.`,
 `The Siamese cat, originally from Thailand (formerly Siam), is one of the oldest and most recognizable cat breeds. They were considered sacred and kept by royalty.`,
 `The British government has a long-standing tradition of keeping cats in official buildings, such as the Chief Mouser at 10 Downing Street. These cats are cherished for their rodent-catching abilities and have become cultural icons.`,
 `In maritime heritage, polydactyl cats (cats with extra toes) were considered good luck on ships. Sailors believed these cats had superior hunting abilities and brought fortune to their voyages.`,
 `The Turkish Van is a breed of cat known for its love of water. In Turkish culture, they are considered a national treasure, and they are often associated with the Lake Van region.`,
 `Blackie, a cat who lived in the UK, became famous for inheriting a portion of his owner's fortune. When Blackie's owner, Ben Rea, passed away in 1988, he left a £7 million estate to his beloved cat, making Blackie one of the richest cats in history.`,
 `Tommaso, an Italian stray cat, inherited a massive fortune when his owner, Maria Assunta, passed away in 2011. Maria left her entire estate, worth around €10 million, to Tommaso, making him one of the wealthiest cats in the world.`,
 `During the Song Dynasty (960–1279), cats became extremely popular as pets among the nobility. They were often depicted in paintings and poetry, symbolizing elegance and grace.`,
 `According to Chinese mythology, the cat was left out of the Chinese zodiac because of a trick played by the rat. The cat and the rat were supposed to participate in a race organized by the Jade Emperor, but the rat pushed the cat into the water, causing it to miss the race.`,
 `The famous poet Lu You (1125-1210) wrote a series of poems about his pet cats. He described how he traded a bag of salt for a cat to protect his book collection from rats and how the cat became a cherished companion.`,
 `King Charles I of England had a cat he believed to be a source of good luck. The day after his cat died, he was arrested, and he reportedly said, "Alas, my luck has run out.`,
 `Empress Catherine the Great of Russia had cats in her palace, and they were treated with great care. She established the "Cat's House" in the Winter Palace, which still exists today.`,
 `The French queen Marie Antoinette was known to have a great love for cats. She allegedly tried to bring her beloved Turkish Angora cats with her to escape during the French Revolution.`,
 `Some cats have been known to "steal" items from their neighbors. These feline burglars often bring home socks, gloves, and other small objects they find intriguing.`,
 `Some cats have a habit of hoarding toys and other small items. They may stash their treasures in hidden spots around the house.`,
 `Wendy, a cat in the UK, saved her owner, Sam Felstead, by jumping on her chest and meowing loudly when Sam had a heart attack in her sleep. Sam woke up and was able to call for medical assistance.`,
 `Pudding, a cat from Wisconsin, saved her new owner, Amy Jung, just hours after being adopted. Amy, who has diabetes, had a seizure in her sleep. Pudding jumped on her chest, meowed loudly, and even swatted at her face until she woke up and called for help.`,
 `Slinky Malinki, a cat from New Zealand, woke up his owner, Craig Jeeves, by pawing at him and making loud noises when a fire broke out in their home. Thanks to Slinky Malinki, Craig was able to escape safely.`,
 `Buddy, a cat in the US, saved his owner, Angela Martin, by alerting her to a carbon monoxide leak. Buddy's persistent meowing and agitation prompted Angela to check the detector, which was indicating dangerous levels.`,
 `Cats can develop diabetes, similar to humans. It is often managed with insulin injections and a special diet. Early diagnosis and treatment are crucial for managing the condition effectively.`,
 `Dental issues, such as gingivitis and periodontal disease, are common in cats. Regular dental care, including brushing and professional cleanings, can help maintain oral health.`,
 `Cats can develop arthritis, especially as they age. Symptoms include stiffness, limping, and reluctance to jump. Treatment options include pain management, joint supplements, and weight management.`,
 `While many cats enjoy fish, it should be given in moderation. Too much fish can lead to nutritional imbalances and health issues, such as thiamine deficiency.`,
 `Some cats enjoy eating grass. It's thought to aid in digestion and help expel hairballs. However, ensure the grass is free of pesticides and safe for cats.`,
 `Contrary to popular belief, most adult cats are lactose intolerant and can experience digestive upset if given milk. It's best to provide lactose-free alternatives or stick to water.`,
 `While cats thrive on a meat-based diet, it's important to provide a balanced diet that includes all essential nutrients. Commercial cat foods are formulated to meet these needs, but it's always best to consult with a veterinarian for personalized dietary advice.`,
 `Cat treats should be given in moderation and not exceed 10% of a cat's daily caloric intake. Overfeeding treats can lead to obesity and other health issues.`,
 `Both garlic and onion are toxic to cats and can cause gastrointestinal upset and damage to red blood cells. It's important to keep these foods away from cats.`,
 `Adult cats typically do well with two meals a day, but some cats prefer smaller, more frequent meals. Kittens require more frequent feeding due to their higher energy needs.`,
	`Americans really love their pet cats. There are approximately 14 million more house cats than dogs in the US.`,
	`Male cats are called toms and females are called queens or mollies.`,
	`The saying, 'A cat always lands on its feet' isn't just an old myth. Some cats have fallen more than 320 metres onto concrete and come away unharmed.`,
	`There's a reason why cats are likely to survive high falls – they have more time to prepare for the landing.`,
	`It's not a flock, it's not a herd – a group of cats together is known as a 'clowder'.`,
	`According to statistics, cat owners are healthier than those without cats. The risk of heart attack is cut by a third among people who have a pet cat.`,
	`Just as a dog's bark has several different meanings, a cat may purr because it is nervous, happy or feeling unwell.`,
	`It's common knowledge that cats are fans of milk, but many of them are lactose intolerant. This means that they are actually allergic to milk.`,
	`Garfield, the lasagne-loving feline, was featured in the Guinness Book of World Records for being the most widely published cartoon.`,
	`Cats are thought to be pretty smart, and with a brain 90% similar to the human brain, it's no surprise.`,
	`When Abraham Lincoln was US President, he had four pet cats which lived with him in the White House.`,
	`Felicette was the first feline to make a trip to space. She luckily survive the mission and was nicknamed 'Astrocat'.`,
	`If you think of yourself as a 'cat person', you're among 11.5% of people in the world.`,
	`If you're a male with a pet cat, you're more likely to find true love. This is due to the fact that people view cat owners are kind, trustworthy and sensitive.`,
	`The record for the largest number of kittens in the same litter was 19.`,
	`Over her lifetime, a cat called Dusty had a total of 420 kittens.`,
	`The oldest cat to give birth to kittens was called Kitty. She was 30 years old when she birthed her last kittens.`,
	`**Bagpuss** was a 1999 TV show which featured an old cloth cat. In 2001, it came fourth in a poll of the greatest kids' TV shows.`,
	`While people dote over their cats in the West, around 4 million cats are killed and eaten over in Asia.`,
	`There are about 70 different cat breeds and a staggering 500 million pet cats in the world.`,
	`Ancient Egyptians worshipped a goddess who was half cat and half woman.`,
	`In Ancient Egypt, civilians would suffer a severe punishment if they hurt a cat.`,
	`Ever noticed your cat sleeping most of the time? On average, cats sleep for about 16 hours per day.`,
	`Kittens sleep even more often, since growth hormones are released when they are napping.`,
	`The front paws of a cat are different from the back paws. They have five toes on the front but only four on the back`,
	`Some cats are known as 'polydactyl' and have extra toes. Some polydactyl have as many as eight toes per paw.`,
	`Unlike dogs, cats have no sense of what is sweet. No wonder they never seem happy with cakes!`,
	`Did you think the cat flap was an ultra-modern idea? Isaac Newton is credited with the invention of the cat flap – something which most cat owners now have.`,
	`Isaac Newton himself had a cat called Spithead, which influenced his invention. Spithead went on to have kittens, who all got their very own cat flap.`,
	`Many cat owners take their pets to the vet to be neutered, and by doing so, increase the life expectancy of their pets by 2-3 years.`,
	`Cats can see very well in the dark, which explains why they are always wandering around at night.`,
	`Adolf Hitler hated cats, so there's another reason why you shouldn't like him.`,
	`Taurine is an amino acid which can be found in cat food. Without this substance, your pet cat would eventually go blind.`,
	`House cats can run at a speed of 30 miles per hour.`,
	`The kidneys of a cat are quite amazing, since they can filter water before using it. This means that a cat can drink sea water and the salt will be filtered out.`,
	`Those cute furry bits inside a cat's ear are called 'ear furnishings'. They ensure that dirt doesn't go inside and also helps them to hear well.`,
	`Cats have a great sense of hearing and can hear ultrasonic noises. They could potentially hear dolphins`,
	`It's not just humans who are right-handed or left-handed. Most female cats prefer using their right paw, while male are more likely to be 'left-pawed'.`,
	`A 'haw' is the third eyelid of a cat, which can only be seen when the cat isn't well.`,
	`They might have an extra eyelid, but they don't have any eyelashes.`,
	`The original version of Cinderella in Italy featured a cat as the fairy godmother.`,
	`Dogs make 10 different sounds, while cats can make as many as 100 different noises.`,
	`Cats seem like such sweet creatures, but approximately 40,000 people suffer from cat bites every single year in America.`,
	`When you see a cat rubbing up against a human, it is being affectionate but also marking its territory to make other cats aware.`,
	`The cat family consists of many different animals, but the largest is the Siberian Tiger, which can be as large as 12 feet long.`,
	`The black-footed cat is the smallest wild cat, at just 20 inches long.`,
	`The wealthiest cat ever was Blackie, a multi-millionaire. It owned £15 million after its rich owner died.`,
	`London was the home of the first ever cat show. It took place in 1871 and started a trend which has continued ever since.`,
	`While cats like to catch mice and eat them, it's not necessarily a good meal. They can contract tapeworm through eating these rodents.`,
	`Cats' hearts beat at a rate of 110-140 beats per minutes – around twice as fast as the average human.`,
	`Ancient Egyptian cat owners would shave off their eyebrows when mourning for their dead kitties.`,
	`'Mau' is the Egyptian word for cat, and the oldest surviving cat breed is known as the Egyptian Mau, translated to mean the 'Egyptian cat'.`,
	`While people are hesitant to buy cats of opposite sexes, they will actually get along better than those of the same sex.`,
	`If you own a cat, you should feed them 10-20 small meals every day, rather than fewer and larger meals.`,
	`Over the Christmas season, cats should avoid poinsettias as they are poisonous.`,
	`Stray and feral cats which live outdoors have a life span of around 4 years. Those which live indoors can live up to 16 years or more.`,
	`Cats are lovers of fish, but too much tuna can cause them to become addicted to this meat.`,
	`They use their tongues to thoroughly clean themselves, but they also use them to get rid of human scent.`,
	`When cats are first born, they have blue eyes. Over time, the colour changes.`,
	`Kittens also have much sharper teeth than adult cats. Their teeth become blunt when they are around 6 months old.`,
	`Cats which have blue eyes for the duration of their lives are likely to be deaf.`,
	`They usually hate water, but the Turkish Van cats actually enjoy getting wet!`,
	`Just as a human's fingerprints are unique, each cat has a completely different nose.`,
	`Many people are allergic to cats, but cats can actually be allergic to humans too. Around one in 200 domestic cats suffer from asthma due to smoke, dust and other particles within houses.`,
	`As long as you introduce your cat to your dog before they are both six months old, they should get along well.`,
	`Although studies suggested that cats didn't enjoy being stroked by humans, further research has proven that they do in fact like it.`,
	`A cat's brain is so quick that even a super-computer in 2015 couldn't beat it.`,
	`Feral cats will go out exploring more often and much further than house cats. House cats can normally be found within the area they live.`,
	`It is thought that 55% of house cats are obese due to overeating.`,
	`Alzheimer's disease can be found in cats, just as it can be found in humans.`,
	`Cats were first kept as pets about 5,000 years ago in China. Farmers were the first to realise that felines could be kept in the home.`,
	`In 2011, scientists concluded that your pet cat may become very ill if you interfere with its routine.`,
	`The high-pitched cry which you may have heard from your cat is an attempt for cats to get their own way. The cry is similar to that of a new-born baby.`,
	`Cats enjoy sitting on warm objects, which is probably why your kitty likes to sit on your computer so often.`,
	`It's a well-known fact that cats are very fussy creatures, and if your pet doesn't always drink water from its water bowl, it may not like the shape of the bowl!`,
	`Cats might look harmless, but they have worked together to make over 30 different species extinct. Even house cats love hunting, and have contributed heavily to this figure.`,
	`They only sweat through their paws, as this is the only place which has sweat glands.`,
	`In the 1950's, Disneyland bought several cats in order to hunt mice at night. There are now more than 200 felines at the amusement park.`,
	`Their whiskers are used to measure gaps and openings. They allow the cat to work out whether or not they will fit through spaces.`,
	`Historians believe that every species of the cat family came from one of just five different wild cats from Africa.`,
	`Female cats can breed with several males when they are in heat. These means that a litter of kittens could potentially have a few different fathers!`,
	`A cat can rotate each of its ears separately. Each ear has a total of 32 muscles.`,
	`Don't feed chocolate to your cat – it's poisonous.`,
	`Cats are pretty amazing at jumping; they can jump up to seven times higher than the length of their tail.`,
	`There's a charming reason your cat brings dead mice to you. It means that your pet likes you!`,
	`They cannot survive eating a vegetarian diet, which is why it's important to feed your cat meat.`,
	`Cats can find their way home even if they have travelled miles away.`,
	`Black cats are the least likely to be adopted from an animal home, although people love buying jet black kittens.`,
	`A cat's tail will quiver if it is near somebody it loves.`,
	`Think your cat purrs a lot? Cats purr up to 26 times per second.`,
	`Felines enjoy spending time alone. Unlike dogs, they don't need much attention and can be very happy without any companionship.`,
	`You shouldn't feed many cats from the same food bowl. It is very likely that some of them will refuse to eat from it, choosing rather to eat alone.`,
	`Don't stare at your cat for long periods of time. This is seen as threatening and will make it feel uneasy.`,
	`There are many plants which are poisonous for cats, although parsley, sage and other herbs are among a cat's favourite foods.`,
	`If you put a collar on your cat, make sure it's not too tight. You should be able to fit two fingers between the collar and your cat's neck, or you could risk strangling it.`,
	`The fear of cats is known as Ailurophobia.`,
	`A town called Talkeetna in Alaska had a cat as mayor for 15 years.`,
	`The record for the world's longest cat was 48.5 inches.`,
	`Cats do recognise their owners' voices, but often act like they don't care.`,
	`Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.`,
	`When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.`,
	`The technical term for a cat’s hairball is a “bezoar.”`,
	`A group of cats is called a “clowder.”`,
	`A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.`,
	`Cats make about 100 different sounds. Dogs make only about 10.`,
	`Many people in China consider cats a "warming" food that is perfect to eat during the winter`,
	`Every year, nearly four million cats are eaten in Asia.`,
	`There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.`,
	`Approximately 24 cat skins can make a coat.`,
	`While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.`,
	`Content warning // animal cruelty/death ||During the time of the Spanish Inquisition, Pope Innocent VIII condemned cats as evil and thousands of cats were burned. Unfortunately, the widespread killing of cats led to an explosion of the rat population, which exacerbated the effects of the Black Death.||`,
	`Content warning // animal cruelty/death ||During the Middle Ages, cats were associated with withcraft, and on St. John’s Day, people all over Europe would stuff them into sacks and toss the cats into bonfires. On holy days, people celebrated by tossing cats from church towers.||`,
	`The first cat in space was a French cat named Felicette (a.k.a. “Astrocat”) In 1963, France blasted the cat into outer space. Electrodes implanted in her brains sent neurological signals back to Earth. She survived the trip.`,
	`The group of words associated with cat (catt, cath, chat, katze) stem from the Latin catus, meaning domestic cat, as opposed to feles, or wild cat.`,
	`The term “puss” is the root of the principal word for “cat” in the Romanian term pisica and the root of secondary words in Lithuanian (puz) and Low German puus. Some scholars suggest that “puss” could be imitative of the hissing sound used to get a cat’s attention. As a slang word for the female pudenda, it could be associated with the connotation of a cat being soft, warm, and fuzzy.`,
	`Approximately 40,000 people are bitten by cats in the U.S. annually.`,
	`Cats are the world's most popular pets, outnumbering dogs by as many as three to one`,
	`Cats are North America’s most popular pets: there are 73 million cats compared to 63 million dogs. Over 30% of households in North America own a cat.`,
	`According to Hebrew legend, Noah prayed to God for help protecting all the food he stored on the ark from being eaten by rats. In reply, God made the lion sneeze, and out popped a cat.`,
	`A cat’s hearing is better than a dog’s. And a cat can hear high-frequency sounds up to two octaves higher than a human.`,
	`A cat can travel at a top speed of approximately 31 mph (49 km) over a short distance.`,
	`A cat rubs against people not only to be affectionate but also to mark out its territory with scent glands around its face. The tail area and paws also carry the cat’s scent.`,
	`Researchers are unsure exactly how a cat purrs. Most veterinarians believe that a cat purrs by vibrating vocal folds deep in the throat. To do this, a muscle in the larynx opens and closes the air passage about 25 times per second.`,
	`When a family cat died in ancient Egypt, family members would mourn by shaving off their eyebrows. They also held elaborate funerals during which they drank wine and beat their breasts. The cat was embalmed with a sculpted wooden mask and the tiny mummy was placed in the family tomb or in a pet cemetery with tiny mummies of mice.`,
	`In 1888, more than 300,000 mummified cats were found an Egyptian cemetery. They were stripped of their wrappings and carted off to be used by farmers in England and the U.S. for fertilizer.`,
	`Most cats give birth to a litter of between one and nine kittens. The largest known litter ever produced was 19 kittens, of which 15 survived.`,
	`Smuggling a cat out of ancient Egypt was punishable by death. Phoenician traders eventually succeeded in smuggling felines, which they sold to rich people in Athens and other important cities.`,
	`The earliest ancestor of the modern cat lived about 30 million years ago. Scientists called it the Proailurus, which means “first cat” in Greek. The group of animals that pet cats belong to emerged around 12 million years ago.`,
	`The biggest wildcat today is the Siberian Tiger. It can be more than 12 feet (3.6 m) long (about the size of a small car) and weigh up to 700 pounds (317 kg).`,
	`Cats have 300 million neurons; dogs have about 160 million`,
	`A cat’s brain is biologically more similar to a human brain than it is to a dog’s. Both humans and cats have identical regions in their brains that are responsible for emotions.`,
	`Many Egyptians worshipped the goddess Bast, who had a woman’s body and a cat’s head.`,
	`Mohammed loved cats and reportedly his favorite cat, Muezza, was a tabby. Legend says that tabby cats have an “M” for Mohammed on top of their heads because Mohammad would often rest his hand on the cat’s head.`,
	`While many parts of Europe and North America consider the black cat a sign of bad luck, in Britain and Australia, black cats are considered lucky.`,
	`The most popular pedigreed cat is the Persian cat, followed by the Main Coon cat and the Siamese cat.`,
	`The smallest pedigreed cat is a Singapura, which can weigh just 4 lbs (1.8 kg), or about five large cans of cat food. The largest pedigreed cats are Maine Coon cats, which can weigh 25 lbs (11.3 kg), or nearly twice as much as an average cat weighs.`,
	`Some cats have survived falls of over 65 feet (20 meters), due largely to their “righting reflex.” The eyes and balance organs in the inner ear tell it where it is in space so the cat can land on its feet. Even cats without a tail have this ability.`,
	`Some Siamese cats appear cross-eyed because the nerves from the left side of the brain go to mostly the right eye and the nerves from the right side of the brain go mostly to the left eye. This causes some double vision, which the cat tries to correct by “crossing” its eyes.`,
	`Researchers believe the word “tabby” comes from Attabiyah, a neighborhood in Baghdad, Iraq. Tabbies got their name because their striped coats resembled the famous wavy patterns in the silk produced in this city.`,
	`Cats have "nine lives" thanks to a flexible spine and powerful leg and back muscles`,
	`A cat can jump up to five times its own height in a single bound.`,
	`Cats hate the water because their fur does not insulate well when it’s wet. The Turkish Van, however, is one cat that likes swimming. Bred in central Asia, its coat has a unique texture that makes it water resistant.`,
	`The Egyptian Mau is probably the oldest breed of cat. In fact, the breed is so ancient that its name is the Egyptian word for “cat.”`,
	`The first commercially cloned pet was a cat named "Little Nicky." He cost his owner $50,000, making him one of the most expensive cats ever.`,
	`A cat usually has about 12 whiskers on each side of its face.`,
	`A cat’s eyesight is both better and worse than humans. It is better because cats can see in much dimmer light and they have a wider peripheral view. It’s worse because they don’t see color as well as humans do. Scientists believe grass appears red to cats.`,
	`Spanish-Jewish folklore recounts that Adam’s first wife, Lilith, became a black vampire cat, sucking the blood from sleeping babies. This may be the root of the superstition that a cat will smother a sleeping baby or suck out the child’s breath.`,
	`Perhaps the most famous comic cat is the Cheshire Cat in Lewis Carroll’s Alice in Wonderland. With the ability to disappear, this mysterious character embodies the magic and sorcery historically associated with cats.`,
	`The smallest wildcat today is the Black-footed cat. The females are less than 20 inches (50 cm) long and can weigh as little as 2.5 lbs (1.2 kg).`,
	`On average, cats spend 2/3 of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life.`,
	`Most cats sleep around 16 hours a day`,
	`In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat.`,
	`The little tufts of hair in a cat’s ear that help keep out dirt direct sounds into the ear, and insulate the ears are called “ear furnishings.”`,
	`The ability of a cat to find its way home is called “psi-traveling.” Experts think cats either use the angle of the sunlight to find their way or that cats have magnetized cells in their brains that act as compasses.`,
	`Isaac Newton invented the cat flap. Newton was experimenting in a pitch-black room. Spithead, one of his cats, kept opening the door and wrecking his experiment. The cat flap kept both Newton and Spithead happy.`,
	`The world’s rarest coffee, Kopi Luwak, comes from Indonesia where a wildcat known as the luwak lives. The cat eats coffee berries and the coffee beans inside pass through the stomach. The beans are harvested from the cat’s dung heaps and then cleaned and roasted. Kopi Luwak sells for about $500 for a 450 g (1 lb) bag.`,
	`A cat’s jaw can’t move sideways, so a cat can’t chew large chunks of food.`,
	`A cat almost never meows at another cat, mostly just humans. Cats typically will spit, purr, and hiss at other cats.`,
	`Like humans, cats tend to favor one paw over another`,
	`Female cats tend to be right pawed, while male cats are more often left pawed. Interestingly, while 90% of humans are right handed, the remaining 10% of lefties also tend to be male.`,
	`A cat’s back is extremely flexible because it has up to 53 loosely fitting vertebrae. Humans only have 34.`,
	`All cats have claws, and all except the cheetah sheath them when at rest.`,
	`Two members of the cat family are distinct from all others: the clouded leopard and the cheetah. The clouded leopard does not roar like other big cats, nor does it groom or rest like small cats. The cheetah is unique because it is a running cat; all others are leaping cats. They are leaping cats because they slowly stalk their prey and then leap on it.`,
	`A cat lover is called an Ailurophilia (Greek: cat+lover).`,
	`In Japan, cats are thought to have the power to turn into super spirits when they die. This may be because according to the Buddhist religion, the body of the cat is the temporary resting place of very spiritual people.`,
	`Most cats had short hair until about 100 years ago, when it became fashionable to own cats and experiment with breeding.`,
	`One reason that kittens sleep so much is because a growth hormone is released only during sleep.`,
	`Cats have about 130,000 hairs per square inch (20,155 hairs per square centimeter).`,
	`The heaviest cat on record is Himmy, a Tabby from Queensland, Australia. He weighed nearly 47 pounds (21 kg). He died at the age of 10.`,
	`The oldest cat on record was Crème Puff from Austin, Texas, who lived from 1967 to August 6, 2005, three days after her 38th birthday. A cat typically can live up to 20 years, which is equivalent to about 96 human years.`,
	`The lightest cat on record is a blue point Himalayan called Tinker Toy, who weighed 1 pound, 6 ounces (616 g). Tinker Toy was 2.75 inches (7 cm) tall and 7.5 inches (19 cm) long.`,
	`Approximately 1/3 of cat owners think their pets are able to read their minds.`,
	`The tiniest cat on record is Mr. Pebbles, a 2-year-old cat that weighed 3 lbs (1.3 k) and was 6.1 inches (15.5 cm) high.`,
	`A commemorative tower was built in Scotland for a cat named Towser, who caught nearly 30,000 mice in her lifetime.`,
	`In the 1750s, Europeans introduced cats into the Americas to control pests.`,
	`The first cat show was organized in 1871 in London. Cat shows later became a worldwide craze.`,
	`The first cartoon cat was Felix the Cat in 1919. In 1940, Tom and Jerry starred in the first theatrical cartoon “Puss Gets the Boot.” In 1981 Andrew Lloyd Weber created the musical Cats, based on T.S. Eliot’s Old Possum’s Book of Practical Cats.`,
	`The normal body temperature of a cat is between 100.5 ° and 102.5 °F. A cat is sick if its temperature goes below 100 ° or above 103 °F.`,
	`A cat has 230 bones in its body. A human has 206. A cat has no collarbone, so it can fit through any opening the size of its head.`,
	`Cats control the outer ear using 32 muscles; humans use 6`,
	`Cats have 32 muscles that control the outer ear (humans have only 6). A cat can independently rotate its ears 180 degrees.`,
	`A cat’s nose pad is ridged with a unique pattern, just like the fingerprint of a human.`,
	`If they have ample water, cats can tolerate temperatures up to 133 °F.`,
	`Foods that should not be given to cats include onions, garlic, green tomatoes, raw potatoes, chocolate, grapes, and raisins. Though milk is not toxic, it can cause an upset stomach and gas. Tylenol and aspirin are extremely toxic to cats, as are many common houseplants. Feeding cats dog food or canned tuna that’s for human consumption can cause malnutrition.`,
	`A 2007 Gallup poll revealed that both men and women were equally likely to own a cat.`,
	`A cat’s heart beats nearly twice as fast as a human heart, at 110 to 140 beats a minute.`,
	`In just seven years, a single pair of cats and their offspring could produce a staggering total of 420,000 kittens.`,
	`Relative to its body size, the clouded leopard has the biggest canines of all animals’ canines. Its dagger-like teeth can be as long as 1.8 inches (4.5 cm).`,
	`Cats spend nearly 1/3 of their waking hours cleaning themselves.`,
	`Grown cats have 30 teeth. Kittens have about 26 temporary teeth, which they lose when they are about 6 months old.`,
	`Cat paws act as tempetature regulators, shock absorbers, hunting and grooming tools, sensors, and more`,
	`Cats don’t have sweat glands over their bodies like humans do. Instead, they sweat only through their paws.`,
	`A cat called Dusty has the known record for the most kittens. She had more than 420 kittens in her lifetime.`,
	`The largest cat breed is the Ragdoll. Male Ragdolls weigh between 12 and 20 lbs (5.4-9.0 k). Females weigh between 10 and 15 lbs (4.5-6.8 k).`,
	`Cats are extremely sensitive to vibrations. Cats are said to detect earthquake tremors 10 or 15 minutes before humans can.`,
	`In contrast to dogs, cats have not undergone major changes during their domestication process.`,
	`A female cat is called a queen or a molly.`,
	`In the 1930s, two Russian biologists discovered that color change in Siamese kittens depend on their body temperature. Siamese cats carry albino genes that work only when the body temperature is above 98° F. If these kittens are left in a very warm room, their points won’t darken and they will stay a creamy white.`,
	`There are up to 60 million feral cats in the United States alone.`,
	`The oldest cat to give birth was Kitty who, at the age of 30, gave birth to two kittens. During her life, she gave birth to 218 kittens.`,
	`The most traveled cat is Hamlet, who escaped from his carrier while on a flight. He hid for seven weeks behind a panel on the airplane. By the time he was discovered, he had traveled nearly 373,000 miles (600,000 km).`,
	`In Holland’s embassy in Moscow, Russia, the staff noticed that the two Siamese cats kept meowing and clawing at the walls of the building. Their owners finally investigated, thinking they would find mice. Instead, they discovered microphones hidden by Russian spies. The cats heard the microphones when they turned on.`,
	`The most expensive cat was an Asian Leopard cat (ALC)-Domestic Shorthair (DSH) hybrid named Zeus. Zeus, who is 90% ALC and 10% DSH, has an asking price of £100,000 ($154,000).`,
	`The cat who holds the record for the longest non-fatal fall is Andy. He fell from the 16th floor of an apartment building (about 200 ft/.06 km) and survived.`,
	`The richest cat is Blackie who was left £15 million by his owner, Ben Rea.`,
	`The claws on the cat’s back paws aren’t as sharp as the claws on the front paws because the claws in the back don’t retract and, consequently, become worn.`,
	`Cats are the most popular pet in the United States: There are 88 million pet cats and 74 million dogs.`,
	`There are cats who have survived falls from over 32 stories (320 meters) onto concrete.`,
	`Cats have over 20 muscles that control their ears.`,
	`Cats sleep 70% of their lives.`,
	`A cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.`,
	`A cat ran for mayor of Mexico City in 2013.`,
	`In tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.`,
	`When cats grimace, they are usually "taste-scenting." They have an extra organ that, with some breathing control, allows the cats to taste-sense the air.`,
	`The world's largest cat measured 48.5 inches long.`,
	`Owning a cat can reduce the risk of stroke and heart attack by a third.`,
	`The world's richest cat is worth $13 million after his human passed away and left her fortune to him.`,
	`Similarly, the frequency of a domestic cat's purr is the same at which muscles and bones repair themselves.`,
	`Adult cats only meow to communicate with humans,`,
	`Cats are often lactose intolerant, so stop givin' them milk!`,
	`The oldest cat video on YouTube dates back to 1894 (when it was made, not when it was uploaded, duh).`,
	`In the 1960s, the CIA tried to turn a cat into a bonafide spy by implanting a microphone into her ear and a radio transmitter at the base of her skull. She somehow survived the surgery but got hit by a taxi on her first mission.`,
	`Female cats are typically right-pawed while male cats are typically left-pawed.`,
	`Basically, cats have a lower social IQ than dogs but can solve more difficult cognitive problems when they feel like it.`,
	`Cats are magical. Here's a cute cat for you. :3 - https://giphy.com/gifs/JIX9t2j0ZTN9S`,
	`Cats have 1,000 times more data storage than an iPad.`,
	`Isaac Newton is credited with inventing the cat door.`,
	`A house cat is faster than Usain Bolt.`,
	`When cats leave their poop uncovered, it is a sign of aggression to let you know they don't fear you.`,
	`Cats use their whiskers to detect if they can fit through a space.`,
	`A cat's nose is ridged with a unique pattern, just like a human fingerprint.`,
	`Cats lick themselves to get *your* scent off, not theirs... Nice try though...`,
	`Ancient Egyptians shaved off their eyebrows to mourn the death of their cats.`,
	`Cat gut, used in tennis rackets and strings for musical instruments does not come from cats, but from sheep.`,
	`Cat urine glows under a black light.`,
	`A cat rubs against people to mark them as their territory.`,
	`Unlike humans, cats have kidneys that can filter out salt and use the water content to hydrate their bodies.`,
	`The furry tufts on the inside of cats’ ears are called "ear furnishings".`,
	`Cats can hear the ultrasonic noises that rodents (and dolphins) make to communicate.`,
	`The ridged pattern on a cat’s nose is as unique as a human fingerprint.`,
	`Cats can’t see directly below their noses. That’s why they miss food that’s right in front of them.`,
	`Isaac Newton invented the cat flap after his own cat, Spithead, kept opening the door and spoiling his light experiments.`,
	`Kittens start to dream when they’re about a week old.`,
	`Kittens sleep a lot because their bodies release a growth hormone only when they’re asleep.`,
	`Adult cats don’t release any particular key hormones during sleep. They just snooze all day because they *can*.`,
	`Cats sleep so much that by the time a cat is 9 years old, it will only have been awake for three years of its life.`,
	`Most female cats are right-pawed, and most male cats favour their left paws.`,
	`Cats sweat through the pads of their paws.`,
	`Cats have a third eyelid called a "haw". It’s generally only visible when they’re unwell.`,
	`Cats can run 3 mph faster than Usain Bolt.`,
}
