// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testVerificationConfigs(t *testing.T) {
	t.Parallel()

	query := VerificationConfigs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testVerificationConfigsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVerificationConfigsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := VerificationConfigs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVerificationConfigsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VerificationConfigSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVerificationConfigsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := VerificationConfigExists(ctx, tx, o.GuildID)
	if err != nil {
		t.Errorf("Unable to check if VerificationConfig exists: %s", err)
	}
	if !e {
		t.Errorf("Expected VerificationConfigExists to return true, but got false.")
	}
}

func testVerificationConfigsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	verificationConfigFound, err := FindVerificationConfig(ctx, tx, o.GuildID)
	if err != nil {
		t.Error(err)
	}

	if verificationConfigFound == nil {
		t.Error("want a record, got nil")
	}
}

func testVerificationConfigsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = VerificationConfigs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testVerificationConfigsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := VerificationConfigs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testVerificationConfigsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	verificationConfigOne := &VerificationConfig{}
	verificationConfigTwo := &VerificationConfig{}
	if err = randomize.Struct(seed, verificationConfigOne, verificationConfigDBTypes, false, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}
	if err = randomize.Struct(seed, verificationConfigTwo, verificationConfigDBTypes, false, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = verificationConfigOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = verificationConfigTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VerificationConfigs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testVerificationConfigsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	verificationConfigOne := &VerificationConfig{}
	verificationConfigTwo := &VerificationConfig{}
	if err = randomize.Struct(seed, verificationConfigOne, verificationConfigDBTypes, false, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}
	if err = randomize.Struct(seed, verificationConfigTwo, verificationConfigDBTypes, false, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = verificationConfigOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = verificationConfigTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testVerificationConfigsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVerificationConfigsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(verificationConfigColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVerificationConfigsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVerificationConfigsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VerificationConfigSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVerificationConfigsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := VerificationConfigs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	verificationConfigDBTypes = map[string]string{`GuildID`: `bigint`, `Enabled`: `boolean`, `VerifiedRole`: `bigint`, `PageContent`: `text`, `KickUnverifiedAfter`: `integer`, `WarnUnverifiedAfter`: `integer`, `WarnMessage`: `text`, `LogChannel`: `bigint`, `DMMessage`: `text`}
	_                         = bytes.MinRead
)

func testVerificationConfigsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(verificationConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(verificationConfigColumns) == len(verificationConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testVerificationConfigsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(verificationConfigColumns) == len(verificationConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &VerificationConfig{}
	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, verificationConfigDBTypes, true, verificationConfigPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(verificationConfigColumns, verificationConfigPrimaryKeyColumns) {
		fields = verificationConfigColumns
	} else {
		fields = strmangle.SetComplement(
			verificationConfigColumns,
			verificationConfigPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := VerificationConfigSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testVerificationConfigsUpsert(t *testing.T) {
	t.Parallel()

	if len(verificationConfigColumns) == len(verificationConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := VerificationConfig{}
	if err = randomize.Struct(seed, &o, verificationConfigDBTypes, true); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VerificationConfig: %s", err)
	}

	count, err := VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, verificationConfigDBTypes, false, verificationConfigPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize VerificationConfig struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert VerificationConfig: %s", err)
	}

	count, err = VerificationConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
