package automod_legacy

// This list is in alphabethical order
// Open a pr or bug me on discord if you want a word added
var BuiltinSwearWords = map[string]bool{
	"anal":                  true,
	"anus":                  true,
	"arse":                  true,
	"ass":                   true,
	"asshat":                true,
	"asshole":               true,
	"b1tch":                 true,
	"ballsack":              true,
	"bastard":               true,
	"Bellend":               true,
	"biatch":                true,
	"bitch":                 true,
	"blowjob":               true,
	"bollock":               true,
	"bollocks":              true,
	"bollok":                true,
	"boner":                 true,
	"bugger":                true,
	"buttplug":              true,
	"child-fucker":          true,
	"clitoris":              true,
	"cock":                  true,
	"cocksukka":             true,
	"cokmuncher":            true,
	"Cúl Tóna":              true,
	"cum":                   true,
	"cunt":                  true,
	"Dick head":             true,
	"dick":                  true,
	"dipshit":               true,
	"dyke":                  true,
	"effing":                true,
	"fag":                   true,
	"faggot":                true,
	"feck":                  true,
	"felching":              true,
	"fellate":               true,
	"fellatio":              true,
	"Fils de Salope":        true,
	"fingerfuck":            true,
	"fuck":                  true,
	"fucks":                 true,
	"fudgepacker":           true,
	"fvck":                  true,
	"gangbang":              true,
	"gangbanged":            true,
	"gangbangs":             true,
	"Gobdaw":                true,
	"jerk":                  true,
	"jizz":                  true,
	"knobend":               true,
	"Monte de Merda":        true,
	"muff":                  true,
	"muthafecker":           true,
	"nigga":                 true,
	"nigger":                true,
	"Penis Head":            true,
	"penisfucker":           true,
	"Póg mo thóin":          true,
	"Pompinara":             true,
	"pu55y":                 true,
	"pube":                  true,
	"Putain":                true,
	"queer":                 true,
	"Rego Do Cu":            true,
	"Salope":                true,
	"shitass":               true,
	"shitfuck":              true,
	"slut":                  true,
	"smegma":                true,
	"son of a whore":        true,
	"son-of-a-bitch":        true,
	"spunk":                 true,
	"Téigh go dtí ifreann!": true,
	"tit":                   true,
	"tits":                  true,
	"tittiefucker":          true,
	"titty":                 true,
	"tosser":                true,
	"trannies":              true,
	"tranny":                true,
	"turd":                  true,
	"twat":                  true,
	"vagina":                true,
	"Vai Para o Caralho":    true,
	"Váyase a la Mierda":    true,
	"wank":                  true,
	"whore":                 true,
	"Wichser":               true,
	"Xуй":                   true,
	"блядь":                 true,
	"Хуй тебе́!":             true,
	"년":                    true,
	"씨방새":                 true,
	"좆 같은 놈/년":           true,
	"くたばれ、ボケ":          true,
	"ぶす":                   true,
	"やりまん":               true,
	"去你的":                 true,
}
