// Code generated by SQLBoiler 4.19.5 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TwitchAnnouncement is an object representing the database table.
type TwitchAnnouncement struct {
	GuildID int64  `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	Message string `boil:"message" json:"message" toml:"message" yaml:"message"`
	Enabled bool   `boil:"enabled" json:"enabled" toml:"enabled" yaml:"enabled"`

	R *twitchAnnouncementR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L twitchAnnouncementL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TwitchAnnouncementColumns = struct {
	GuildID string
	Message string
	Enabled string
}{
	GuildID: "guild_id",
	Message: "message",
	Enabled: "enabled",
}

var TwitchAnnouncementTableColumns = struct {
	GuildID string
	Message string
	Enabled string
}{
	GuildID: "twitch_announcements.guild_id",
	Message: "twitch_announcements.message",
	Enabled: "twitch_announcements.enabled",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var TwitchAnnouncementWhere = struct {
	GuildID whereHelperint64
	Message whereHelperstring
	Enabled whereHelperbool
}{
	GuildID: whereHelperint64{field: "\"twitch_announcements\".\"guild_id\""},
	Message: whereHelperstring{field: "\"twitch_announcements\".\"message\""},
	Enabled: whereHelperbool{field: "\"twitch_announcements\".\"enabled\""},
}

// TwitchAnnouncementRels is where relationship names are stored.
var TwitchAnnouncementRels = struct {
}{}

// twitchAnnouncementR is where relationships are stored.
type twitchAnnouncementR struct {
}

// NewStruct creates a new relationship struct
func (*twitchAnnouncementR) NewStruct() *twitchAnnouncementR {
	return &twitchAnnouncementR{}
}

// twitchAnnouncementL is where Load methods for each relationship are stored.
type twitchAnnouncementL struct{}

var (
	twitchAnnouncementAllColumns            = []string{"guild_id", "message", "enabled"}
	twitchAnnouncementColumnsWithoutDefault = []string{"guild_id", "message"}
	twitchAnnouncementColumnsWithDefault    = []string{"enabled"}
	twitchAnnouncementPrimaryKeyColumns     = []string{"guild_id"}
	twitchAnnouncementGeneratedColumns      = []string{}
)

type (
	// TwitchAnnouncementSlice is an alias for a slice of pointers to TwitchAnnouncement.
	// This should almost always be used instead of []TwitchAnnouncement.
	TwitchAnnouncementSlice []*TwitchAnnouncement

	twitchAnnouncementQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	twitchAnnouncementType                 = reflect.TypeOf(&TwitchAnnouncement{})
	twitchAnnouncementMapping              = queries.MakeStructMapping(twitchAnnouncementType)
	twitchAnnouncementPrimaryKeyMapping, _ = queries.BindMapping(twitchAnnouncementType, twitchAnnouncementMapping, twitchAnnouncementPrimaryKeyColumns)
	twitchAnnouncementInsertCacheMut       sync.RWMutex
	twitchAnnouncementInsertCache          = make(map[string]insertCache)
	twitchAnnouncementUpdateCacheMut       sync.RWMutex
	twitchAnnouncementUpdateCache          = make(map[string]updateCache)
	twitchAnnouncementUpsertCacheMut       sync.RWMutex
	twitchAnnouncementUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single twitchAnnouncement record from the query using the global executor.
func (q twitchAnnouncementQuery) OneG(ctx context.Context) (*TwitchAnnouncement, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single twitchAnnouncement record from the query.
func (q twitchAnnouncementQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TwitchAnnouncement, error) {
	o := &TwitchAnnouncement{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for twitch_announcements")
	}

	return o, nil
}

// AllG returns all TwitchAnnouncement records from the query using the global executor.
func (q twitchAnnouncementQuery) AllG(ctx context.Context) (TwitchAnnouncementSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all TwitchAnnouncement records from the query.
func (q twitchAnnouncementQuery) All(ctx context.Context, exec boil.ContextExecutor) (TwitchAnnouncementSlice, error) {
	var o []*TwitchAnnouncement

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TwitchAnnouncement slice")
	}

	return o, nil
}

// CountG returns the count of all TwitchAnnouncement records in the query using the global executor
func (q twitchAnnouncementQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all TwitchAnnouncement records in the query.
func (q twitchAnnouncementQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count twitch_announcements rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q twitchAnnouncementQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q twitchAnnouncementQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if twitch_announcements exists")
	}

	return count > 0, nil
}

// TwitchAnnouncements retrieves all the records using an executor.
func TwitchAnnouncements(mods ...qm.QueryMod) twitchAnnouncementQuery {
	mods = append(mods, qm.From("\"twitch_announcements\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"twitch_announcements\".*"})
	}

	return twitchAnnouncementQuery{q}
}

// FindTwitchAnnouncementG retrieves a single record by ID.
func FindTwitchAnnouncementG(ctx context.Context, guildID int64, selectCols ...string) (*TwitchAnnouncement, error) {
	return FindTwitchAnnouncement(ctx, boil.GetContextDB(), guildID, selectCols...)
}

// FindTwitchAnnouncement retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTwitchAnnouncement(ctx context.Context, exec boil.ContextExecutor, guildID int64, selectCols ...string) (*TwitchAnnouncement, error) {
	twitchAnnouncementObj := &TwitchAnnouncement{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"twitch_announcements\" where \"guild_id\"=$1", sel,
	)

	q := queries.Raw(query, guildID)

	err := q.Bind(ctx, exec, twitchAnnouncementObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from twitch_announcements")
	}

	return twitchAnnouncementObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *TwitchAnnouncement) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TwitchAnnouncement) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no twitch_announcements provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(twitchAnnouncementColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	twitchAnnouncementInsertCacheMut.RLock()
	cache, cached := twitchAnnouncementInsertCache[key]
	twitchAnnouncementInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			twitchAnnouncementAllColumns,
			twitchAnnouncementColumnsWithDefault,
			twitchAnnouncementColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(twitchAnnouncementType, twitchAnnouncementMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(twitchAnnouncementType, twitchAnnouncementMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"twitch_announcements\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"twitch_announcements\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into twitch_announcements")
	}

	if !cached {
		twitchAnnouncementInsertCacheMut.Lock()
		twitchAnnouncementInsertCache[key] = cache
		twitchAnnouncementInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single TwitchAnnouncement record using the global executor.
// See Update for more documentation.
func (o *TwitchAnnouncement) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the TwitchAnnouncement.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TwitchAnnouncement) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	twitchAnnouncementUpdateCacheMut.RLock()
	cache, cached := twitchAnnouncementUpdateCache[key]
	twitchAnnouncementUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			twitchAnnouncementAllColumns,
			twitchAnnouncementPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update twitch_announcements, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"twitch_announcements\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, twitchAnnouncementPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(twitchAnnouncementType, twitchAnnouncementMapping, append(wl, twitchAnnouncementPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update twitch_announcements row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for twitch_announcements")
	}

	if !cached {
		twitchAnnouncementUpdateCacheMut.Lock()
		twitchAnnouncementUpdateCache[key] = cache
		twitchAnnouncementUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q twitchAnnouncementQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q twitchAnnouncementQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for twitch_announcements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for twitch_announcements")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TwitchAnnouncementSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TwitchAnnouncementSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), twitchAnnouncementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"twitch_announcements\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, twitchAnnouncementPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in twitchAnnouncement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all twitchAnnouncement")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *TwitchAnnouncement) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TwitchAnnouncement) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no twitch_announcements provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(twitchAnnouncementColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	twitchAnnouncementUpsertCacheMut.RLock()
	cache, cached := twitchAnnouncementUpsertCache[key]
	twitchAnnouncementUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			twitchAnnouncementAllColumns,
			twitchAnnouncementColumnsWithDefault,
			twitchAnnouncementColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			twitchAnnouncementAllColumns,
			twitchAnnouncementPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert twitch_announcements, could not build update column list")
		}

		ret := strmangle.SetComplement(twitchAnnouncementAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(twitchAnnouncementPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert twitch_announcements, could not build conflict column list")
			}

			conflict = make([]string, len(twitchAnnouncementPrimaryKeyColumns))
			copy(conflict, twitchAnnouncementPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"twitch_announcements\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(twitchAnnouncementType, twitchAnnouncementMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(twitchAnnouncementType, twitchAnnouncementMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert twitch_announcements")
	}

	if !cached {
		twitchAnnouncementUpsertCacheMut.Lock()
		twitchAnnouncementUpsertCache[key] = cache
		twitchAnnouncementUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single TwitchAnnouncement record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *TwitchAnnouncement) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single TwitchAnnouncement record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TwitchAnnouncement) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TwitchAnnouncement provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), twitchAnnouncementPrimaryKeyMapping)
	sql := "DELETE FROM \"twitch_announcements\" WHERE \"guild_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from twitch_announcements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for twitch_announcements")
	}

	return rowsAff, nil
}

func (q twitchAnnouncementQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q twitchAnnouncementQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no twitchAnnouncementQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from twitch_announcements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for twitch_announcements")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o TwitchAnnouncementSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TwitchAnnouncementSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), twitchAnnouncementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"twitch_announcements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, twitchAnnouncementPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from twitchAnnouncement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for twitch_announcements")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *TwitchAnnouncement) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no TwitchAnnouncement provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TwitchAnnouncement) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTwitchAnnouncement(ctx, exec, o.GuildID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TwitchAnnouncementSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty TwitchAnnouncementSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TwitchAnnouncementSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TwitchAnnouncementSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), twitchAnnouncementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"twitch_announcements\".* FROM \"twitch_announcements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, twitchAnnouncementPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TwitchAnnouncementSlice")
	}

	*o = slice

	return nil
}

// TwitchAnnouncementExistsG checks if the TwitchAnnouncement row exists.
func TwitchAnnouncementExistsG(ctx context.Context, guildID int64) (bool, error) {
	return TwitchAnnouncementExists(ctx, boil.GetContextDB(), guildID)
}

// TwitchAnnouncementExists checks if the TwitchAnnouncement row exists.
func TwitchAnnouncementExists(ctx context.Context, exec boil.ContextExecutor, guildID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"twitch_announcements\" where \"guild_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID)
	}
	row := exec.QueryRowContext(ctx, sql, guildID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if twitch_announcements exists")
	}

	return exists, nil
}

// Exists checks if the TwitchAnnouncement row exists.
func (o *TwitchAnnouncement) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TwitchAnnouncementExists(ctx, exec, o.GuildID)
}
