package throw

import (
	"math/rand"
)

func randomThing() string {
	return throwThings[rand.Intn(len(throwThings))]
}

// If you want somthing added submit a pr
var throwThings = []string{
	"anime girls",
	"b1nzy",
	"bad jokes",
	"a boom box",
	"garliko~ (from GBDS)",
	"old cheese",
	"heroin",
	"sadness",
	"depression",
	"an evil villain with a plan to destroy earth",
	"a superhero on his way to stop an evil villain",
	"jonas747#0001",
	"Elyas, he'll never forget you, he'll add you to a list, and every few months he'll ping you from alt accounts and threaten to sue you. He's harmless though and kinda funny",
	"Soggy Saussages",
	"Borbot and his minions who will occasionally make you question your existence.",
	"Weird dad jokes from savage",
	"The office memes, often used incorrectly",
	"Angry rants",
	"hot firemen",
	"fat idiots",
	"a hairy potter",
	"a hen wearing a tie",
	"a soft knife",
	"a sharp pillow",
	"love",
	"hate",
	"a tomato",
	"a time machine that takes 1 year to travel 1 year into the future",
	"sadness disguised as happiness",
	"debt",
	"all your imaginary friends",
	"homelessness",
	"stupid bot commands",
	"bad bots",
	"ol' musky",
	"wednesday, my dudes",
	"wednesday frog",
	"flat earthers",
	"round earthers",
	"prequel memes",
	"logan paul and jake paul",
	"selfbots",
	"very big fish",
	"ur mum",
	"the biggest fattest vape",
	"donald trump's wall",
	"smash mouth - all star",
	"H4sIABaqgVoA/1WPvW7FIAyFd57ibHmOTlWWrlVHenFIGrCvwCTi7a9Dq0rZ0Pn5OP6kqRBYULV4jlQqVJDkIPclDTvLCV0JpSWq8BxQBUEwuzcsLSU8JOdNM7FOFefqFfOUrbLxvnGELINzSkuBJ0UkvcyKpUg2XocYviC27tyMn1YVp2f2UDJ6t+5qEy7mQpQM6d5F1SP7nYbdONhqtWnOfdBxseTqx+34CzxverIFlxzk5JtRGsMXMd64M1ClMqK31P+/j9JvRvXdXhK+O930cYd9u9HAru0X+gIEKbNKeQEAAA==",
	"death",
	"tide pods",
	"a happy life with a good career and a nice family",
	"a sad life with a dead-end career and a horrible family",
	"divorce papers",
	"an engagement ring",
	"yourself",
	"nothing",
	"insults",
	"compliments",
	"life advice",
	"scams",
	"nothing",
	"crappy code",
	"2 million ping",
	"myself",
	"easter eggs",
	"explosives",
	"a black hole",
	"cheap servers",
	"babies",
	"oranges",
	"eggs",
	"cream puffs",
	"plasma grenades",
	"human body parts",
	"Whitney",
	"a wedding",
	"a car",
	"a chair",
	"a rickroll",
	"money",
	"an 8ball",
	"crabs",
	"bits of the sky",
	"useless polls",
	"a television",
	"a bus",
	"expensive cheese",
	"lame memes",
	"spaghetti",
	"cats",
	"free games",
	"birds",
	"potatoes",
	"a football stadium",
	"water",
	"an alarm clock",
	"air",
	"electricity",
	"music",
	"jail time",
	"watches",
	"bookshelves",
	"the sun",
	"trains",
	"iron",
	"paper",
	"a random city",
	"cheap radios",
	"doors",
	"pie",
	"squares",
	"a duck",
	"lily from at&t",
	"couples therapy",
	"beans",
	"a discord channel",
	"a box of never to be used cables",
	"a soggy waffle",
	"the remote control that was lost under the couch for 3 years",
	"a single, extremely judgmental-looking grape",
	"a participation trophy",
	"a slightly damp sock",
	"a collection of mismatched Tupperware lids",
	"the last slice of pizza that everyone was too polite to take",
	"a bag of holding (it's empty)",
	"a signed photo of a confused pigeon",
	"a 'World's Okayest Employee' mug",
	"a rubber duck wearing a tiny wizard hat",
	"a USB drive that only contains 57 copies of the same cat photo",
	"a half-eaten sandwich",
	"a plastic straw from 2004",
	"a dictionary with all the vowels missing",
	"a very aggressive kazoo",
	"a cloud that looks suspiciously like a potato",
	"a jar of air from the 90s",
	"a cardboard box labeled 'IMPORTANT TRASH'",
	"a sentient slice of toast",
	"a haunted toaster",
	"a bag of 'extra' IKEA screws",
	"a printer that only works when it's not being watched",
	"a coupon for a free hug (terms and conditions apply)",
	"a 20-year-old receipt that is completely blank",
	"a single flip-flop found at the beach",
	"a VHS tape of Shrek with the label 'Taxes 2005'",
	"a pizza box containing exactly one crust",
	"a cactus wearing a tiny sweater",
	"a 1000-piece puzzle with 999 pieces",
	"a USB cable that only charges at a 2-degree angle",
	"a motivational poster of a cat that says 'Hang in there!'",
	"a half-peeled sticker",
	"a battery that's been in the junk drawer since 1998",
	"a DVD of a movie that doesn't exist",
	"a clump of glitter that will never leave your carpet",
	"a map of a city that was built entirely out of cheese",
	"a pair of glasses with one lens missing",
	"a rock that looks like a celebrity",
	"a library book that's 42 years overdue",
	"a fortune cookie that says 'Error: Fortune not found'",
	"a rubber band that is about to snap",
	"a sandwich with the crusts cut off, but the crusts are what's being thrown",
	"a cloud of mild inconvenience",
	"a sentient paperclip that wants to help you write a letter",
	"a disco ball that only reflects sadness",
	"a trophy for 'Participation in Participation'",
	"a single, very confused ant",
	"a bookmark that is actually just a slice of ham",
	"a collection of lint from a dryer",
	"a small, very polite ghost",
	"a taco that is actually a burrito in disguise",
	"a wind-up toy that won't stop making noise",
	"a piece of paper with 'The Game' written on it",
	"a single sock that has lost its partner",
	"a box of cereal with only crumbs left",
	"a pen that ran out of ink just as you were signing a check",
	"a pair of scissors that can't cut anything",
	"a flashlight with a dying battery",
	"a 1 percent battery notification that won't go away",
	"a single, very persistent mosquito",
	"a cold cup of tea that you've already forgotten about",
	"a pair of headphones with a broken left earbud",
	"a slice of bread that's been toasted on only one side",
	"a collection of empty toilet paper rolls",
	"a remote-controlled car that only goes backwards",
	"a very small teapot that can only hold one drop of water",
	"a packet of ketchup that's impossible to open",
	"a list of chores that you'll definitely do tomorrow",
	"a pillow that is always warm on both sides",
	"a pair of jeans with a tiny hole in the pocket where all your change falls out",
	"a single, very judgmental goldfish",
	"a map that only leads to the nearest grocery store",
	"a collection of pens that all ran out of ink at the same time",
	"a very short extension cord",
	"a bag of popcorn with 50% unpopped kernels",
	"a single, very small cloud that only rains on you",
	"a pair of shoes that squeaks with every step",
	"a book with the last chapter missing",
	"a television that only plays weather reports from 1982",
	"a clock that's always 5 minutes fast",
	"a single, very confused bee",
	"a box of chocolates where all the fillings are mystery-flavored",
	"a pair of socks with a hole in the big toe",
	"a very large key that doesn't fit any lock",
	"a single, very small marble",
	"a bottle of invisible ink that you've already lost",
	"a collection of buttons from shirts you've long since thrown away",
	"a very enthusiastic but untalented tuba player",
}
