package advice

import (
	"math/rand"
)

func randomAdvice() string {
	return adviceList[rand.Intn(len(adviceList))]
}

// advicelist generated using chat-gpt.
var adviceList = []string{
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
	"Believe in yourself and all that you are.",
	"Don't be afraid to ask for help when you need it.",
	"Keep learning; education doesn't end after school.",
	"Take time to appreciate the small things in life.",
	"Stay positive, even in difficult times.",
	"Listen more than you speak.",
	"Be patient; good things take time.",
	"Take care of your health; it's your most valuable asset.",
	"Set goals and work towards them consistently.",
	"Be kind to others; kindness is never wasted.",
}
