// this package provides core functinality to yagpdb, important security stuff here
package common

var Verbs = []string{
    "accept",
    "accuse",
    "achieve",
    "acknowledge",
    "acquire",
    "act",
    "add",
    "admire",
    "admit",
    "advise",
    "afford",
    "agree",
    "allow",
    "bake",
    "be",
    "bear",
    "beg",
    "begin",
    "behave",
    "believe",
    "bend",
    "bet",
    "bite",
    "blind",
    "blush",
    "can",
    "care",
    "carry",
    "catch",
    "change",
    "climb",
    "confirm",
    "consist",
    "contain",
}
