// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAutomodViolations(t *testing.T) {
	t.Parallel()

	query := AutomodViolations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAutomodViolationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAutomodViolationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AutomodViolations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAutomodViolationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AutomodViolationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAutomodViolationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AutomodViolationExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AutomodViolation exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AutomodViolationExists to return true, but got false.")
	}
}

func testAutomodViolationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	automodViolationFound, err := FindAutomodViolation(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if automodViolationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAutomodViolationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AutomodViolations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAutomodViolationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AutomodViolations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAutomodViolationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	automodViolationOne := &AutomodViolation{}
	automodViolationTwo := &AutomodViolation{}
	if err = randomize.Struct(seed, automodViolationOne, automodViolationDBTypes, false, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}
	if err = randomize.Struct(seed, automodViolationTwo, automodViolationDBTypes, false, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = automodViolationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = automodViolationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AutomodViolations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAutomodViolationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	automodViolationOne := &AutomodViolation{}
	automodViolationTwo := &AutomodViolation{}
	if err = randomize.Struct(seed, automodViolationOne, automodViolationDBTypes, false, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}
	if err = randomize.Struct(seed, automodViolationTwo, automodViolationDBTypes, false, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = automodViolationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = automodViolationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testAutomodViolationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAutomodViolationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(automodViolationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAutomodViolationToOneAutomodRuleUsingRule(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AutomodViolation
	var foreign AutomodRule

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, automodRuleDBTypes, false, automodRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodRule struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.RuleID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Rule().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := AutomodViolationSlice{&local}
	if err = local.L.LoadRule(ctx, tx, false, (*[]*AutomodViolation)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Rule == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Rule = nil
	if err = local.L.LoadRule(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Rule == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testAutomodViolationToOneSetOpAutomodRuleUsingRule(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AutomodViolation
	var b, c AutomodRule

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, automodViolationDBTypes, false, strmangle.SetComplement(automodViolationPrimaryKeyColumns, automodViolationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, automodRuleDBTypes, false, strmangle.SetComplement(automodRulePrimaryKeyColumns, automodRuleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, automodRuleDBTypes, false, strmangle.SetComplement(automodRulePrimaryKeyColumns, automodRuleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*AutomodRule{&b, &c} {
		err = a.SetRule(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Rule != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RuleAutomodViolations[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.RuleID, x.ID) {
			t.Error("foreign key was wrong value", a.RuleID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.RuleID))
		reflect.Indirect(reflect.ValueOf(&a.RuleID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.RuleID, x.ID) {
			t.Error("foreign key was wrong value", a.RuleID, x.ID)
		}
	}
}

func testAutomodViolationToOneRemoveOpAutomodRuleUsingRule(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AutomodViolation
	var b AutomodRule

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, automodViolationDBTypes, false, strmangle.SetComplement(automodViolationPrimaryKeyColumns, automodViolationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, automodRuleDBTypes, false, strmangle.SetComplement(automodRulePrimaryKeyColumns, automodRuleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetRule(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveRule(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Rule().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Rule != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.RuleID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.RuleAutomodViolations) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAutomodViolationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAutomodViolationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AutomodViolationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAutomodViolationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AutomodViolations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	automodViolationDBTypes = map[string]string{`ID`: `bigint`, `GuildID`: `bigint`, `UserID`: `bigint`, `RuleID`: `bigint`, `CreatedAt`: `timestamp with time zone`, `Name`: `text`}
	_                       = bytes.MinRead
)

func testAutomodViolationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(automodViolationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(automodViolationColumns) == len(automodViolationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAutomodViolationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(automodViolationColumns) == len(automodViolationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AutomodViolation{}
	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, automodViolationDBTypes, true, automodViolationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(automodViolationColumns, automodViolationPrimaryKeyColumns) {
		fields = automodViolationColumns
	} else {
		fields = strmangle.SetComplement(
			automodViolationColumns,
			automodViolationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AutomodViolationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAutomodViolationsUpsert(t *testing.T) {
	t.Parallel()

	if len(automodViolationColumns) == len(automodViolationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AutomodViolation{}
	if err = randomize.Struct(seed, &o, automodViolationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AutomodViolation: %s", err)
	}

	count, err := AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, automodViolationDBTypes, false, automodViolationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AutomodViolation struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AutomodViolation: %s", err)
	}

	count, err = AutomodViolations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
