// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAutomodLists(t *testing.T) {
	t.Parallel()

	query := AutomodLists()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAutomodListsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAutomodListsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AutomodLists().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAutomodListsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AutomodListSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAutomodListsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AutomodListExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AutomodList exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AutomodListExists to return true, but got false.")
	}
}

func testAutomodListsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	automodListFound, err := FindAutomodList(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if automodListFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAutomodListsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AutomodLists().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAutomodListsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AutomodLists().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAutomodListsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	automodListOne := &AutomodList{}
	automodListTwo := &AutomodList{}
	if err = randomize.Struct(seed, automodListOne, automodListDBTypes, false, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}
	if err = randomize.Struct(seed, automodListTwo, automodListDBTypes, false, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = automodListOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = automodListTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AutomodLists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAutomodListsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	automodListOne := &AutomodList{}
	automodListTwo := &AutomodList{}
	if err = randomize.Struct(seed, automodListOne, automodListDBTypes, false, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}
	if err = randomize.Struct(seed, automodListTwo, automodListDBTypes, false, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = automodListOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = automodListTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testAutomodListsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAutomodListsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(automodListColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAutomodListsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAutomodListsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AutomodListSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAutomodListsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AutomodLists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	automodListDBTypes = map[string]string{`ID`: `bigint`, `GuildID`: `bigint`, `Name`: `text`, `Kind`: `integer`, `Content`: `ARRAYtext`}
	_                  = bytes.MinRead
)

func testAutomodListsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(automodListPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(automodListColumns) == len(automodListPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAutomodListsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(automodListColumns) == len(automodListPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AutomodList{}
	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, automodListDBTypes, true, automodListPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(automodListColumns, automodListPrimaryKeyColumns) {
		fields = automodListColumns
	} else {
		fields = strmangle.SetComplement(
			automodListColumns,
			automodListPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AutomodListSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAutomodListsUpsert(t *testing.T) {
	t.Parallel()

	if len(automodListColumns) == len(automodListPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AutomodList{}
	if err = randomize.Struct(seed, &o, automodListDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AutomodList: %s", err)
	}

	count, err := AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, automodListDBTypes, false, automodListPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AutomodList struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AutomodList: %s", err)
	}

	count, err = AutomodLists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
