#!/bin/bash

export YAGPDB_OWNER="Insert owner id here"
export YAGPDB_BOTID="Insert bot ID here"
export YAGPDB_CLIENTID="Insert client id here"
export YAGPDB_CLIENTSECRET="Insert client secret here"
export YAGPDB_BOTTOKEN="Bot token_here"

#Used for the website, required for https
export YAGPDB_HOST="somehost.com"   
export YAGPDB_EMAIL="insert@email.here"      

export YAGPDB_PQUSERNAME="postgres username"
export YAGPDB_PQPASSWORD="postgres password"
export YAGPDB_REDIS="redis address"

# Logging, not required
# Send errors to a discord channel
export YAGPDB_ERRORCHANNEL=""
# Bot leaves joins to this channel
export YAGPDB_BOTLEAVESJOINS=""

# Plugins below, not required

# Aylien
export YAGPDB_AYLIENAPPID="aylien app id here"
export YAGPDB_AYLIENAPPKEY="aylien app key here"

# Reddit
export YAGPDB_REDDIT_CLIENTID="Reddit application clientid here"
export YAGPDB_REDDIT_CLIENTSECRET="Reddit application client secret here"
export YAGPDB_REDDIT_REDIRECT="Reddit redirect uri here"
export YAGPDB_REDDIT_REFRESHTOKEN="Reddit never-ending refreshtoken here (duration=permanent)"

# Youtube and other google apis credentials json file
export GOOGLE_APPLICATION_CREDENTIALS="path/to/credentials.json"