#!/bin/bash


export YAGPDB_OWNER="Insert owner id here" #owner has access to all control panels
export YAGPDB_BOTID="Insert bot ID here"
export YAGPDB_CLIENTID="Insert client id here" # Needed for oauth
export YAGPDB_CLIENTSECRET="Insert client secret here" # Needed for oauth
export YAGPDB_BOTTOKEN="Bot token_here" # "Bot " needs to be before the actual token 

#Used for the website, required for https
export YAGPDB_HOST="somehost.com"   
export YAGPDB_EMAIL="insert@email.here"      

export YAGPDB_PQUSERNAME="postgres username"
export YAGPDB_PQPASSWORD="postgres password"
export YAGPDB_REDIS="redis address"

#Plugins, not required
export YAGPDB_AYLIENAPPID="aylien app id here"
export YAGPDB_AYLIENAPPKEY="aylien app key here"
