// This file is generated by SQLBoiler (https://github.com/volatiletech/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	ReputationConfigs string
	ReputationLog     string
	ReputationUsers   string
}{
	ReputationConfigs: "reputation_configs",
	ReputationLog:     "reputation_log",
	ReputationUsers:   "reputation_users",
}
