package automod

// This list is in alphabethical order
// Open a pr or bug me on discord if you want a word added
var BuiltinSwearWords = map[string]bool{
	"anal":         true,
	"anus":         true,
	"arse":         true,
	"ass":          true,
	"ballsack":     true,
	"balls":        true,
	"bastard":      true,
	"bitch":        true,
	"biatch":       true,
	"blowjob":      true,
	"blow job":     true,
	"bollock":      true,
	"bollok":       true,
	"boner":        true,
	"boob":         true,
	"bugger":       true,
	"bum":          true,
	"butt":         true,
	"buttplug":     true,
	"clitoris":     true,
	"cock":         true,
	"coon":         true,
	"crap":         true,
	"cunt":         true,
	"damn":         true,
	"dick":         true,
	"dildo":        true,
	"dyke":         true,
	"fag":          true,
	"feck":         true,
	"fellate":      true,
	"fellatio":     true,
	"felching":     true,
	"fuck":         true,
	"fudgepacker":  true,
	"fudge packer": true,
	"flange":       true,
	"Goddamn":      true,
	"hell":         true,
	"homo":         true,
	"jerk":         true,
	"jizz":         true,
	"knobend":      true,
	"knob end":     true,
	"labia":        true,
	"lmao":         true,
	"lmfao":        true,
	"muff":         true,
	"nigger":       true,
	"nigga":        true,
	"penis":        true,
	"piss":         true,
	"poop":         true,
	"prick":        true,
	"pube":         true,
	"pussy":        true,
	"queer":        true,
	"scrotum":      true,
	"sex":          true,
	"shit":         true,
	"sh1t":         true,
	"slut":         true,
	"smegma":       true,
	"spunk":        true,
	"tit":          true,
	"tosser":       true,
	"turd":         true,
	"twat":         true,
	"vagina":       true,
	"wank":         true,
	"whore":        true,
}
