---
name: Comment PR

on:
  pull_request:
    branches:
      - master

jobs:
  comment_pr:
    name: Comment PR to master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment
        if: ${{ github.actor != 'ashishjh-bst' || github.actor != github.repository_owner }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hey @${{ github.actor }}! Thank you for your pull request.
            However, please do not open pull requests against `master`, as stated in
            [CONTRIBUTING.md](../../CONTRIBUTING.md):
            > [...] make a PR to the dev branch (botlabs-gg/yagpdb/dev)

            To change the base branch, edit the this pull request and select the new base.
            To prevent conflicts, either `git merge upstream/dev` to your local branch, or
            rebase your local branch onto dev, like so: `git rebase upstream/dev`.
            Afterwards, (force) push your branch, and you're set!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
